### ISSUE TITLE
As a departmental/college administrator I would like to create a collection for our masters theses, and have multiple people be able to contribute/manage the collection so that we can fulfill our departmental obligations.

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1019]
This would probably be useful for a lot of users, but in this case one of the departments are required to submit their theses to ScholarSphere, and would like to create a collection based on that, but have multiple people be able to manage it.

**Comment by carolyncole** [comment]
This would be adding the Collaborators like we have in works to the collection form:
https://scholarsphere-qa.libraries.psu.edu/concern/generic_works/new#share

This was removed in Sufia 7, but was present in one of the later version of Sufia 6

**Comment by carolyncole** [comment]
This is only for the permissions to the collection, not for the works within the collection.
