### ISSUE TITLE
Searches Table is getting large

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1025]
Blacklight store searches in a table.  It is currently getting very large.  We should look into truncating the table.

**Comment by carolyncole** [comment]
Store the data to disk for future data mining and then truncate the table.  Do it either monthly or yearly with a new dated file each time.  Put it in as a cron job.  The file should be saved to a location where is will not be deleted.

**Comment by jrpatterson** [comment]
For now the table has been dumped to a file and truncated.  If you want it restored to a "new table" for analysis let me know:
/users/cam156/ssprodrail.searches-2012-2017.20171115.gz
