### ISSUE TITLE
Review multiple Item Input techniques

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1027]
Do we want to use simple form, handlebar and mustache, or some other way of creating our forms.  

At this point we have a mixture between the two.

**Comment by carolyncole** [comment]
Look at the two techniques and decide which would be easier to maintain into the future.
  * Accessibility
  * Make sense to developer for maintenance
  * Ease of Testing

**Comment by mtribone** [comment]
Created a note in Box to explore options and gather some ideas.

https://psu.box.com/s/z7m5s1nws4wpettkx2wf4bncm28rtmve

**Comment by carolyncole** [comment]
We should discuss this during the retrospective

**Comment by carolyncole** [comment]
We should rewrite the Moustache with Simple form and the existing jbuilder template to match hyrax
