### ISSUE TITLE
Can't Continue Uploading Files when Generic File Error Occurs

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#103]
I select the "upload" button from my listing of files and go to the upload screen. Select checkbox for deposit agreement, select multiple files from dashboard, and select "start upload." I get an "error occured when creating a generic file." The only way that I can move forward is to select the link to edit metadata in the flash message. Not readily apparent to me what to do next until I scroll up and read message. See screen shot.

![screen shot 2015-04-02 at 2 41 25 pm](https://cloud.githubusercontent.com/assets/4163828/6971002/78316350-d947-11e4-9a67-ab3abdfa023e.png)

**Comment by carolyncole** [comment]
This will be fixed with PCDM.
