### ISSUE TITLE
BatchEditsController passes user instead of ability

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#1038]
The BatchEditsController uses passes the current user as the parameter in `#edit`, when it should be the current ability. Although the controller is passing the wrong class, and BatchEditForm expects the second parameter to be the ability and not user, the form still appears to work. However, we should correct this as some point.

**Comment by carolyncole** [comment]
Change this line to pass current_ability: https://github.com/psu-stewardship/scholarsphere/blob/develop/app/controllers/batch_edits_controller.rb#L13
