### ISSUE TITLE
Creator search should return results from LDAP

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#1041]
When adding creators to a work, we need to search beyond the existing users in the system, and include all PSU users in LDAP. Results returned would include PSU id as well as email. Users can select which sources to search, whether existing users or users from LDAP.
![creator-form](https://user-images.githubusercontent.com/312085/30645320-5dd31d4c-9de3-11e7-876a-8d72d64faf52.png)

**Comment by awead** [comment]
Depends on #961

**Comment by awead** [comment]
@cam156 This is to capture the discussion from this morning. I will should be able to add the additional fields to the UI, but might need some help from @mtribone with the dropdown.

**Comment by mtribone** [comment]
When searching the existing users in the new system, does it match on creator name? Which is the display name?

**Comment by carolyncole** [comment]
It matches with Person surname and given name.
