### ISSUE TITLE
Embargo and Lease do not show properly on the FileSet edit

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1050]
This work is embargoed:
![screen shot 2017-10-23 at 10 16 24 am](https://user-images.githubusercontent.com/1599081/31894029-26d1c246-b7db-11e7-918b-53fe6868a78e.png)

The FileSet does not show the embargo during edit.
![screen shot 2017-10-23 at 10 14 35 am](https://user-images.githubusercontent.com/1599081/31893984-0b253cee-b7db-11e7-8ccc-0d7470f14d86.png)

**Comment by carolyncole** [comment]
Can we enable Embargoes on Files Sets?
How would the users feel if that is not a possiblity?

**Comment by mtribone** [comment]
*Existing Work*
I'm not able to reproduce the error. Here are my steps:

1. Edit an existing public work
1. Change visibility to embargo
1. Apply changes to contents of the work
1. Edit a fileset from the list of items in the work
1. Select Permissions tab

![screen shot 2018-03-28 at 1 51 31 pm](https://user-images.githubusercontent.com/4163828/38047029-338e98d6-328f-11e8-972e-1db643adc53d.png)

*New Work with Emargo*
1. Create a new work
1. Add required metadata
1. Set visibility to embargo
1. Add files
1. Save
1. Edit fileset from the list of items in the work
1. Select Permissions tab

![screen shot 2018-03-28 at 2 15 17 pm](https://user-images.githubusercontent.com/4163828/38048118-8513c99e-3292-11e8-9a08-8b1899cbbdf2.png)

**Comment by mtribone** [comment]
*Existing Work*

![screen shot 2018-03-28 at 1 51 31 pm](https://user-images.githubusercontent.com/4163828/38048205-bbd6c8dc-3292-11e8-96c3-6f7af8476ac3.png)


*New Work with Embargo*

![screen shot 2018-03-28 at 2 15 17 pm](https://user-images.githubusercontent.com/4163828/38048196-b7ddf4a8-3292-11e8-994f-b50dfa67e13f.png)

**Comment by mtribone** [comment]
Leaving a note from Slack conversation

Job
https://github.com/samvera/sufia/blob/master/app/jobs/attach_files_to_work_job.rb#L12

Override AttachFilesToWorkJob and add any embargoes and leases from the work to the file set. Verify that work has embargo or lease at that point.

**Comment by carolyncole** [comment]
Visibility is being copied down to the file set on create, but the embargo and lease is not being copied down to the file set.  This could be a timing error based on the fact that the embargo or lease has not yet been created when the FileSet is attached to the work or vice versa.
