### ISSUE TITLE
Add Readme Section

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1052]
refs #747.  Display the contents of the README on the work show page

Put it in a prominent portion of the page (aka under the description)

**Comment by carolyncole** [comment]
We will support text and mark down formats. Need to sanitize the contents of the README

Display file_set.content.content (sanitized and formatted) We may want to store this into solr during the to_solr of the work

**Comment by mtribone** [comment]
@olendorf Here is the display of a message without a README and the output of a README file.

No README

![screen shot 2018-04-02 at 10 59 41 am](https://user-images.githubusercontent.com/4163828/38201206-65e59d82-3665-11e8-9397-0a086cb85aa9.png)


With a README (unofficial README)

![screen shot 2018-04-02 at 11 04 13 am](https://user-images.githubusercontent.com/4163828/38201251-a1c5cc28-3665-11e8-81f0-aa64708976d0.png)

**Comment by olendorf** [comment]
@mtribone  looks great to me.
