### ISSUE TITLE
Add identifier field to collections

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1054]
Several users have submitted data as collections of stuff even when they have works. Essentially they needed more hierarchy than is provided by works. The result is that we need to be able to identify collections with DOIs. I've already been providing DOIs for collections in a couple cases, and the DOI resolves to the collection. So we just need to be able to have a DOI field for collections to be fully consistent.

**Comment by carolyncole** [comment]
The identifier is in under additional fields.
