### ISSUE TITLE
Auto Completes on Batch Editing of files is not working

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#106]
When I select multiple files from my file listing
And I click Edit
Then I type in Language "ENG"
I should get a autocomplete "English...."

Like in the GF Edit page
![screen shot 2015-04-02 at 5 01 46 pm](https://cloud.githubusercontent.com/assets/1599081/6973624/fc31c994-d959-11e4-8804-f5a170660cf3.png)

Should also auto complete subject and location

**Comment by hectorcorrea** [comment]
I cannot replicate this in QA. I can replicate this in my local box when the MySQL "domain tables" (domain_terms, domain_terms_local_authorities, local_authorities, local_authority_entries, subject_local_authority_entries) are empty but the system works as soon as the data is on the tables.

It is possible that the tables were empty at one point in QA (?)

I tested Language, Subject, and Location in both single file edit and batch edit.

**Comment by carolyncole** [comment]
@hectorcorrea Yes this seems to have resolved itself.
