### ISSUE TITLE
Regularly check for missing otherwise messed up content

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1070]
Given our recent problem with missing content, and also this might help when an upload fails, but have a cron job or something like that that audits the content to check that it is there.

@awead  already wrote a script that does most if not all of this. Also, since it is based on the SHA hash, it would also detect corrupted files?

**Comment by awead** [comment]
@olendorf it could, but Fedora already has the capacity to do this. I believe we already run a job to check for corrupted files, but I'll verify that.

**Comment by olendorf** [comment]
@awead  I thought Fedora could too. Part of the question is we are considering the possibility, at some point taking fedora out of the stack. So it might be something useful when that happens too. That being said, its a "discussion" at this point, and don't know if and when it will happen.
