### ISSUE TITLE
Creator is no longer required

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1074]
When I click on New Work
And I remove myself as the creator
And I fill in the rest of the required metadata
Then I should not be able to click save
And the required metadata should still require a creator

**Comment by carolyncole** [comment]
@mtribone I apologize.  I was looking at this ticket without putting my name on it.  I put in a PR to fix part of the ticket: https://github.com/psu-stewardship/scholarsphere/pull/1077

The other part (which is what was describe here) is still up for grabs.  The java script for the save work only looks at inputs that exist in the form and are required, so if the user deletes all copies of the field the requirement gets removed.

I think the easiest way to fix this is to remove the current field, but if there are no items left add one, vs trying to rework the javascript to recognize that all copies the field have been removed.

**Comment by mtribone** [comment]
@cam156 No worries!
