### ISSUE TITLE
dmc186 profile not found

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#108]
On both staging and QA DMC186 profile is not found
![4 - profile is empty](https://cloud.githubusercontent.com/assets/1599081/6983817/37797cd6-d9f0-11e4-8d66-bd49088b8832.png)

dmc186 is listed in the users list, but when you click on the link you get the screen above

![screen shot 2015-04-03 at 10 57 15 am](https://cloud.githubusercontent.com/assets/1599081/6983819/3d18fb9e-d9f0-11e4-8682-717c1e2b9f90.png)

This may have to do with the migration only being partial

**Comment by carolyncole** [comment]
It appears to be realted to missing trophies.  The logs did not contain anything good, but when I loaded Dan's user in the console and run through the steps for show,  u.trophy_files throws the following error:

ActiveFedora::ObjectNotFoundError: Object n583z150g not found in solr
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/solr_instance_loader.rb:37:in `solr_doc'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/solr_instance_loader.rb:54:in`active_fedora_class'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/solr_instance_loader.rb:30:in `allocate_object'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/solr_instance_loader.rb:21:in`object'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/indexing.rb:79:in `load_instance_from_solr'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/sufia-models-6.0.0/app/models/concerns/sufia/user.rb:80:in`block in trophy_files'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in `map'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in`map'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/sufia-models-6.0.0/app/models/concerns/sufia/user.rb:79:in `trophy_files'
    from (irb):8
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/commands/console.rb:90:in`start'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/commands/console.rb:9:in `start'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:69:in`console'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/railties-4.1.9/lib/rails/commands.rb:17:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'irb(main):009:0>

**Comment by hectorcorrea** [comment]
This problem is caused by the `trophies` MySQL table pointing to a document ID that does not exist in Fedora/Solr. 

This was not caused by a partial migration, but rather it will happen every time we bring a copy of the Fedora data but we don't bring the MySQL data. 

I'll update the code to handle this more gracefully, but wanted to keep everybody in the loop. /cc @cam156 @awead

**Comment by carolyncole** [comment]
@hectorcorrea Great!

**Comment by hectorcorrea** [comment]
I've also submitted a PR to Sufia (see https://github.com/projecthydra/sufia/pull/1029) to address this issue at the root.
