### ISSUE TITLE
The admin/stats url is returning a ss error page

### ISSUE THREAD

**Issue by pketienne** [psu-libraries/scholarsphere-3#1091]
In testing steps 5 & 8 of the "Admin Pages" testing scripts, it was discovered that rather than the expected behavior listed, step 5 resulted in a redirect to a single sign-on login page. Step 8 resulted in a rails-based scholarsphere error page.

Discover the underlying cause and adjust so that the resulting behavior matches the expectations listed in the testing script.

**Comment by carolyncole** [comment]
Here is the information from the log
```
Rendering 500 page due to exception: #<NoMethodError: undefined method `name' for nil:NilClass> - ["/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/views/sufia/admin/stats/_deposits.html.erb:5:in `block in __opt_heracles_deploy_scholarsphere_shared_bundle_ruby_______gems_sufia_______app_views_sufia_admin_stats__deposits_html_erb___2382302787184157983_47323729039860'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/views/sufia/admin/stats/_deposits.html.erb:3:in `each'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/views/sufia/admin/stats/_deposits.html.erb:3:in `__opt_heracles_deploy_scholarsphere_shared_bundle_ruby_______gems_sufia_______app_views_sufia_admin_stats__deposits_html_erb___2382302787184157983_47323729039860'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'", "/opt/her
```

**Comment by carolyncole** [comment]
Noticed this was running on my local machine, so I guessed it was just the data on the server.

Seems we have some deposits that do not have associated user.
Got the page to load by running this code int he console.
```
depositors = Sufia::Statistics::Depositors::Summary.new(nil,nil).depositors
depositors.each{|dep| dep[:user].name rescue User.create!(login:dep[:key])}
```

The users seemed to exists on production so I am not 100% sure why the sync did not capture them.

**Comment by carolyncole** [comment]
Admin Stats page loads in Production.

**Comment by pketienne** [comment]
I'm reopening this issue as I've run into what I believe is a similar problem. I'm working specifically with the QA environment but I have successfully and completely synced the stage environment with qa so they should be identical at this point (but are not with respect to the `/admin/stats` page).

In the original issue, the error was `undefined method 'name' for nil:NilClass`, however the issue I'm getting now is `undefined method '[]' for nil:NilClass`.

```
Rendering 500 page due to exception: #<NoMethodError: undefined method `[]' for nil:NilClass> - ["/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.      1/app/services/sufia/statistics/term_query.rb:26:in `query'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/presenters/sufia/admin_stats_presenter.rb:31:in `top_formats'",       "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/views/sufia/admin/stats/_top_data.html.erb:9: [...]
```
I've synced the following persistent data sources:
* solr
* fedora
* redis
* mariadb - local - fedora
* mariadb - remote - rails
* uploads folder (derivatives)

I've also run the following code on the QA environment (after sync with stage):
```ruby
depositors = Sufia::Statistics::Depositors::Summary.new(nil,nil).depositors
depositors.each{|dep| dep[:user].name rescue User.create!(login:dep[:key])}
```

Both commands seem to have completed successfully with output related to users.

The problem stems from the `term_query.rb` file, line 26. It seems that either `json['terms']` or `json['terms'][term]` is an empty reference, but after looking through related files in the stacktrace, I've not been able to determine why this might be the case.

Any tips, hints, or suggestions are appreciated.

**Comment by pketienne** [comment]
I'm closing this issue as I've talked with the dev team about their issue reporting practices and understand that for their workflow, it is best to open a new issue. The new issue can be found at #1175
