### ISSUE TITLE
dashboard stat numbers white on yellow is hard to see

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#110]
When I go to my dashboard
And I have files statistics
I should be able to easily read them

![screen shot 2015-04-03 at 9 30 47 am](https://cloud.githubusercontent.com/assets/1599081/6983887/dbbf4fd2-d9f0-11e4-8f94-85a1d73752c7.png)

**Comment by mtribone** [comment]
You know that light gray could be darkened, too.

**Comment by carolyncole** [comment]
@mtribone good idea!

**Comment by mtribone** [comment]
![screen shot 2015-06-25 at 10 45 46 am](https://cloud.githubusercontent.com/assets/4163828/8357154/56b2c6d4-1b27-11e5-9b53-6b48162f8f94.png)
