### ISSUE TITLE
Following/Followers always says you

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#111]
When I am viewing another users profile
and I click on followers/following
and I have zero followers/following
Then It should not say "No One is following/follows YOU"
It should say No One is following/follows Joseph Peter

![screen shot 2015-04-03 at 11 06 00 am](https://cloud.githubusercontent.com/assets/1599081/6983941/73b3d088-d9f1-11e4-8248-e0ed05336e42.png)
"

**Comment by hectorcorrea** [comment]
This will be fixed in Sufia via this PR https://github.com/projecthydra/sufia/pull/1034

**Comment by carolyncole** [comment]
Has been fixed by the latest sufia
