### ISSUE TITLE
Clean Up Agent Migration

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1125]
I have created a report that contains all the new agents in the system.  At this point we need to figure out which agents are really the same person.  The code erred on the side of not matching, so there are some fairly obvious ones in the list.

@olendorf Does someone from the library have the time to run through the list?  @DanCoughlin Is there anyone in our group with the time to run through the list?

[agents.xlsx](https://github.com/psu-stewardship/scholarsphere/files/1526978/agents.xlsx)

They are sorted by given name as I assume that will be the easiest way to find the matches.

I believe for a first pass we should just try to match up the ones that should be combined, so I added a column on the end for the person to copy and paste the matching id.

After we get the spreadsheet updated my plan would be to create a script that takes two Agent ids and moves the aliases from one agent to the other. 
Afterward it deletes the old agent.
Create a new agent if a row exists without an id.
Copy any name changes into the agent

**Comment by olendorf** [comment]
@cam156 We can get an part time person at PAMS to work on it. The person would need pretty clear instructions, but is very meticulous and detail oriented.

**Comment by carolyncole** [comment]
@olendorf great!
Here is an example duplicate:
```
40ae793d-214c-4d67-9fd2-33d9494d8487 | Adams | Elizabeth E |   |  
e14e7402-a17d-4a05-82f3-58c7bf77854e | Adams | Elizabeth E. |   |  
```

What name would you prefer?  The line for the prefered name would get the id for the non prefered name and would look like

```
40ae793d-214c-4d67-9fd2-33d9494d8487 |   | Adams | Elizabeth E |   | e14e7402-a17d-4a05-82f3-58c7bf77854e
e14e7402-a17d-4a05-82f3-58c7bf77854e |   | Adams | Elizabeth E. |   |  
```

**Comment by olendorf** [comment]
@cam156 Good question about the preferred name. I would go for the one with no punctutaion in this case, but I can imagine there will be lots of judgement calls. I think if Jaycee (the guy here) can just get the name grouping handled, i can set up the preferred names? Not sure he is up to that sort of thinking.

**Comment by olendorf** [comment]
@cam looking overs this seems there are a lot of issues I am not sure of.

1. Should we clean up names? 
   Example surname: Abigail Ruby, given name: BSN should be 
                  surname: Ruby, BSN, given name: Abigail

   - is this a good way to handle honorifics?

2. We should only link names with emails I assume, even if they are most likely the same name.

3. Where people put two people in 
    Example surname: Amy Knehans, Given name: Alex Evans
     Should be two people, surname: Knehans, given name Amy 
                                            surname: Evans, given name Alex

4. Should we take the time to look up indentical names ?

- This seems more nuanced than initially thought. Right now i put two new columns in the table 
       corrected_surname, corrected_given_name

**Comment by cam** [comment]
@olendorf I think you may have the wrong Cam 😁

**Comment by olendorf** [comment]
Agent cleaning more or less done.
[agents_cleaned.xlsx](https://github.com/psu-stewardship/scholarsphere/files/2529617/agents_cleaned.xlsx)

**Comment by awead** [comment]
Notes:
1. Run through the split column first (id_split_from_agent)
2. Join the duplicates from id_of_equal_agent
3. Fix the names
  * we won't fix degree types in surname fields

**Comment by carolyncole** [comment]
Updated copy with cleaned id_of_equal_agent so there are no loops.

[agents_cleaned.xlsx](https://github.com/psu-stewardship/scholarsphere/files/2562010/agents_cleaned.xlsx)
