### ISSUE TITLE
Move ScholarSphere to use Valkyrie

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1129]
The data mapper pattern we are utilizing in CHO should help to ease the migration issues we keep facing in ScholarSphere.

Can we migrate the system an object at a time? Collection, then Work, then FileSet?

We discussed this and the theory is that we could create an valkyrie adapter using the current Active Fedora Model so that the back end data would remain constant as we migrate the code.

After the code is migrated we could use the data mapper patterns to migrate from one persister to another.

**Comment by carolyncole** [comment]
It is possible we could get this with upgrading to Hyrax.  This would depend on Hyrax being completely migrated to Valkyrie first.

**Comment by mtribone** [comment]
TBD. We may not be using Valkyrie?
