### ISSUE TITLE
When Editing a Collection, Title in the Header Only Displays First Letter

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1132]
When I edit an existing collection, the header above the form only displays the first letter of the collection name.

![screen shot 2018-01-04 at 12 41 00 pm](https://user-images.githubusercontent.com/4163828/34576772-0b5d0b6e-f14d-11e7-9af0-50f7a6451176.png)

**Comment by carolyncole** [comment]
Duplicate of #1157
