### ISSUE TITLE
DOI metadata not being sent correctly

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1160]
The records sent via the api are being populated with triples rather than strings

The record https://scholarsphere-stage.libraries.psu.edu/concern/generic_works/6dj52w482w

Should have title: foo
and creator Robert K Olendorf

IN ezid it looks like this.

Location (URL): https://scholarsphere-stage.libraries.psu.edu/concern/generic_works/6dj52w482w
Creator:#<ActiveTriples::Relation:0x007fd87b7b7770>
Title:#<ActiveTriples::Relation:0x007fd87b986e98>
Publisher:ScholarSphere
Publication year:2018
Resource type:[No value]

**Comment by awead** [comment]
@olendorf titles and creators can be multiple, so we need to format them. How should we group together multiple titles? Creators should probably be via display name, and comma-separated.

**Comment by awead** [comment]
Duh. sorry... titles are single, or rather, arrays with only one value.
