### ISSUE TITLE
Scholarsphere and DOIs content types don't map well

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1167]
Until this is fixed I can fix them manually. Still labeled it as high.

ScholarSphere      ->    DOI
---
Article  -> Text
Audio -> Sound
Book ->
Capstone Project -> Text
Conference Proceeding -> Text
Dataset -> Dataset
Image -> Image
Journal -> Text
Map or Cartographic Material -> Image
Part of  Book -> Text
Poster -> Audiovisual
Presentation -> Audiovisual
Project -> Other
Report -> Text
Research Paper -> Text
Software or Program Code -> Software
Video -> Audiovisual
Other -> Other

**Comment by awead** [comment]
@olendorf Scholarsphere's resource types can be multiple. I don't see if they can be in EzId, such as separating them with commas. If they have to singular, we can just choose the first.

**Comment by olendorf** [comment]
@awead no just singular, so yeah go with the first

**Comment by awead** [comment]
@olendorf I've got a fix in for it. We could do a hotfix release early next week, if you want.

**Comment by olendorf** [comment]
Sounds good
