### ISSUE TITLE
When I create a collection and I upload new works it can error

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1172]
When I go to the collection show page
And I click on the Add new Works
Then I upload a couple files
It redirects me to some page and does not create the works

**Comment by awead** [comment]
It also creates the works, but does not add them to the collection.

**Comment by carolyncole** [comment]
This commit fixes the issue: d6cf8f569947bab8d9696d88d43d45a885a58891

**Comment by mtribone** [comment]
Adding new works to a collection from the collection show page creates the works but does not add them to the collection.
