### ISSUE TITLE
The admin/stats url on the qa environment is returning a ss error page

### ISSUE THREAD

**Issue by pketienne** [psu-libraries/scholarsphere-3#1175]
I'm working specifically with the QA environment but I have successfully and completely synced the stage environment with qa so they should be identical at this point (but are not with respect to the `/admin/stats` page).

In the original issue, the error was `undefined method 'name' for nil:NilClass` (#1091), however the issue I'm getting now is `undefined method '[]' for nil:NilClass`.

```
Rendering 500 page due to exception: #<NoMethodError: undefined method `[]' for nil:NilClass> - ["/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.      1/app/services/sufia/statistics/term_query.rb:26:in `query'", "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/presenters/sufia/admin_stats_presenter.rb:31:in `top_formats'",       "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/views/sufia/admin/stats/_top_data.html.erb:9: [...]
```
I've synced the following persistent data sources:
* solr
* fedora
* redis
* mariadb - local - fedora
* mariadb - remote - rails
* uploads folder (derivatives)

I've also run the following code on the QA environment (after sync with stage):
```ruby
depositors = Sufia::Statistics::Depositors::Summary.new(nil,nil).depositors
depositors.each{|dep| dep[:user].name rescue User.create!(login:dep[:key])}
```

Both commands seem to have completed successfully with output related to users.

The problem stems from the `term_query.rb` file, line 26. It seems that either `json['terms']` or `json['terms'][term]` is an empty reference, but after looking through related files in the stacktrace, I've not been able to determine why this might be the case.

Any tips, hints, or suggestions are appreciated.

**Comment by awead** [comment]
Terms query needs to be enable in solrconfig. See #1346.

The no method error was being raised because the json response from the term query was returning `{}` and calling `[term]` caused the error. Oddly, RSolr doesn't error when we call a term query that's not configured, but the error does appear in Travis:
```
<p>
    Showing <i>/home/travis/build/psu-stewardship/scholarsphere/vendor/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/views/sufia/admin/stats/_top_data.html.erb</i> where line <b>#9</b> raised:
  </p>
  <pre><code>RSolr::Error::Http - 404 Not Found
Error:     Not Found
URI: http://127.0.0.1:8985/solr/hydra-test/terms?terms.fl=file_format_sim&amp;terms.sort=count&amp;terms.limit=5&amp;wt=[secure]&amp;[secure].nl=map&amp;omitHeader=true
```

**Comment by carolyncole** [comment]
Need to add the link back in so we can access the page via a link instead of just entering the URL.  Revert this change: https://github.com/psu-stewardship/scholarsphere/pull/1272
