### ISSUE TITLE
Reformat DOI display

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1176]
While correct, we currently display the DOI as `doi:10.18113/S1V91R`. However this has turned out to be confusing to users because it doesn't function as a proper link. Perhaps provide the direct link format

`https://doi.org/10.18113/S1V91R`

or provide both the pure DOI and the https version.

**Comment by carolyncole** [comment]
I believe the Work presenter could be modified to exchange 'doi:' for 'https://doi.org'
