### ISSUE TITLE
Repeated edit users when uploading on behalf of

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#1179]
When uploading on behalf of another user, the other user appears three times as an edit user.

For example, if I upload a new work and choose `mat141` as the user to upload on behalf of, ownership is transferred to him, but when looking at the work:

``` ruby
>  gw = GenericWork.find([id])
>  gw.edit_users
=> ["mat141", "mat141", "mat141", "agw13"]
```
You can also see this when flipping down the caret on the "Shared With Me" listing:
<img width="417" alt="behalf" src="https://user-images.githubusercontent.com/312085/36501896-68e03cf4-1716-11e8-8a1f-92c98567cc58.png">

**Comment by carolyncole** [comment]
This is no longer occuring
