### ISSUE TITLE
Unable to Find Works When Searching for Extracted Text from PDF

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1180]
When I create a new work and upload a PDF, text contained within the PDF does not return the work when searching My Works or All of ScholarSphere.

**Comment by carolyncole** [comment]
From what I can tell the solr document no longer contains the all_text field.

**Comment by nrm149** [comment]
- we do not believe its related to solr 7 upgrade as it was happening before
-  This is done via solr join and did work in sophia 7 and hyrax
- needs to be a test that finds this issue

**Comment by awead** [comment]
This doesn't seem to work when searching My Works, but does work when searching all of Scholarsphere.
