### ISSUE TITLE
Batch edit hangs when saving multiple changes

### ISSUE THREAD

**Issue by pketienne** [psu-libraries/scholarsphere-3#1181]
It may not be good practice (or perhaps it should work fine?) to save multiple changes at the same time from within batch editing a set of works. Either way, the interface allows a user to edit thirteen different metadata fields at the same time. Adding new values or removing values one at a time works fine, however when attempting to update all at the same time, some few complete successfully and the rest seem to hang.

**Comment by carolyncole** [comment]
@informaticianme this is a duplicate of #1178
