### ISSUE TITLE
Download Collection with works I do not have access to

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1222]
When I click on a collection That contains works I do not have access to
And I click on download collection
Then I get a invalid zip file
I should either not see the button or recieve a flash stating the zip would be empty

**Comment by carolyncole** [comment]
Screen shot of collection I do not have access to the works:

![screen shot 2018-04-05 at 11 19 34 am](https://user-images.githubusercontent.com/1599081/38375172-8fbf1e7a-38c3-11e8-959f-edfa1f2e8688.png)

Resultant zip file
[cimbala_papers.zip](https://github.com/psu-
stewardship/scholarsphere/files/1880638/cimbala_papers.zip)

**Comment by awead** [comment]
Don't show the download button if you don't have access to any works in the collection.
