### ISSUE TITLE
Creator Value on the Work Show Page doesn't Search for Canonical Name

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1223]
When I click the linked value of the creator metadata field, the search doesn't search for the canonical name as it does from the facet. The linked metadata field for creator needs to search for the canonical name.

Display Name  

![screen shot 2018-04-05 at 12 36 30 pm](https://user-images.githubusercontent.com/4163828/38379304-4b0c6e44-38ce-11e8-97d1-646d67a7080a.png)

Search

![screen shot 2018-04-05 at 12 39 02 pm](https://user-images.githubusercontent.com/4163828/38379340-6e183be8-38ce-11e8-8b42-f2bcece1d006.png)

Search All of SS from Works using "Sir Snacks-a-Lot" Returns Michael Anthony Tribone in the Creator Facet. Selecting my name from the facet returns all of Sir Snacks-a-Lot's works.

![screen shot 2018-04-05 at 12 40 55 pm](https://user-images.githubusercontent.com/4163828/38379449-ba816144-38ce-11e8-895d-a15993d38f36.png)

**Comment by carolyncole** [comment]
I believe this is becuase the Canonical name is indexed into solr as the facet instead of the display name.  We need to change the link to show the display name, but search on the canonical name.

**Comment by nrm149** [comment]
This also needs to be done for the collection show page

**Comment by carolyncole** [comment]
This works for a work, but not a collection.
