### ISSUE TITLE
Contrast Issues on the Dashboard and User Profile

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1232]
We have some grey text color over white background and the badges with white text that displays followers and following that are contrast issues. Also the badge elements on the dashboard are the same, but are showing views and downloads. And any place with placeholder text.

Dashboard
![screen shot 2018-04-06 at 11 25 02 am](https://user-images.githubusercontent.com/4163828/38429720-363883f8-398d-11e8-9c99-8f43373db212.png)

User Profile
![screen shot 2018-04-06 at 11 26 04 am](https://user-images.githubusercontent.com/4163828/38429751-53f35490-398d-11e8-8862-d5378dba33bb.png)

**Comment by awead** [comment]
User profile issues are addressed in #1228. This ticket should address the dashboard.
