### ISSUE TITLE
Incorrectly converted strings

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#1235]
In a description or title field, a "smart" quote which might result from a copy/paste taken from a pdf or other document, will produce an error when rendered on the work's show page:

`Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT`

In the terminal, the field might look like `"Mike?s dog"`.

**Comment by nrm149** [comment]
done is when form data is converted to utf 8 when ingested on collections and works

**Comment by nrm149** [comment]
going to ignore bad characters on conversion

**Comment by nrm149** [comment]
Will need dark grey or black for CSS color in the user profile

**Comment by awead** [comment]
Related to #1236

**Comment by awead** [comment]
Metadata will be converted to correct encoding errors when the record is created or updated so that the correct content is stored in Fedora. This process should be applied to all fields.
