### ISSUE TITLE
Readme processing needs to handle UTF8 encoding

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1236]
Non UTF-8 readmes are causing the page to not render.  I have added some code to encode the readme to UTF-8, but for an error it just displays the error.  We may want to try and do something better liek remove the bad characters, or something.

In addition readme processing is occurring each time the page is loaded.  This seems like something we should index with the work, or the fileset

**Comment by carolyncole** [comment]
@olendorf Would you like us to ignore bad characters, or try to convert them?

**Comment by olendorf** [comment]
@cam156 I would prefer to convert them, but what ever works is fine.

**Comment by awead** [comment]
Depends on #1235, but the same process for correcting encoding in that ticket could be applied here. Content would be corrected on display only, and not saved back to the file.
