### ISSUE TITLE
Move from DOI to DataCite

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1237]
Switch the API from EZID to Datacite. Should be done by the end of 2018. Replace the EZID gem with the DataCite gem and make any necessary changes.

**Comment by awead** [comment]
We will need to verify which gem we'll need to user. @olendorf will do this, then we can point the ticket.

**Comment by carolyncole** [comment]
@olendorf do you have any idea which gem we would switch.

**Comment by carolyncole** [comment]
https://support.datacite.org/docs/datacite-ez-api-guide Is this the location?

**Comment by carolyncole** [comment]
Add processes for migrating the old IDs from the EZID system.

**Comment by carolyncole** [comment]
We are waiting on purchasing for the real license key.  It can take about a month to get the real key, so this may need to be updated after the sprint is complete.

@olendorf  will ask for early sandbox access for testing.

**Comment by awead** [comment]
Based on this link: https://support.datacite.org/docs/datacite-ez-api-guide#section-how-to-use
We can continue to use the same ezid-client gem we've been using. Is this right @olendorf ?

**Comment by awead** [comment]
@olendorf word on the street is that we can, and should: https://github.com/duke-libraries/ezid-client/issues/83

**Comment by carolyncole** [comment]
We need a switch to be able to use ezid, or turn it off completely, or use the new datacite.

**Comment by carolyncole** [comment]
@olendorf  Were you able to get the mapping from our resource Types to the new DataCite types?  We know that Image does work and book does not work, but are not certain of the other types.

**Comment by carolyncole** [comment]
Here are a list of the ResourceTypes from DataCite: https://schema.datacite.org/meta/kernel-4.1/doc/DataCite-MetadataKernel_v4.1.pdf

Audiovisual, Collection, DataPaper, Dataset, Event, Image, InteractiveResource, Model, PhysicalObject, Service, Software, Sound, Text, Workflow, Other

Here is the mapping that will need to be updated: https://github.com/psu-stewardship/scholarsphere/blob/develop/app/services/doi_service.rb#L6

**Comment by cam156** [comment]
Looking at travis builds Master was 18 minutes for the features and 43 minutes for the unit tests, After the "upgrade" to ChromeDriver we were at 34 minutes for the features and 47 minutes for the unit tests. Develop is now 18 minutes for the features and 36 minutes for the unit tests.

Overall the upgrade to ChromeDriver slowed things down, but we were able to speed back up to just a bit faster by removing tests in the unit tests and combining and refactoring feature tests.

**Comment by olendorf** [comment]
@cam156 Looks like only the book needs to change. I just set it to text. I put the datacite value in parenthesis below.  

EZID_RESOURCE_TYPES = {
    'Article' => 'Text',  (Text)
    'Audio' => 'Sound', (Sound)
    'Book' => 'Book',  (Text)
    'Capstone Project' => 'Text', (Text)
    'Conference Proceeding' => 'Text', (Text)
    'Dataset' => 'Dataset', (Dataset)
    'Image' => 'Image', (Image)
    'Journal' => 'Text', (Image)
    'Map or Cartographic Material' => 'Image', (Image)
    'Part of Book' => 'Text', (Text)
    'Poster' => 'Audiovisual',  (Audiovisual)
    'Presentation' => 'Audiovisual', (Audiovisual)
    'Project' => 'Other', (Other)
    'Report' => 'Text', (text)
    'Research Paper' => 'Text', (Text)
    'Software or Program Code' => 'Software', (Software)
    'Video' => 'Audiovisual', (Audiovisual)
    'Other' => 'Other' (other)
  }.freeze
