### ISSUE TITLE
Downloads controller is now taking 15 seconds vs 1 second

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1240]
Looking at new relic previous to the April 10th deploy the downloads controller was taking an average of 1 second to respond.

After April 10 the downloads controller is now taking an average of  15 seconds.

This could be becuase more people are downloading the entire work.  It also could be that the work added an inefficiencies in the download controller in general.

**Comment by carolyncole** [comment]
https://github.com/psu-stewardship/scholarsphere/commit/be78154a24d4951e78ba6d681b61602c0be6d685#diff-5b1717b5c25ba511288b5bb06c831667
https://github.com/psu-stewardship/scholarsphere/commit/dd411aa30d54648b27aec334ce980a35eb516ec0#diff-5b1717b5c25ba511288b5bb06c831667
https://github.com/psu-stewardship/scholarsphere/commit/b79d17ce92910bccdc5cfc66001ec783a940114a#diff-5b1717b5c25ba511288b5bb06c831667

Revert these commits, push to stage, and see what new relic has to say.

**Comment by carolyncole** [comment]
See the difference in the graph from before April 8th to after April 8th

![screen shot 2018-06-13 at 8 53 43 am](https://user-images.githubusercontent.com/1599081/41353074-2464ef4a-6ee9-11e8-95b4-de5537dbb46f.png)

**Comment by awead** [comment]
Total number of downloads seems fairly consistent over the last two years:
![total_downloads.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55098a50f74dcc53007cd9d5/125516c66e82c728ace21e0d46fc9b8e228ebcad80feb14fab5cf4876b0a65633b0ba92e7391a172fd172f040b094ff9450a5947fcfd812aafb63c768d5a0bbbd67f4366846c4ff8e7df46f554f832815d84bfb68b49c2e03427e683864c3918040ac4.png)

**Comment by awead** [comment]
Using New Relic's Insights query interface tells us 4.81K zip downloads _alone_ in the last 7 days, each averaging 67 seconds. Although, there are notable outliers such as this collection https://scholarsphere-stage.libraries.psu.edu/collections/jw827b80n which took 143 minutes to download its 52 GB content.

About half (2.33K) of those 4.8K requests were from referrers with "bot" in the name. So, it's likely all the zip download traffic is from bots. I doubt there are 2,000+ users out there downloading zip files in the last week. But I could be wrong.

**Comment by awead** [comment]
When looking at downloads versus collection size, its seems linear: the more files, the longer the process. Using my local machine, on master, I created collections each with 1, 2, 3, 4, and 5 100 MB files and downloaded their zips:

```
1 item:
real	0m9.430s
user	0m0.044s
sys	0m0.251s

2 items:
real	0m18.959s
user	0m0.095s
sys	0m0.546s

3 items:
real	0m28.416s
user	0m0.146s
sys	0m0.816s

4 items:
real	0m39.149s
user	0m0.194s
sys	0m1.114s

5 items:
real	0m49.841s
user	0m0.242s
sys	0m1.385s
```

It's possible the reason we're seeing the uptick in time spent downloading is because the bots are hitting it, and we have some big collections.

**Comment by awead** [comment]
Possible solutions:
* cache zips based on timestamps or checksums
* don't delete zips
* don't zip single-file works
* block bots from downloading zips, while allowing binaries
