### ISSUE TITLE
Allow users to choose video quality

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1241]
We have had a user request to allow for choice on video playback quality.  Right now the small webm is being shown always, but sometimes people want to see the high resolution video.

We could create a download link for high res, or use something like: https://github.com/silvermine/videojs-quality-selector to allow the user to pick.

**Comment by awead** [comment]
Implementation should include the option to select quality for playback and choose which file to download.

**Comment by awead** [comment]
I don't think we're using VideoJS anymore:

https://github.com/samvera-deprecated/sufia/commit/f876be1b2ec542a566be290e51c1da29573cc217

So we need to add it back and see if it still works.
