### ISSUE TITLE
Derivatives may be taking up significant extra disk space

### ISSUE THREAD

**Issue by pketienne** [psu-libraries/scholarsphere-3#1244]
The `/scholarsphere/upload_{env}/derivatives` directory is taking up 1.3TB on production. Is this disk usage valid and used derivatives? Might there be extraneous data that needs to be cleaned out? What would it take to perform an "audit" of the derivatives folder to ensure that we have only the necessary files on disk?

Disk usage stats on the various environments' "uploads" directories are as follows:

`/scholarsphere/upload_prod_new/browse_everything_file_system`: 141GB 
`/scholarsphere/upload_prod_new/derivatives`: 1.3TB 
`/scholarsphere/upload_prod_new/tmp`: 129GB 
`/scholarsphere/upload_prod_new/uploads`: 28GB 

`/scholarsphere/upload_stage_new/browse_everything_file_system`: 141GB 
`/scholarsphere/upload_stage_new/derivatives`: 2.3GB 
`/scholarsphere/upload_stage_new/tmp`: 129GB 
`/scholarsphere/upload_stage_new/uploads`: 25GB 

`/scholarsphere/upload_qa_new/browse_everything_file_system`: 141GB 
`/scholarsphere/upload_qa_new/derivatives`: 2.4GB 
`/scholarsphere/upload_qa_new/tmp`: 128GB 
`/scholarsphere/upload_qa_new/uploads`: 56GB

**Comment by carolyncole** [comment]
List of fIle paths that are needed for the operation objects in the system.
Mater list should include thumbnails, and other access derivates that are utilized for each object.  

ANYTHING that is NOT in the list will be removed from the system.

Take what are the additional files and why are being created.  Is this from migrations or from some other issue.  Are files that are being deleted not being removed.  Look for matching fedora tombstone.

**Comment by carolyncole** [comment]
@informaticianme So it seems that most of the extra files are from the download zip:
```
 > find . -type f -name '*.zip' -exec du -cb {} + | grep total$ | cut -f1 | paste -sd+ - | bc
617120136858
```

Looks like 617GB of the files are from that.  Those files are not being utilized after they are downloaded so they could be periodically deleted.

**Comment by carolyncole** [comment]
There only seem to be an additional  435 files in the directory over and above the thumbnails and the zips.
```
-bash-4.2$ find . -type f -name '*-thumbnail*' | wc -l
5364
-bash-4.2$ find . -type f -name '*zip*' | wc -l
6758
-bash-4.2$ find . -type f -name '*' | wc -l
12557
```

**Comment by carolyncole** [comment]
@informaticianme the other files are related to .csv, .txt, and other text types of files.  I think creating a cron job to periodically remove the .zip files would be the best solution to the disk size issue.

**Comment by carolyncole** [comment]
We have decided we may want to keep these zip files around as a caching mechanism
