### ISSUE TITLE
Admin stats is broken

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere-3#1246]
the admin stats page is broken, when logged in and clicking on the link for the statistics I get an error page
https://scholarsphere.psu.edu/admin/stats

![screen shot 2018-05-18 at 9 25 04 am](https://user-images.githubusercontent.com/398837/40237125-7cddd7de-5a7d-11e8-870d-97de085d9141.png)

**Comment by carolyncole** [comment]
@DanCoughlin I believe this is a duplicate of #1175

**Comment by carolyncole** [comment]
Remove the broken link.  #1175 would be to fix the code.

**Comment by awead** [comment]
Link to "System Statistics" in the user dashboard also needs to be removed.
