### ISSUE TITLE
implement the option that has been selected

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1249]
Pilot A fedora instance on Demo Server to document the process

Creating new objects that store data outside of fedora
Create Derivatives
Create Versions

child of #1128

**Comment by cam156** [comment]
[  ] Verison of the code that creates external versions
    - Includes a Monkey Patch  
[  ]  Get the build passing
[  ] Reach out to the community for the update to Active Fedora
[  ] Changes behind a configuration flag

**Comment by carolyncole** [comment]
- [x] Verison of the code that creates external binaries
    - Includes a Monkey Patch  
- [x] Get the build passing
- [x] Put the changes behind a configuration flag
- [x] PR to the develop branch
- [ ] Reach out to the community for the update to Active Fedora
