### ISSUE TITLE
Reach out to the community for the update to Active Fedora

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1283]
We have created a way to store content in external files.  Is there a way to change active fedora to make this easier for people to implement into the future

**Comment by carolyncole** [comment]
Use the google doc that @bess is creating as a platform for community feedback

**Comment by bess** [comment]
I wrote to the Samvera community about what we did and there was some response: https://groups.google.com/forum/#!searchin/samvera-tech/external$20data$20bess/samvera-tech/mJKDWw0ZTNc/93YnOkWuBgAJ

**Comment by carolyncole** [comment]
Add the documentation to samvera.github.io to finish up the community update

**Comment by bess** [comment]
PR for samvera.github.io here: https://github.com/samvera/samvera.github.io/pull/339
