### ISSUE TITLE
Create manual benchmark on QA of Upload and Edit after binaries are stored externally

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1285]
Additionally create benchmarks of DCEFedora
child of #1128

**Comment by carolyncole** [comment]
http://sites.psu.edu/dltdocs/?p=4258

**Comment by awead** [comment]
Benchmarks are reported here https://github.com/psu-stewardship/scholarsphere/wiki/Benchmarks#reporting
