### ISSUE TITLE
Reverse File Membership - File point at work vs Work pointing at the File

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1309]
Child of #996

Adding a new relationship on the FileSet to point at the work.  Add a new predicate to the file set (member_of).  Look at the reversion of collection membership.

Added the new relation ship and it saves to Fedora and Solr and we can utilize that relationship to see what FileSets belong in a work.

**Comment by mtribone** [comment]
Focus of the project has changed and we are moving to a new ScholarSphere that may not be dependent on the current technology stack.
