### ISSUE TITLE
Change the work display to show search result Files in Work (like collection show)

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1311]
child of #996

Use the code the collection for showing works in a collection to show FileSets in the File.

Should update the Work show presenter to get the files out of the new predicate.

Does include sorting by title alphabetically by default.  Does not include visual ability to sort by title.

**Comment by mtribone** [comment]
Focus of the project has changed and we are moving to a new ScholarSphere that may not be dependent on the current technology stack.
