### ISSUE TITLE
Test works with large numbers of files

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1317]
child of #996

Test the code with large numbers of files in a work

Should we rework the Cannon Image data?

**Comment by carolyncole** [comment]
This should include benchmarking the new code.  We may be able to reuse @awead's large data script.

**Comment by mtribone** [comment]
Focus of the project has changed and we are moving to a new ScholarSphere that may not be dependent on the current technology stack.
