### ISSUE TITLE
After Sending Contact Message Form Does not Clear Data

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#132]
I fill out the contact form and hit send. I get the flash message that indicates success, but all fields are still filled with contact. I'm guessing that this is "normal" behavior, but not ideal experience?

![screen shot 2015-04-11 at 3 06 53 pm](https://cloud.githubusercontent.com/assets/4163828/7102824/c40627e0-e05c-11e4-8b82-303dbc8d67a4.png)

**Comment by awead** [comment]
I think this got fixed in sufia somewhere, so updating it might just fix it.

**Comment by awead** [comment]
This is fixed now.
