### ISSUE TITLE
Investigate the scope of Multiple benchmark test for cloud providers will fail

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#1327]
When running the benchmarking tests for cloud providers, the test will fail after a second or third successful run.

How long do you need to wait before running them again.  
Are there other upload tests we can use?
Why the issue is happening?

blocked by #1326

**Comment by carolyncole** [comment]
cloud providers could throttle you

**Comment by awead** [comment]
This appears to be working now by setting up L-SCHOLARSPHERE-SUPPORT@LISTS.PSU.EDU as the Box user.
