### ISSUE TITLE
Benchmark DCEFedora before the binaries are moved

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1329]
Run a benchmark of the DCE fedora box before the binaries get migrated so we can benchmark after.

Document the results on site. Possibly run it from multiple locations to see if there is a difference

blocked by #1326

**Comment by carolyncole** [comment]
Currently we are going to run these on someone's laptop, but we are hoping to get a VM for benchmarking in the future

**Comment by cam156** [comment]
Document the results on site.  Possibly run it from multiple locations to see if there is a difference

**Comment by awead** [comment]
Solr query
`bundle exec rspec spec/solr_query.rb  240.02s user 61.32s system 58% cpu 8:37.12 total`
Upload without Resque
`bundle exec rspec spec/upload_from_my_computer.rb  26.36s user 9.79s system 65% cpu 55.393 total`
Upload with Resque
`bundle exec rspec spec/upload_from_my_computer_with_resque.rb  151.09s user 54.05s system 39% cpu 8:38.76 total`

**Comment by awead** [comment]
The cloud providers test is not running cleanly, see #1327, also it is not tracked in the reporting page in the DLT docs: http://sites.psu.edu/dltdocs/?p=4265
