### ISSUE TITLE
Helper Info for Identifier in Batch Edit Cuts Off

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#134]
When I am batch editing files and select the helper icon for identifier, the help text gets cut off at the top.

![screen shot 2015-04-11 at 3 49 14 pm](https://cloud.githubusercontent.com/assets/4163828/7102992/741034fa-e062-11e4-9203-dc8420cb380b.png)

**Comment by mtribone** [comment]
Also for location

![screen shot 2015-04-11 at 3 51 49 pm](https://cloud.githubusercontent.com/assets/4163828/7102997/b7ffcb9e-e062-11e4-8190-06f7642cc598.png)

**Comment by mtribone** [comment]
Yeah pretty much all of them

![screen shot 2015-04-11 at 3 53 49 pm](https://cloud.githubusercontent.com/assets/4163828/7103004/fa71d986-e062-11e4-835f-5f61a0e776e2.png)

**Comment by mjgiarlo** [comment]
Good to see these documented! I'm thinking the bugs related to batch editing might be low priority since this whole feature may be going away when we switch to PCDM.

**Comment by mtribone** [comment]
Is this something that I can work on while PCDM is still in progress? Just wondering about the timeframe to implementation for PCDM and a current UI problem.

**Comment by carolyncole** [comment]
Yes I think it would be great to fix this up, since it may be a bit for PCDM
