### ISSUE TITLE
Enable TermsComponent in solrconfig.xml

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#1346]
Statistic queries using terms like format, depositor, and resource type are failing because we don't have a terms component query handler enabled:

https://github.com/samvera/sufia/blob/master/solr/config/solrconfig.xml#L190-L199

This is causing the admin stats page to error. A fix has been implemented to get the page to render, but the solr config should be updated to enable the queries to work.

**Comment by carolyncole** [comment]
Needs to be put on the servers.  Is in the local configuration

**Comment by awead** [comment]
This was present in our `solrconfig.xml` as far back as 2016 in cd5dbbe008863a645a46c875f1af043bc55565a0

But then seems to have been removed in 95e2f9e94fa1bde39554e3819e01e9ff09cfbf16

The config was restored as part of 660a95ba46c3318a373d75322c3e7d4c02674727 for #1175.

**Comment by awead** [comment]
Merged into Chef https://github.com/psu-stewardship/chef/pull/265
