### ISSUE TITLE
solr rake compare does not work with fedora 4

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#137]
NoMethodError: undefined method `connection_for_pid' for ActiveFedora::Base:Class
/opt/heracles/deploy/scholarsphere/releases/20150411014520/lib/tasks/scholarsphere-solr.rake:46:in`initialize_rubydora_connection'
/opt/heracles/deploy/scholarsphere/releases/20150411014520/lib/tasks/scholarsphere-solr.rake:33:in `block (3 levels) in <top (required)>'

**Comment by awead** [comment]
Do we still need to check solr like this?
