### ISSUE TITLE
Marketing Text on Home Page

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1395]
When I try to edit the marketing text on the home page as an admin, I do not get the tinymce editor. I get a large teal block and an input for an external key.

**Comment by mtribone** [comment]
![screen shot 2018-09-05 at 4 05 42 pm](https://user-images.githubusercontent.com/4163828/45118689-2a84fe80-b127-11e8-9419-349482a675a2.png)

**Comment by carolyncole** [comment]
Tested on QA.  This is now working.
