### ISSUE TITLE
Blank Resource Type with Facet Count

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1396]
When I use the links for types of content on the About page, I receive a blank resource type with an actual facet count. I also get one when I do a manual search for "all" from the home page.

**Comment by mtribone** [comment]
![screen shot 2018-09-05 at 4 51 17 pm](https://user-images.githubusercontent.com/4163828/45120453-23142400-b12c-11e8-86be-87ce40875ec3.png)

**Comment by mtribone** [comment]
![screen shot 2018-09-05 at 4 50 57 pm](https://user-images.githubusercontent.com/4163828/45120462-2c04f580-b12c-11e8-92e0-df424bd8f096.png)

**Comment by carolyncole** [comment]
There are blank resource types in production as well.  This seems to be a data issue from a migration possibly?

**Comment by carolyncole** [comment]
From what I can tell resource type was not required as late as Sufia 6 based on this commit from Hector in Sufia: https://github.com/samvera/sufia/commit/ee2e6b0820e9e4043da05a68d695518d80049b06

A report that I ran on May 19, 2017 shows some files with Resource Types and some files without resource Types. https://psu.box.com/s/7xl0pp7xwyotrkm2ldhi1jbrp8trmgeg

I believe the final solution to make this work would either be have the facet translated to show a link that would show any resources with a blank facet value:

for example: https://scholarsphere.psu.edu/solr/collection1/select?fq=has_model_ssim:GenericWork&q=-resource_type_tesim:*&sort=date_uploaded_dtsi%20desc

**Comment by carolyncole** [comment]
I18n `unspecified` for the default value in the resource type.  We may insert it in the document, but it might be nicer to facet on the missing field instead of updating .

The above query is not quite right, since the number of documents does not match the facet in the application.

**Comment by awead** [comment]
This may be relevant https://github.com/projectblacklight/blacklight/issues/1130
