### ISSUE TITLE
Searching for Extracted Text for a File on DCE Box

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1401]
When searching for text within a text on the DCE box, I am unable to find the search "A la carte tornado" from one of my files. However, I see my work in the search results on QA.

File on DCE
https://dce-fedora.vmhost.psu.edu/concern/parent/5712ms21n/file_sets/wst74cr47g

Search results on DCE
https://dce-fedora.vmhost.psu.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=A+la+carte+tornado

Search results on QA
https://scholarsphere-qa.libraries.psu.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=A+la+carte+tornado

**Comment by awead** [comment]
I think the issue is that extracted text in the file set is now `StringIO`.  Looking at a record in production, the class is`String`.  Here's what I'm seeing with the above file set:
```
> fs = FileSet.find("wst74cr47g")
=> #<FileSet id: "wst74cr47g", label: "wst74cr47g_version1_Demystifying_Web-based_Design-...", [...]
> fs.extracted_text.content
=> #<StringIO:0x005644b1e41118>
> fs.extracted_text.content.read
=> "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDesign from my POV (brain)\nDoesn\xE2\x80\x99t Require a Muse\n\nInformation is the seed from which design grows\nInspiration happens\n\nDesign isn\xE2\x80\x99t Surface\nMore than a thin 
[...]
> fs.to_solr["all_text_timv"]
=> "Error encoding readme as UTF-8: undefined method `encode' for #<StringIO:0x005644b4fbcfd0>"
```

A record in production looks like:
```
> fs = FileSet.find("m6395w8729")
=> #<FileSet id: "m6395w8729", label: "2005_RSQ_Review_of_the_Rhetoric_of_Rhetoric.pdf", ...
> fs.extracted_text.content.class
=> String
```
Note that in the production example, calling `content` on the string object returns the actual content, whereas in dce, it's returning the object.
