### ISSUE TITLE
Does group access still work?

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#1433]
Was just working through this with a user, and it looks to me like it was driven off of UMG our old emails system? Does it still work with outlook ?

**Comment by carolyncole** [comment]
Create a new work and give edit access to a group.  Then have people verify they have access.  Make sure the people in the group are not administrators.

**Comment by carolyncole** [comment]
The short answer is yes the groups still work.  I would guess there are some settings that might cause it not to work, like being able to choose if it is stored in LDAP.  We may need to update wording to include that caveat.
