### ISSUE TITLE
Front End Analysis

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1438]
Find out where the system is slow on the front end.

Do an audit on the front end.  Are the thumbnails too big?  Utilize an existing tool to create a report.  Possibly use google developers tools or something from a search of tools.

Does new relic give us this information?

**Comment by mtribone** [comment]
Google Dev Tools - Lighthouse

Just a few things that stand out to me doing a quick test of my Samvera Connect Poster Collection.

* CSS file is (614 KB)
* JS file is (2,799 KB)
* Preload or Remove
  * glyphicons (18 KB)
  * fontawesome (76 KB)
* Compression
  * JS
  * CSS
  * images and thumbnails (JPEG 200, JPEG XR, WebP)
  * Penn State mark (19 KB)
  * minify assets
  * update for better, faster, newer

Diagnostics
* inefficient [cache policy](https://developers.google.com/web/tools/lighthouse/audits/cache-policy)
* leverage [font-display](https://developers.google.com/web/updates/2016/02/font-display)
* enormous network payload (4,068 KB)
* critical request chains (Longest chain: 457.7ms over 3 requests, totalling 75.6 KB)

Additionally, look at the gems in use and see what is being loaded. We might be able to eliminate some things and improve performance by not loading everything for every page.

Reference
https://www.smashingmagazine.com/2018/01/front-end-performance-checklist-2018-pdf-pages/

**Comment by mtribone** [comment]
We need to discuss the longevity of doing front end performance work in comparison with a possible move to Hyrax. Perhaps as a first step we could make sure that both the JS and CSS are minified and that they thumbnails are compressed a little more aggressively.
