### ISSUE TITLE
Get timing Numbers on test suite running

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1439]
What are the current numbers for how long the test suite runs

Run the test suite locally and document the numbers
Gather numbers from travis

**Comment by carolyncole** [comment]
Here is a run from my machine:

## release-3.5.0
```
Top 10 slowest examples (505.98 seconds, 17.7% of total time):
  GenericWork displays the contents of the readme
    163.45 seconds ./spec/features/remote_download_spec.rb:18
  ExternalFilesConversion running without sha1 mocked converts all versions of all the files of a work
    92.44 seconds ./spec/services/external_files_conversion_spec.rb:230
  DownloadsController#show with a GenericWork downloads a zip
    54.26 seconds ./spec/controllers/downloads_controller_spec.rb:108
  Batch management of works when editing and viewing multiple works edits a field and displays the changes
    47.44 seconds ./spec/features/batch_edit_spec.rb:39
  Checksummer can return the checksum for works stored as external files
    34.43 seconds ./spec/services/checksummer_spec.rb:21
  FileSet versioning: sets the file set title and label to new and reverted file versions
    30.97 seconds ./spec/features/file_set/versioning_spec.rb:16
  GenericWork displays the contents of the readme
    24.09 seconds ./spec/features/generic_work/work_with_readme_spec.rb:13
  Generic File uploading and deletion: when logged in as a PSU user cloud providers I can click on cloud providers
    20.84 seconds ./spec/features/generic_work/upload_and_delete_spec.rb:39
  Generic File batch uploading when logged in as a PSU user uploading a new work enforces a workflow
    19.21 seconds ./spec/features/generic_work/batch_upload_and_delete_spec.rb:17
  Dashboard Works Many Works Changing the number per page on other pages of My Works redirects to page 1
    18.85 seconds ./spec/features/dashboard/dashboard_works_spec.rb:224

Top 10 slowest example groups:
  GenericWork
    163.49 seconds average (163.49 seconds / 1 example) ./spec/features/remote_download_spec.rb:7
  FileSet versioning:
    30.97 seconds average (30.97 seconds / 1 example) ./spec/features/file_set/versioning_spec.rb:5
  Batch management of works
    20.09 seconds average (60.27 seconds / 3 examples) ./spec/features/batch_edit_spec.rb:5
  Generic File batch uploading
    19.21 seconds average (19.21 seconds / 1 example) ./spec/features/generic_work/batch_upload_and_delete_spec.rb:5
  Checksummer
    18.99 seconds average (37.99 seconds / 2 examples) ./spec/services/checksummer_spec.rb:5
  GenericWork
    16.95 seconds average (16.95 seconds / 1 example) ./spec/features/generic_work/restricted_upload_spec.rb:5
  FileSet
    15.95 seconds average (15.95 seconds / 1 example) ./spec/features/file_set/extracted_text_search_spec.rb:5
  ExternalFilesConversion
    14.8 seconds average (162.83 seconds / 11 examples) ./spec/services/external_files_conversion_spec.rb:6
  Generic File uploading and deletion:
    13.78 seconds average (41.33 seconds / 3 examples) ./spec/features/generic_work/upload_and_delete_spec.rb:7
  FileSet Thumbnail Creation:
    13.76 seconds average (13.76 seconds / 1 example) ./spec/features/file_set/analytics_spec.rb:7

Finished in 47 minutes 44 seconds (files took 8.63 seconds to load)
```

## develop 
```
Top 10 slowest examples (408.38 seconds, 15.4% of total time):
  GenericWork displays the contents of the readme
    130.76 seconds ./spec/features/remote_download_spec.rb:18
  ExternalFilesConversion running without sha1 mocked converts all versions of all the files of a work
    60.04 seconds ./spec/services/external_files_conversion_spec.rb:230
  Batch management of works when editing and viewing multiple works edits a field and displays the changes
    51.19 seconds ./spec/features/batch_edit_spec.rb:39
  ExternalFilesConversion running a conversion from internal to external file storage converts a single work of a given Class
    34.57 seconds ./spec/services/external_files_conversion_spec.rb:26
  FileSet versioning: sets the file set title and label to new and reverted file versions
    27.67 seconds ./spec/features/file_set/versioning_spec.rb:16
  DownloadsController#show with a GenericWork downloads a zip
    27.3 seconds ./spec/controllers/downloads_controller_spec.rb:108
  GenericWork displays the contents of the readme
    21.91 seconds ./spec/features/generic_work/work_with_readme_spec.rb:13
  Dashboard Works Many Works Changing the number per page on other pages of My Works redirects to page 1
    18.98 seconds ./spec/features/dashboard/dashboard_works_spec.rb:224
  Generic File uploading and deletion: when logged in as a PSU user cloud providers I can click on cloud providers
    18.01 seconds ./spec/features/generic_work/upload_and_delete_spec.rb:39
  Generic File batch uploading when logged in as a PSU user uploading a new work enforces a workflow
    17.94 seconds ./spec/features/generic_work/batch_upload_and_delete_spec.rb:17

Top 10 slowest example groups:
  GenericWork
    130.79 seconds average (130.79 seconds / 1 example) ./spec/features/remote_download_spec.rb:7
  FileSet versioning:
    27.67 seconds average (27.67 seconds / 1 example) ./spec/features/file_set/versioning_spec.rb:5
  Batch management of works
    21.6 seconds average (64.79 seconds / 3 examples) ./spec/features/batch_edit_spec.rb:5
  Generic File batch uploading
    17.94 seconds average (17.94 seconds / 1 example) ./spec/features/generic_work/batch_upload_and_delete_spec.rb:5
  GenericWork
    17.08 seconds average (17.08 seconds / 1 example) ./spec/features/generic_work/restricted_upload_spec.rb:5
  FileSet
    14.99 seconds average (14.99 seconds / 1 example) ./spec/features/file_set/extracted_text_search_spec.rb:5
  ExternalFilesConversion
    14.11 seconds average (155.26 seconds / 11 examples) ./spec/services/external_files_conversion_spec.rb:6
  Generic File uploading and deletion:
    12.32 seconds average (36.96 seconds / 3 examples) ./spec/features/generic_work/upload_and_delete_spec.rb:7
  FileSet Thumbnail Creation:
    12.17 seconds average (12.17 seconds / 1 example) ./spec/features/file_set/analytics_spec.rb:7
  PermissionsSharing:
    12.09 seconds average (12.09 seconds / 1 example) ./spec/features/file_set/permissions_sharing_spec.rb:5

Finished in 44 minutes 12 seconds (files took 6.75 seconds to load)
817 examples, 15 failures, 8 pending
```

**Comment by carolyncole** [comment]
Another run from develop after chromedriver:

Top 10 slowest examples (805.94 seconds, 34.8% of total time):
  GenericWork displays the contents of the readme
    251.62 seconds ./spec/features/remote_download_spec.rb:18
  DownloadsController#show with a GenericWork downloads a zip
    134.87 seconds ./spec/controllers/downloads_controller_spec.rb:108
  FileSet when searching the file set's extraced text returns the file set's containing work
    133.08 seconds ./spec/features/file_set/extracted_text_search_spec.rb:16
  FileSet file with text #.to_solr contains the extracted text
    132.51 seconds ./spec/models/file_set_spec.rb:62
  Batch management of works when editing and viewing multiple works edits a field and displays the changes
    52.46 seconds ./spec/features/batch_edit_spec.rb:39
  FileSet versioning: sets the file set title and label to new and reverted file versions
    27.61 seconds ./spec/features/file_set/versioning_spec.rb:16
  GenericWork displays the contents of the readme
    19 seconds ./spec/features/generic_work/work_with_readme_spec.rb:13
  Generic File uploading and deletion: when logged in as a PSU user cloud providers I can click on cloud providers
    18.79 seconds ./spec/features/generic_work/upload_and_delete_spec.rb:39
  Create a Generic Work with multiple Creators a logged in user should have css ".creator_inputs"
    18.07 seconds ./spec/features/generic_work/add_multiple_creators_spec.rb:27
  Dashboard Works Many Works Changing the number per page on other pages of My Works redirects to page 1
    17.92 seconds ./spec/features/dashboard/dashboard_works_spec.rb:224

Top 10 slowest example groups:
  GenericWork
    251.63 seconds average (251.63 seconds / 1 example) ./spec/features/remote_download_spec.rb:7
  FileSet
    133.1 seconds average (133.1 seconds / 1 example) ./spec/features/file_set/extracted_text_search_spec.rb:5
  FileSet versioning:
    27.61 seconds average (27.61 seconds / 1 example) ./spec/features/file_set/versioning_spec.rb:5
  Batch management of works
    24.03 seconds average (72.08 seconds / 3 examples) ./spec/features/batch_edit_spec.rb:5
  Create a Generic Work with multiple Creators
    18.09 seconds average (18.09 seconds / 1 example) ./spec/features/generic_work/add_multiple_creators_spec.rb:6
  Generic File batch uploading
    17.14 seconds average (17.14 seconds / 1 example) ./spec/features/generic_work/batch_upload_and_delete_spec.rb:5
  GenericWork
    16.8 seconds average (16.8 seconds / 1 example) ./spec/features/generic_work/restricted_upload_spec.rb:5
  DownloadsController
    14.64 seconds average (161 seconds / 11 examples) ./spec/controllers/downloads_controller_spec.rb:5
  Generic File uploading and deletion:
    12.57 seconds average (37.72 seconds / 3 examples) ./spec/features/generic_work/upload_and_delete_spec.rb:7
  ImportVersionJob
    12.15 seconds average (12.15 seconds / 1 example) ./spec/jobs/import_version_job_spec.rb:5

Finished in 38 minutes 38 seconds (files took 5.21 seconds to load)
611 examples, 6 failures, 4 pending

**Comment by mtribone** [comment]
## Develop
 commit `1e0ede0cc02c7a4c49b0cb2f44947e40b1a30114`



Top 10 slowest examples (162.65 seconds, 12.7% of total time):
  Create a Generic Work with multiple Creators a logged in user should have css ".creator_inputs"
    21.28 seconds ./spec/features/generic_work/add_multiple_creators_spec.rb:27
  unified search known user searches all
    20.51 seconds ./spec/features/unified_search_spec.rb:51
  FileSet versioning: sets the file set title and label to new and reverted file versions
    19.14 seconds ./spec/features/file_set/versioning_spec.rb:16
  Batch management of works when editing and viewing multiple works edits a field and displays the changes
    18.44 seconds ./spec/features/batch_edit_spec.rb:39
  GenericWork when restricting total upload size prevents submitting the form
    16.3 seconds ./spec/features/generic_work/restricted_upload_spec.rb:19
  Generic File uploading and deletion: when logged in as a PSU user cloud providers I can click on cloud providers
    14.53 seconds ./spec/features/generic_work/upload_and_delete_spec.rb:39
  Generic File uploading and deletion: when logged in as a PSU user with a single local file uploads the file, sends notification, creates new agent records, and deletes the file
    14.52 seconds ./spec/features/generic_work/upload_and_delete_spec.rb:88
  GenericWork displays the contents of the readme
    14.17 seconds ./spec/features/generic_work/work_with_readme_spec.rb:13
  Dashboard Works Many Works Changing the number per page on other pages of My Works redirects to page 1
    12.51 seconds ./spec/features/dashboard/dashboard_works_spec.rb:224
  Generic File batch uploading when logged in as a PSU user uploading a new work enforces a workflow
    11.25 seconds ./spec/features/generic_work/batch_upload_and_delete_spec.rb:17

Top 10 slowest example groups:
  Create a Generic Work with multiple Creators
    21.32 seconds average (21.32 seconds / 1 example) ./spec/features/generic_work/add_multiple_creators_spec.rb:6
  FileSet versioning:
    19.14 seconds average (19.14 seconds / 1 example) ./spec/features/file_set/versioning_spec.rb:5
  GenericWork
    16.3 seconds average (16.3 seconds / 1 example) ./spec/features/generic_work/restricted_upload_spec.rb:5
  Generic File batch uploading
    11.25 seconds average (11.25 seconds / 1 example) ./spec/features/generic_work/batch_upload_and_delete_spec.rb:5
  Generic File uploading and deletion:
    10.51 seconds average (31.53 seconds / 3 examples) ./spec/features/generic_work/upload_and_delete_spec.rb:7
  FileSet
    10.49 seconds average (10.49 seconds / 1 example) ./spec/features/file_set/extracted_text_search_spec.rb:5
  Batch management of works
    9.49 seconds average (28.46 seconds / 3 examples) ./spec/features/batch_edit_spec.rb:5
  unified search
    8.57 seconds average (34.27 seconds / 4 examples) ./spec/features/unified_search_spec.rb:5
  GenericWork
    8.46 seconds average (8.46 seconds / 1 example) ./spec/features/remote_download_spec.rb:7
  FileSet Thumbnail Creation:
    8.02 seconds average (8.02 seconds / 1 example) ./spec/features/file_set/analytics_spec.rb:7

Finished in 21 minutes 16 seconds (files took 4.96 seconds to load)
608 examples, 3 failures, 4 pending

Failed examples:

rspec ./spec/features/generic_work/add_multiple_creators_spec.rb:27 # Create a Generic Work with multiple Creators a logged in user should have css ".creator_inputs"
rspec ./spec/features/remote_download_spec.rb:18 # GenericWork displays the contents of the readme
rspec ./spec/features/unified_search_spec.rb:51 # unified search known user searches all
