### ISSUE TITLE
Not test every line multiple times

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1444]
collaborator
Look at the report from codeclimate or coveralls to get an idea of where things are being tested multiple times.

Use that report to combine tests and remove unneeded tests.

**Comment by cam156** [comment]
Look at the report from codeclimate or coveralls to get an idea of where things are being tested multiple times.  

Use that report to combine tests and remove unneeded tests.

**Comment by carolyncole** [comment]
Here is a coveralls report with 92% coverage.  It is not develop, but I have not seen a good report in a bit... https://coveralls.io/github/psu-stewardship/scholarsphere?branch=i%231451
