### ISSUE TITLE
Make sure that email and PSU ID are pre-filled when creating a work

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1453]
When a user is creating a work and is filling out the metadata form for creator on a new work, it is expected that the email and PSU ID are pre-filled with the user's information.

**Comment by mtribone** [comment]
During the Open Access Week upload party, a user commented that it was confusing that the information was not filled out automatically. It was filled out automatically for the co-creator. The expectation is that since there are fields in the box and other info was filled in that this information should be filled in also.

**Comment by carolyncole** [comment]
change label to `Access ID (xyz123)`  for login.  The form needs to be updated to pre fill the depositor with email and login. Mustache template needs to be updated to include the email.

**Comment by carolyncole** [comment]
Need to be able to not have the depositor as a creator.  Currently the depositor is read only (if an agent already exists).  Would it be best to add a remove button to the first item if there are more than one creators, or leave the form always editable on new?

**Comment by carolyncole** [comment]
Add a creator adds the remove button to the first entry.  The Search does not add the remove button.  We need the search to add the remove button to the first item, like the add button does.
