### ISSUE TITLE
Send Monthly Statistic report

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1454]
On the administrative dashboard allow the user to slect a date range (already implemented) and then click on a button to download a Upload report or a usage report

The download report would have the same format as the weekly report sent via email: https://github.com/psu-stewardship/scholarsphere/blob/develop/lib/tasks/scholarsphere.rake#L207-L209

The Usage report (downloads and views) would have the following format:
File URL, work URL, downloads, views

Not needed:

https://github.com/psu-stewardship/scholarsphere/blob/develop/config/cronjobs/send_weekly_stats.bash

https://github.com/psu-stewardship/scholarsphere/blob/develop/config/schedule.rb#L45

**Comment by DanCoughlin** [comment]
From the spreadsheet, folks would like the ability to create: 
Total number of uploads by resource type

Downloads:
Number of total downloads
Top 10 downloads (urls)

**Comment by carolyncole** [comment]
https://github.com/psu-stewardship/scholarsphere/wiki/Yearly-Download-and-Upload-Report - Keep empty downloads in the report.

**Comment by mtribone** [comment]
Getting weekly stats and aggregating that data.
