### ISSUE TITLE
Minify JS for Production

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1459]
Currently in production we are serving full JS without minification. Figure out why it isn't be minified and perhaps ensure multiple copies of JS aren't being inserted.

https://scholarsphere.psu.edu/assets/application-6d4e6a8da32a16b332d0e868d9dbfc036accb6178a4b89b37fb373143c912e17.js

**Comment by mtribone** [comment]
Looks like the compressors are commented out in production: https://github.com/psu-stewardship/scholarsphere/blob/develop/config/environments/production.rb#L69

**Comment by mtribone** [comment]
CSS is compressed by default using `sass-rails`, however, I don't think that the JS is compressed by default.

https://guides.rubyonrails.org/configuring.html#configuring-assets

**Comment by carolyncole** [comment]
Looks like this was started here: https://github.com/psu-stewardship/scholarsphere/tree/i%231459-minify-js
