### ISSUE TITLE
Duplicate Copies of Bootstrap CSS

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1460]
We have 3 copies of Bootstrap CSS, minified, in our production CSS file. Figure out why and fix.

https://scholarsphere.psu.edu/assets/application-d2727e60c6788ec4362632c88b07a7719a797e9d4d2690f0c940c073cc4c627a.css

**Comment by mtribone** [comment]
Do we need `bootstrap-sprockets` here?
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/assets/stylesheets/sufia.scss#L7

**Comment by carolyncole** [comment]
Browse everything and Sufia include these.  Remove the duplicates from https://github.com/psu-stewardship/scholarsphere/blob/develop/app/assets/stylesheets/application.css

Is there a gem that would remove the duplication.  Why does the asset pipeline not do this?
