### ISSUE TITLE
Security Vulnerabilities with third party JS

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#1462]
Dev tools lists 3 libraries with security vulnerabilities.

1. Bootstrap 3.3.7
1. jQuery 1.12.4
1. jQuery UI 1.11.4

The version of jQuery that we are using is from 2016. Recommend a plan to upgrade the libraries to the most current versions.

**Comment by carolyncole** [comment]
How can we verify that these are actual vulnerabilities?  Github is not reporting these as  issue.

Update to the latest Bootstrap 3.

**Comment by mtribone** [comment]
Security Vulnerabilities

Bootstrap
https://snyk.io/vuln/npm:bootstrap?lh=3.3.7

jQuery
https://snyk.io/vuln/npm:jquery?lh=1.12.4

jQuery UI
https://snyk.io/vuln/npm:jquery-ui?lh=1.11.4

Bootstrap Blog Addressing Security
https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/

**Comment by mtribone** [comment]
Unable to update the jQuery because we are on the latest Curation Concerns (1.7.8) that does NOT require a migration with reverse membership. Upgrading to CC 2.0 would require the relationship change and a migration to update jQuery. This is not ideal at this point in time.
