### ISSUE TITLE
Analytics start date is migration date not uploaded date

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#147]
https://scholarsphere.psu.edu/files/g732d898n#.VTaBu2TBwXA was uploaded in 2013

Analytics show as of April 11th (https://scholarsphere.psu.edu/files/g732d898n/stats)

We need to use the field that is being displayed when querying google instead of the field that we are currently using.

**Comment by carolyncole** [comment]
Looks like this line is the problem: https://github.com/projecthydra/sufia/blob/master/sufia-models/app/models/file_usage.rb#L13

It should  look more like this: 
self.created = Date.parse(::GenericFile.load_instance_from_solr(id).date_uploaded)

**Comment by hectorcorrea** [comment]
PR submitted to Sufia to handle this https://github.com/projecthydra/sufia/pull/1052

**Comment by hectorcorrea** [comment]
I've got a branch in SS with the fix but I am still testing it. 
https://github.com/psu-stewardship/scholarsphere/commit/ed29ae7e4cde2555825720eed7b4217017c911a9

**Comment by hectorcorrea** [comment]
PR for ScholarSphere is #160

**Comment by awead** [comment]
The 2.2.4 release did not seem to fix this.

**Comment by carolyncole** [comment]
This seems to be only partially fixed.  The date above the graph is correct, but the graph itself is not.

**Comment by carolyncole** [comment]
I think I see the issue:

```
 => #<FileViewStat id: 1, date: "2013-03-24 00:00:00", views: 0, file_id: "scholarsphere:x346dj321", created_at: "2015-01-16 11:18:52", updated_at: "2015-01-16 11:18:52", user_id: 2>
```

See the scholarsphere in the id...

**Comment by hectorcorrea** [comment]
Closing the loop on this. We've updated the data in `file_view_stats` and `file_download_stats` so that field `file_id` does not include "scholarsphere:"

```
update file_view_stats set file_id = substring(file_id, 15) where substring(file_id, 1, 14) = "scholarsphere:";

update file_download_stats set file_id = substring(file_id, 15) where substring(file_id, 1, 14) = "scholarsphere:";
```
