### ISSUE TITLE
Deprecation warning on prod for rights

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1475]
DEPRECATION WARNING: You are using the deprecated RightsService module, but you do not have 'rights.yml'. Switch to CurationConcerns::LicenseService instead. (called from <module:RightsService> at /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/curation_concerns-1.7.8/app/services/rights_service.rb:4)
Loading production environment (Rails 4.2.7.1)

**Comment by mtribone** [comment]
It looks like we are calling the updated Rights Service in the edit fields for records. Not sure why we are getting the deprecation warning in production.

https://github.com/psu-stewardship/scholarsphere/blob/develop/app/views/records/edit_fields/_rights.html.erb#L1

**Comment by mtribone** [comment]
licenses authorities
https://github.com/psu-stewardship/scholarsphere/blob/develop/config/authorities/licenses.yml

**Comment by mtribone** [comment]
It was suggested that perhaps updating our version of Curation Concerns would resolve the deprecation warning, however, Sufia 7.4.1 requires Curation Concerns 1.7.6. Upgrading to Curation Concerns 2.0.0 would also require a data migration and resolving compatible version of Active Fedora, Hydra Batch Edit, Mailboxer, Blacklight Gallery, etc.

**Comment by mtribone** [comment]
Wait until we upgrade to Hyrax to solve the deprecation warning.

**Comment by mtribone** [comment]
The direction has changed scope.
