### ISSUE TITLE
Video player gets too big

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1519]
The video player is overwriting the contents of the page
https://scholarsphere.psu.edu/concern/parent/db78tc20t/file_sets/9kd17cs73r

**Comment by carolyncole** [comment]
Add `width: 100%` to the  video.  Make sure that this works on multiple browsers.  It was only tested in Chrome.

**Comment by awead** [comment]
Confirmed: works in Chrome, Firefox, and Safari.
