### ISSUE TITLE
Remove override in User show for labels

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#155]
Remove the overrides in user show adde here: https://github.com/psu-stewardship/scholarsphere/commit/a550bb6b385f2fc0d106fb63db76d14fb6689dbc

Make sure this ticket has been closed in sufia: projecthydra/sufia#1056

**Comment by carolyncole** [comment]
Check in SUfia 6.3  This is not quite fixed.  When the user has no highlights the wording still says files.

**Comment by carolyncole** [comment]
Looks like ti was put in the PCDM version of sufia.

**Comment by awead** [comment]
Verify, or backport to Sufia 6 from Sufia 7.

**Comment by awead** [comment]
Backported in projecthydra/sufia#1524
