### ISSUE TITLE
The sitemap has http instead of https

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#1555]
Google is not indexing our data since the sitemap is saying http and we are redirecting to https.  We should change the sitemap generator to have the correct https urls.

https://search.google.com/search-console/index/drilldown?resource_id=http%3A%2F%2Fscholarsphere.psu.edu%2F&item_key=CAESKGh0dHA6Ly9zY2hvbGFyc3BoZXJlLnBzdS5lZHUvc2l0ZW1hcC54bWwYFiAC&hl=en
![screen shot 2019-03-01 at 3 18 00 pm](https://user-images.githubusercontent.com/1599081/53663992-3a445200-3c35-11e9-8287-56f258d84e01.png)

**Comment by awead** [comment]
All the sitemap urls are https. I updated the robots.txt file, which points to the sitemap file, to use https. I also removed the "http://scholarsphere.psu.edu" property from the Google console. It may have been viewing the http site and the https site as separate entities.

There seem to be fewer unindexed pages from the sitemap:

![Screen Shot 2019-04-22 at 1 11 22 PM](https://user-images.githubusercontent.com/312085/56513340-2fed5880-6500-11e9-9dad-2de5a1929dfc.png)
