### ISSUE TITLE
Remove help override in ScholarSphere for collection

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#156]
Remove the oveeride once this ticket is closed: projecthydra/sufia#1057

**Comment by carolyncole** [comment]
Checked this with 6.3.0  Either we have additional overrides, or the sufia implementation is incorrect.

**Comment by awead** [comment]
remove bccb0fb86596fe1af5fefed40293b799479b7b08

**Comment by awead** [comment]
backported in projecthydra/sufia#1525
