### ISSUE TITLE
README.md files sometimes identified as video/m2ts

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere-3#1587]
README.md files are sometimes identified as Mime Type: video/m2ts. Behaviour seems to vary, but here is an example:
https://scholarsphere.psu.edu/concern/parent/bnz805z66z/file_sets/mpg15bf61m

**Comment by awead** [comment]
FITS is identifying this file as `video/m2ts` which is triggering the video derivative creation process. It doesn't seem to affect the rendering of the readme, which is nice, but the characterization metadata is incorrect. I haven't been able to replicate this on the jobs server. It's possible it's something to do with certain Readme files, or their character encoding, or it's an issue with fits. I don't believe we've update it's version at all in the past year or more.

**Comment by mtribone** [comment]
For this version of SS let's handle it by a local fix. The files are not consistently being added to the work. Could possibly be a configuration fix.

**Comment by whereismyjetpack** [comment]
looks like we can add the following into fits.xml to resolve the issue with markdown files 
```<tool class="edu.harvard.hul.ois.fits.tools.exiftool.Exiftool" exclude-exts="md,txt,wps,vsd,jar,avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4" classpath-dirs="lib/exiftool" />```

we currently aren't managing this file, but if this seems like a sane approach, i can vendor the configuration and have chef manage it.

**Comment by whereismyjetpack** [comment]
I've updated the configuration on the qa jobs box, with the readme file above it's now being classified as plain text.


```
/fits.sh -i /tmp/README.md
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.2.2" timestamp="7/8/19 11:17 AM">
  <identification status="SINGLE_RESULT">
    <identity format="Plain text" mimetype="text/plain" toolname="FITS" toolversion="1.2.2">
      <tool toolname="file utility" toolversion="5.28" />
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/tmp/README.md</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">README.md</filename>
    <size toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">3257</size>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">18bb526f0a2a09989c0af7334588391c</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1562595576000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <text>
      <charset toolname="file utility" toolversion="5.28" status="SINGLE_RESULT">US-ASCII</charset>
    </text>
  </metadata>
  <statistics fitsExecutionTime="400">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.3" executionTime="75" />
    <tool toolname="Jhove" toolversion="1.20" status="did not run" />
    <tool toolname="file utility" toolversion="5.28" executionTime="389" />
    <tool toolname="Exiftool" toolversion="10.00" status="did not run" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="73" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="346" />
    <tool toolname="Tika" toolversion="1.10" executionTime="165" />
  </statistics>
</fits>
```

is someone able to reproduce on the qa servers? @srerickson @awead

**Comment by awead** [comment]
@whereismyjetpack Great! However, don't we only need to exclude the `md` extension? We want Exiftool to run for all the other types of files, I believe.

**Comment by whereismyjetpack** [comment]
I should have been more clear. the default `fits.xml` that we get has ```<tool class="edu.harvard.hul.ois.fits.tools.exiftool.Exiftool" exclude-exts="txt,wps,vsd,jar,avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4" classpath-dirs="lib/exiftool" />``` I just tacked md in the front. i think for the other file types, there are other classes that do run on them. for example, ```        <tool class="edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo" include-exts="avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4" classpath-dirs="lib/mediainfo" />``` so, mp4's will use the `MediaInfo` class, but ignore `Exiftool`

**Comment by awead** [comment]
@whereismyjetpack Sounds good. There's a config file in this repo under `fits_conf/fits.xml`. Can you put in a PR for an updated config file with these changes that matches what will go into qa and production? This is similar to the way we keep our solr configs between repo and deployment in sync.

**Comment by whereismyjetpack** [comment]
@awead https://github.com/psu-stewardship/scholarsphere/pull/1592

**Comment by whereismyjetpack** [comment]
This configuration was placed on the servers today. Please let me know if something needs mended

**Comment by srerickson** [comment]
Thanks! I'll try it out.

**Comment by srerickson** [comment]
Works as expected when I upload the README.md in the OP to a new work. I also re-uploaded the README to the existing work and the mime type was correctly updated to `text/plain`. 

Thanks! @whereismyjetpack
