### ISSUE TITLE
User stats emails should not be sent on system other than prod

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#1614]
Stage and QA likely have the same cron jobs as prod, which means they will send out emails on the same date as prod. We should not do this.

**Comment by awead** [comment]
TODO:
* ensure cron job for `scholarsphere:stats:notify` only runs on the production jobs server

**Comment by whereismyjetpack** [comment]
what we usually do is have a global bit that turns off the mailer, or use something like `mailcatcher`

are we setting email on / off in the rails config someplace?

**Comment by awead** [comment]
@whereismyjetpack No, mailler is on. I'm thinking we need to have another ENV key in `application.yml` that indicates what "environment" it is: qa, stage, prod, etc. But "environment" doesn't seem to be the right word.

**Comment by whereismyjetpack** [comment]
I'm usually more a fan of explicit config bits, instead of guessing based off env (this seems to be a rails anitpattern though) 

i.e 
```
mailer:
  enabled: true
```

in `application.yml`

**Comment by whereismyjetpack** [comment]
there may also be a case where we want to sent the smtp server to something like mail catcher to get a view on what it _would_ have done?

**Comment by awead** [comment]
The mailer still needs to be enabled so we can test things. We can just turn off the job under config/schedule.rb:31.
