### ISSUE TITLE
remove empty string from resource_type

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere-3#1617]
The blank resource type (#1396) is still lingering in  some objects' resource type field. For example:
```json
{
        "has_model_ssim":["GenericWork"],
        "id":"5712m6699",
        "resource_type_tesim":["", "Other"]}]
  }
```

[This csv](https://github.com/psu-stewardship/scholarsphere/files/3502755/resource_type-fixed.txt) (which I've renamed to `.txt` to agree with Github's restrictions on files that can be attached to issues)  includes a list of objects that need to be fixed, along with the corrected value for the resource type. Columns are: `id`, `has_model_ssim`, `OLD_resource_type_tesim`,  `NEW_resource_type_tesim`. Hopefully this file can be used for a batch update.

**Comment by awead** [comment]
@srerickson I went ahead and updated the resources in Scholarsphere listed in the CSV. Re-run the query and see if we've got them all.

**Comment by srerickson** [comment]
Looks good. I don't see any Works the the empty resource_type. "unspecified" is also gone as an option for the resource type on the search page, which is great.
