### ISSUE TITLE
local anchor tags have spaces in them

### ISSUE THREAD

**Issue by jgm106** [psu-libraries/scholarsphere-3#169]
Specifically, I found the issue was on https://scholarsphere.psu.edu/about/

```
<a href="#Preservation Support Policy">Preservation Support Policy</a>
```

causes the following link (minus the quotes)

   "https://scholarsphere.psu.edu/about/#Content Policy"

See even github doesn't like it :) This could lend itself to a usability issue.

**Comment by carolyncole** [comment]
I clean up the about page on ss-qa and production.
