### ISSUE TITLE
schema imposes limit on users.group_list

### ISSUE THREAD

**Issue by cswalina** [psu-libraries/scholarsphere-3#17]
@cam156 We noticed that the db/schema.rb file has a limit of 255 characters on the `users.group_list` text field:

https://github.com/psu-stewardship/scholarsphere/blob/develop/db/schema.rb#L211

That seems to be counter to the intent of this commit (allow a user to belong to lots of groups): https://github.com/psu-stewardship/scholarsphere/commit/e93d0e87bd56ffaa31889a7b6a91f3cbecfa9cba

When we do a `rake db:schema:dump` on our development machines, we get the desired outcome, where the limit is not imposed on the text column. This disagrees with the copy of db/schema.rb that's checked in.

It seems like the current db/schema.rb is incorrect. Should we commit a version that removes that `:limit => 255` for this column? Otherwise, some tests fail and some pass, depending on whether the user loaded their database via migrations or via the schema.
- Chet, @woods, @niedermyer

**Comment by mjgiarlo** [comment]
Pinging @jcoyne for advice on this as well.  Especially if this touches on https://github.com/projecthydra/sufia

(But, yes, it does seem strange that the schema places this limit on the groups field!)

**Comment by jcoyne** [comment]
@mjgiarlo I wasn't even aware of that group_list attribute. Apparenlty it was introduced here: https://github.com/projecthydra/sufia/commit/1ca5a32be2a6ebf0b93d04798fb94bcb939434a5#diff-c4edcb3b48d48dccc32ba8078cd2267aR79

I was under the impression that was all LDAP.

**Comment by jcoyne** [comment]
@jeremyf did this just show up out of nowhere? https://github.com/projecthydra/sufia/commit/1ea58a9b03967e9bb22e3e7e5dbfb734e2553755#diff-124690f37e2453ca359325e829371e8dR1

**Comment by jcoyne** [comment]
Ah, here's the original source:
https://github.com/psu-stewardship/scholarsphere/commit/7749f7ef944e23f3b070318cc9c3975318eedf1c#diff-c2292aaedd82ee775ec4046363082e21R3

It looks like it was originally a string type thus the 255 char limit.  When it was moved into sufia it was change to a text type, so no limit.

**Comment by carolyncole** [comment]
I think this should be ok to remove.  We were only using migrations up until the point that this was added to git.  My guess is we just got a copy that was a bit off.
