### ISSUE TITLE
User get created when you go to /users/<id>

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#175]
When you go to the users/<id> the user gets created if it does not already exists.

https://scholarsphere-qa.dlt.psu.edu/users/abc

**Comment by carolyncole** [comment]
Should clean up ids

**Comment by carolyncole** [comment]
Here is the offending code/  Should do User.new with a block and save only if user exists in the ldap
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/models/user.rb#L190-L191

**Comment by mjgiarlo** [comment]
Wow, good catch!  That is gross.  Agree with your recommendation.

**Comment by carolyncole** [comment]
fixed with: https://github.com/psu-stewardship/scholarsphere/commit/4cd3a5d60c8a177b429f2e31918208df5a3ce2b6

**Comment by mjgiarlo** [comment]
:clap:
