### ISSUE TITLE
Rights field should only allow a single value to be selected

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#183]
Original information from Patricia:

This is our newest deposit: https://scholarsphere.psu.edu/files/5712mv73t. You'll notice in the metadata that it has two entries for the Rights field: All rights reserved and CC BY-NC-ND. Is there a way to disable the selection of more than one license for this field? Or perhaps I'm being naive and there really are instances in which more than two would make sense. (These two that the user has selected don't make sense to me, though, unless I'm missing something. And I realize that one of these, C BY-NC-ND, is the default.)

**Comment by carolyncole** [comment]
It seems the rights feild is single valued on the edit screen and multi valued on the upload screen.

Edit
![screen shot 2015-08-19 at 10 20 56 am](https://cloud.githubusercontent.com/assets/1599081/9358868/3956b23e-465c-11e5-8e74-cc425740644d.png)

Upload

![screen shot 2015-08-19 at 10 21 48 am](https://cloud.githubusercontent.com/assets/1599081/9358872/3eaf5358-465c-11e5-9e08-e7d7ab67ad9d.png)

**Comment by awead** [comment]
I was able to select multiple values in the edit view using shift-click, but either way, I think a single-value select box would be the way to do. Also, we could optionally change Sufia to enforce `multiple: false` on the model.

**Comment by patriciahswe** [comment]
+1 for single value. Plus, I checked with the user, and he did not mean to have two values for the Rights field, so he went back in to edit that field to reflect a single value (All rights reserved).

But here's a new issue - "All rights reserved" appears twice in the Rights field (once as a hyperlinked phrase). See: https://scholarsphere.psu.edu/files/5712mv73t

**Comment by mjgiarlo** [comment]
:+1: to fixing this in Sufia -- I doubt anyone who's not overriding Rights locally wants this. (And if they're already doing local overrides, they can change their overridden Rights to multi-valued easily.)

**Comment by awead** [comment]
Linked: projecthydra/sufia#1287

**Comment by mjgiarlo** [comment]
:clap:

**Comment by awead** [comment]
This is current "fixed" so that the select only allows you to select one value. However, you're still able to add additional licenses. See the current edit page:
![rights](https://cloud.githubusercontent.com/assets/312085/12486778/195882dc-c032-11e5-935b-2a5adbed172a.png)
If we want the field to truly be single-valued, we'll need to do some kind of migration work, since we may have files that currently have more than one value. Doing this during the PCDM migration seems like a good time. I'll close this ticket and open another one to reflect the change.

**Comment by mjgiarlo** [comment]
@awead Hey! Is this an issue in Sufia more broadly, or just a sphere thang? If the former, it'd be great to have this addressed in the 6.x -> 7 upgrade/migration process.

**Comment by awead** [comment]
@mjgiarlo both. So, yeah, probably should be done in the migration to PCDM.

**Comment by mjgiarlo** [comment]
OK, it'll be good to have this work in Sufia proper. Thanks, @awead.
