### ISSUE TITLE
Email Daily Statistics

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#184]
Send an email with a report about the system.

Current format:
https://docs.google.com/document/d/1WvdsT4pPb3F_Tn9YfrQSWqj-NskmAjl_T8ey4aYrkWk/edit

**Comment by awead** [comment]
@cam156 do we still need this? I thought the admin stats page could just show us this information.

**Comment by carolyncole** [comment]
@awead Patricia HAD wanted an email so she did not have to log into the system to get the information.

The email is being produced daily, but only being received by me.  The information we had to offer was lacking when we rolled the change out, but I do not have details on what was missing. 

I left the ticket open since it was never completed to the satisfaction of the Library,

**Comment by patriciahswe** [comment]
@cam156 Circling back around to this . . . I see what's in the GDoc. This information would be fine for a report emailed on a weekly basis. Is that possible?

**Comment by carolyncole** [comment]
Need to change the cron job to deliver_weekly_stats instead of daily

**Comment by awead** [comment]
Fixed in d5b31446ba7f3a95805b5636fa458290865cef44

**Comment by carolyncole** [comment]
Recipients  for the weekly email can be added to umg/up.its.sas.scholarsphere-email at https://umg.its.psu.edu/listgroups.cgi
