### ISSUE TITLE
Word Cloud links have trailing spaces

### ISSUE THREAD

**Issue by nty5001** [psu-libraries/scholarsphere-3#189]
Just a small cosmetic issue. Word cloud items have trailing spaces or some type of padding afterwards to make them appear separated from one another. Only issue is that when hovering the cursor over them, the hyperlink underline shows in the trailing space

**Comment by mtribone** [comment]
It appears that there is an em space hard coded inside the hyperlink?
![screen shot 2016-01-08 at 9 16 02 am](https://cloud.githubusercontent.com/assets/4163828/12199749/9a60472e-b5e8-11e5-85b3-4ad566041c9a.png)

**Comment by carolyncole** [comment]
Word Cloud has been removed.
