### ISSUE TITLE
Image preview extends to far right of div column

### ISSUE THREAD

**Issue by nty5001** [psu-libraries/scholarsphere-3#194]
The white space beside preview images in the div column is clickable, which could mistakenly cause misclicks/open the file for users who are just trying to focus on the window's empty area for scrolling or whatever their purpose.

http://screencast.com/t/48Se1z1QnTH

**Comment by carolyncole** [comment]
@mtribone Any ideas on this one?

**Comment by mtribone** [comment]
Hmmmm...the img-responsive class should make the image fill the space. I'll look at it when I get back.

**Comment by mtribone** [comment]
Interesting. max-width: 100% limits to the parent element but may be restricting size based on aspect ratio? Seems like it stops at a certain width based on the Bootstrap columns? It doesn't work at all in QA, but works to a point in production.

setting img-responsive to use width: 100% seems to fix the issue.

**Comment by mtribone** [comment]
![screen shot 2015-10-01 at 9 55 50 am](https://cloud.githubusercontent.com/assets/4163828/10222562/b0e1c41e-6822-11e5-97f4-6fadfc99d52e.png)

**Comment by mtribone** [comment]
![screen shot 2015-10-01 at 9 57 46 am](https://cloud.githubusercontent.com/assets/4163828/10222599/eb5d8358-6822-11e5-984e-176942fad6d0.png)

**Comment by jcoyne** [comment]
Doesn't `width: 100%` screw up the aspect ratio?

**Comment by jcoyne** [comment]
Uh, nope, looks like it gets taller too.

**Comment by mtribone** [comment]
@jcoyne Yeah it still inherits the height from the original declaration. However, it looks like it is just a Chrome issue with bootstrap-sass-3.3.5.1?

https://github.com/projecthydra/sufia/issues/1335

**Comment by mtribone** [comment]
This solution pixellates the image and is not a desired outcome.

**Comment by mtribone** [comment]
display: inline-block

**Comment by awead** [comment]
Fixed in projecthydra/sufia#1337. Verify, and backport to Sufia 6 if necessary.

**Comment by awead** [comment]
Fixed in b74804dd75cf4cc78397a123fc86764212c1027f
