### ISSUE TITLE
File transfer comments do not appear for sender/recipient

### ISSUE THREAD

**Issue by nty5001** [psu-libraries/scholarsphere-3#196]
When transferring ownership of a file to someone else, the comments entered do not appear for either the sender or recipient.

Senders see a listing of transfers sent on the subsequent screen, but Comments section is empty.
Recipients do not see comments anywhere.

**Comment by carolyncole** [comment]
Confirmed this is still occuring

**Comment by nrm149** [comment]
PSUSprint01

**Comment by carolyncole** [comment]
This appears to be fixed in Sufia 7.2.ish branch that @awead is working on.  It is working is sufia master and I can not find any overrides in ScholarSphere that would prevent this from working. Will  recheck and close one ScholarSphere is based on 7.2
