### ISSUE TITLE
Send a single file to share notify

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#201]
Generate a service or something, that given a GenericFile it could connect with share and push the proper json to share.  See #188 for related story.  relies on #200 for the correct json output.

The following steps will need to be performed for thsi ticket to be completed
- Connect and Authorize with Share Notify, includes #209 
- call to filtering mechanism see #205 
- Send FIle (handle any errors gracefully)
- Process results to save share ID
- call to logging see #206

**Comment by cam156** [comment]
How are we authorizing to share. We have authorization tokens.

**Comment by cam156** [comment]
Filter for only public files

**Comment by cam156** [comment]
Filter for only public files, and the correct resource type.
log to the activity stream that a file was shared.

**Comment by cam156** [comment]
Handle gracefully existing files in share.

**Comment by carolyncole** [comment]
Created a file to test against. https://github.com/psu-stewardship/scholarsphere/blob/develop/spec/fixtures/share.json

**Comment by carolyncole** [comment]
I have done some testing with the staging api.  It seems if you post the same file twice you will get a second file.  https://staging.osf.io/api/v1/share/data

I ran the command below twice and got two records in the data

```
curl https://staging.osf.io/api/v1/share/data/ -H 'Authorization: Token tokentokentoken' -H "Content-Type: application/json" -X POST -d "@spec/fixtures/share.json" 
```

![screen shot 2015-10-09 at 7 36 38 am](https://cloud.githubusercontent.com/assets/1599081/10392798/8e201eb2-6e58-11e5-9590-d4993b408139.png)

**Comment by carolyncole** [comment]
We have determined that we should store the id that is returned by share when we send the single file.

**Comment by awead** [comment]
Is it necessary to store it in Fedora? What about a db table?

**Comment by carolyncole** [comment]
@awead as discussed in the refactoring session this ticket is requiring the data to be stored.  There is no specification on where it need to be stored.  I would like for there to be a method on the GenericFile to retrieve the ID no matter how it is stored.
