### ISSUE TITLE
Implement Push notification of Existing Files

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#203]
Implement a rake task that can be used to send notifications to share of files already existing in the system.  See #188 for resource types.  Use code created by #201 to send the data for each file.

**Comment by cam156** [comment]
Handle gracefully existing files in share.

**Comment by carolyncole** [comment]
for every file in the system send it to the share service.

**Comment by carolyncole** [comment]
Is there a limit for sending information to share.
Is there a batch request?
