### ISSUE TITLE
Error during uploading of GenericFIles from My Computer

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#208]
When I upload a set of files larger than 10 via my computer
I start seeing some of the files error during the upload

**Production**
<img width="1134" alt="screen shot 2015-10-21 at 9 43 24 am" src="https://cloud.githubusercontent.com/assets/1599081/10638301/46e33050-77d8-11e5-9fcd-fbe00378d0b2.png">

**Staging**
<img width="974" alt="screen shot 2015-10-21 at 9 45 56 am" src="https://cloud.githubusercontent.com/assets/1599081/10638350/8d8e1308-77d8-11e5-8dee-87c27fc5071e.png">

I am not seeing any error messages in the log files on staging.  
In production I see:

```
2015-10-21 09:35:48 -0400 (3527) Rendering 404 page due to exception: #<ActiveFedora::ObjectNotFoundError: Object 5712mt52v not found in solr> - ["/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.2.0/gems/active-fedora-9.4.
```

```
2015-10-21 08:23:02 -0400 (3548) GenericFilesController::create rescued Ldp::Gone
```

**Comment by awead** [comment]
One idea for the cause was a change in solr configuration from 4.0 to 4.10. The solrconfig.xml in this repo is different than the one used in production/qa/staging. We could explore that and copy the repo config to one of the servers to see if that stops the problem from occurring.

**Comment by awead** [comment]
@cam156 was this due to the minting of existing noids?
