### ISSUE TITLE
Enhance upload page / form to include question about large file deposit

### ISSUE THREAD

**Issue by patriciahswe** [psu-libraries/scholarsphere-3#212]
On the upload page, include a note that asks, "Need to upload a file larger than 1.9 GBs? Click here to contact us for support," where "here" is a link to the ScholarSphere Contact page.

**Comment by mtribone** [comment]
Do we want to have them use the cloud provider service? Or is this a step towards mediated deposit?

**Comment by mtribone** [comment]
Also "Click here" isn't great for accessibility because it doesn't provide any context for the user. Just linking "contact us for support" would be alright, but perhaps "upload a file larger than 1.9 GB" would be better.

**Comment by patriciahswe** [comment]
Good point about "Click here" - however it needs to be worded to meet accessibility standards is fine with me. E.g., "Need to upload a file larger than 1.9 GB? Contact us for support."

The reason why this has come up is because the cloud services still aren't great at getting files larger than a couple of GBs into ScholarSphere, but we don't want to turn away people or have them give up. Also, Karen Estlund is interested in knowing what the demand is. Having such a message on the upload page and seeing what the uptake is would inform prioritization for this for future roadmaps.

Should I write a better user story?

**Comment by mtribone** [comment]
Nope. I just needed a little background to help me make some design decisions. Good point about the cloud providers!

**Comment by mtribone** [comment]
Working on making the restrictions more visible and a two-column layout. The other message needs a little more visual punch, but am working on it.

<img width="1043" alt="screen shot 2015-12-08 at 2 28 03 pm" src="https://cloud.githubusercontent.com/assets/4163828/11665994/2f649396-9db8-11e5-8a81-144aa4dc6a8f.png">

**Comment by patriciahswe** [comment]
Looking good! Do we want to add the max of 1.9GB when uploading via Dropbox and Box? Or will that be noted in the tab for the cloud services? (Or maybe we're removing the cloud services tab?)

Glad you're working on a visual punch to the message on the right. Thanks, Michael!

**Comment by mtribone** [comment]
I think the 1.9GB max should be on the cloud providers tab to avoid possible confusion. I'm not quite sure why I don't have it locally, but will double check my local build.

**Comment by carolyncole** [comment]
@mtribone The maximum upload size for box is 5GB, so 1GB.
Wording for list from service team:
Individual size 500MB 
Up to 100 files and totaling less than 1G in size

`<link>Need to upload a larger file? Contact us for support</link>`

**Comment by mtribone** [comment]
I've moved the "larger file" statement to the bottom of the maximum restrictions because a) it is more noticeable inline with the text and b) the html is in a place where it is getting reused on both my computer and cloud. I will work on a little styling.

<img width="1060" alt="screen shot 2015-12-11 at 10 23 24 am" src="https://cloud.githubusercontent.com/assets/4163828/11747452/4d5d1d42-9ff1-11e5-919d-c51bec522b33.png">

**Comment by awead** [comment]
@mtribone can this be closed now?

**Comment by mtribone** [comment]
I defer to @patriciahswe to double check if it meets her requirements.

**Comment by awead** [comment]
Here's how it look on QA: https://scholarsphere-qa.dlt.psu.edu/files/new
@patriciahswe can you give the :ok: and we'll get this out for the 2.5 release in two weeks.

**Comment by patriciahswe** [comment]
Sorry, Adam and Michael! Was away at a conference until Tuesday and am still catching up. Thanks for addressing - I think it looks great!
