### ISSUE TITLE
Deposits and downloads of large file directories / hierarchies

### ISSUE THREAD

**Issue by patriciahswe** [psu-libraries/scholarsphere-3#213]
Enable deposits of large file directories that maintain the file relationships (hierarchy) when uploaded and accessed (downloaded, so that files are downloaded together, not singly).

**Comment by patriciahswe** [comment]
Hey Rob: If you want to get together to talk about user stories for this, just let me know.

**Comment by olendorf** [comment]
Wow, I didn't realize i was assigned this. I know we have been working on this. Where do we stand on this ticket?

**Comment by carolyncole** [comment]
Duplicate of #572
