### ISSUE TITLE
Documentation missing link

### ISSUE THREAD

**Issue by nty5001** [psu-libraries/scholarsphere-3#215]
The "How to Create a Collection in ScholarSphere" documentation looks like it should include a link in step #4, but it doesn't have a destination.

https://scholarsphere.psu.edu/collection.pdf

**Comment by patriciahswe** [comment]
Thanks for catching that! I'll fix that link and upload a new version of the PDF.

**Comment by carolyncole** [comment]
Likely need new documentation for creating collections in PCDM ScholarSphere

**Comment by carolyncole** [comment]
#337 Duplicates the above comment closing this link
