### ISSUE TITLE
Word cloud display

### ISSUE THREAD

**Issue by nty5001** [psu-libraries/scholarsphere-3#216]
The word cloud on the home page seems to have lost much of the style that makes it a world cloud display. Its difficult to put into words, just that now it seems to be regular font with only small differences in font size.

It may be that the QA space tags don't have enough of a bank to draw from, or there may be an issue with the feature.

**Comment by awead** [comment]
ping @mtribone I hear he loves word clouds. :cloud: :cloud: :cloud: :cloud: :cloud: :cloud: :cloud: :cloud:

**Comment by mtribone** [comment]
@awead :+1:

**Comment by mtribone** [comment]
@nty5001 I'm guessing that the differences are small and that is why the word cloud seems to have lost its word cloudness. I'll take a look at QA.

**Comment by nty5001** [comment]
Here's a screen
http://screencast.com/t/XfxTmkdq2ShD

**Comment by mtribone** [comment]
I believe that this is just a symptom of the amount and frequency of keywords in QA. It's a little better in production. Can we close this issue?
