### ISSUE TITLE
Facet links from "More" modals under My Highlights goes to My Files

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#236]
With more than 5 keyword terms, click "more Keywords" from the keyword facet. In the modal, all links to the additional facets are going to `/dashboard/files` as opposed to `/dashboard/highlights`.

**Comment by awead** [comment]
This is also occurring with the _Files Shared with Me_ and was tested with the Creator facet, so it seems to be happening regardless of the facet.

**Comment by carolyncole** [comment]
This should be fixed in sufia.  Looks like the path is always set to works instead of using the current dashboard action.

**Comment by awead** [comment]
@cam156 I have another idea... You can only highlight 5 works. It doesn't seem necessary to facet on only 5 items. What if we just removed the tab altogether? Users would see their highlighted works on the profile. @mtribone  @olendorf thoughts?

**Comment by mtribone** [comment]
@awead Highlighted works have always been a bit of a mystery to me. I'm unsure of how many people use this feature. I'm certainly good with removing it from the works, collections, shared tab.

**Comment by mtribone** [comment]
Since September, the highlights have been accessed 13 times and the time on page was 6 seconds.


![screen shot 2017-01-24 at 1 41 23 pm](https://cloud.githubusercontent.com/assets/4163828/22261434/f20847ae-e23a-11e6-9a47-d3af41769b75.png)

**Comment by carolyncole** [comment]
@awead Removing My Highlights would not fix this bug as it is also a problem on the Works shared with my tab (and I believe the my Collection tab).

That said maybe we should open a new ticket for removing the My Highlights tab.  I'm not certain it is useful.

**Comment by awead** [comment]
@cam156 I've fixed it. It's not a problem with collections.
