### ISSUE TITLE
Uploading new versions

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#238]
This is not always reproduceable, but I'm seeing issues with uploading new versions. Sometimes the derivative generation doesn't create a new thumbnail, and downloading the file gives you the old version and not the newly updated one.

**Comment by carolyncole** [comment]
Verify that this is still an issue.  If it is an issue create a ticket with details on reproduction.

**Comment by awead** [comment]
I've confirmed this is problem and created a ticket: https://github.com/psu-stewardship/scholarsphere/issues/537
