### ISSUE TITLE
sprocket-rails 3.0.0 wants images to be precompiled

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#239]
With the gem sprocket-rails 3.0.0, we're getting errors:

```
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( missing_thumb.png )` to
`config/initializers/assets.rb` and restart your server
```

even though we've configured all images to be precompiled:
https://github.com/psu-stewardship/scholarsphere/blob/develop/config/environments/production.rb#L81

**Comment by carolyncole** [comment]
Seems to be in the path now.
