### ISSUE TITLE
Migrate multi-valued rights fields to single-valued ones

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#242]
See #183. We can add multiple licenses, but maybe we shouldn't?

**Comment by carolyncole** [comment]
We should have only one at the work level.  In ScholarSphere we hide the second/multiple rights and display as single value.

**Comment by carolyncole** [comment]
override the form for this metadata field CurationConcerns workf form https://github.com/psu-stewardship/scholarsphere/blob/develop/app/forms/curation_concerns/generic_work_form.rb
