### ISSUE TITLE
Thumbnails size

### ISSUE THREAD

**Issue by hectorcorrea** [psu-libraries/scholarsphere-3#244]
For some of our documents we are producing thumbnails that are way too big to be used as thumbnail images. See file https://scholarsphere.psu.edu/files/x346f3538 for an example. In this file the thumbnail image is 793x1103. This causes two problems. 
1. A large thumbnail messes the layout of the page in FireFox (see attachment below)
2. We are downloading a whole lot more information from Fedora and sending it to the user for no good reason. This might also be related with the issues that we have seen with web crawlers.

![screen shot 2016-02-03 at 8 46 20 am](https://cloud.githubusercontent.com/assets/568286/12784348/c536d096-ca54-11e5-9ea9-db09e7d0a3c8.png)

**Comment by mtribone** [comment]
Are thumbnails still being created at these sizes? Or was this during a certain period of time? Are we able to search thumbnail sizes in Fedora or Solr? Does Imagemagick handle this?

**Comment by hectorcorrea** [comment]
@mtribone that was a really good idea. I re-uploaded the file in QA to see if we generated a smaller thumbnail but no. Unfortunately we are producing a gigantic thumbnail. However, in QA the thumbnail was resized correctly. See the two images below.

QA - resized correctly
![screen shot 2016-02-03 at 2 06 16 pm](https://cloud.githubusercontent.com/assets/568286/12793627/7b668b7a-ca7f-11e5-8774-bde6453bd8b9.png)

Production - what a mess 
![screen shot 2016-02-03 at 2 05 59 pm](https://cloud.githubusercontent.com/assets/568286/12793644/8a089ac4-ca7f-11e5-9155-7be4c2591035.png)

**Comment by carolyncole** [comment]
Verify that Thumbnails do not go over their display area on Firefox, Chrome, Safari, & IE
Create tickets for any issues

**Comment by awead** [comment]
This should be fixed in 82f28bb56bf6726bd8e0fd8fb07ffeea68f3a458

**Comment by carolyncole** [comment]
Yes this can be closed.  I uploaded an excel file and a docx and they both had small thumbnails
