### ISSUE TITLE
Remove report from data types being sent to share notify

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#245]
Question What do we want to do about ones already sent to share?  Does share have an api fro removing items.

Can we delete an item from share when it is deleted from scholarsphere

**Comment by awead** [comment]
@cam156 There's no mention of such a feature in the API docs, so I would conclude that there is no such feature. However, it seems like there should be a delete feature. Probably something we need to contact them about.

**Comment by patriciahswe** [comment]
@cam156  There was a message from Erin via email confirming ScholarSphere's integration. Have you already been in touch, or should I follow up with Erin, copying you, Carolyn? Let me know.

**Comment by carolyncole** [comment]
@patriciahswe I have not contacted Erin yet.  If you would like to follow up you can, or I will.

**Comment by carolyncole** [comment]
@patriciahswe I just sent out the email.  Feel free to follow up using the thread.

**Comment by patriciahswe** [comment]
@cam156 Here is a list of mostly CVs that I generated: https://scholarsphere.psu.edu/catalog?f%5Bresource_type_sim%5D%5B%5D=Report&q=lang+vitae.

In the list, it's **1 through 56** that are actually CVs. These need to be made private ASAP, and these are the ones that need to be deleted from SHARE. All of them carry the resource types "project" and "report." 

If SHARE Notify could delete these items, that would be great. Let me know if you need anything else.

**Comment by patriciahswe** [comment]
@cam156 Btw, items 57 through 63 (or through 61 if resource type "project" or "report" is chosen), are **not** CVs. Items 57 through 63 are files that may remain public in ScholarSphere.

**Comment by carolyncole** [comment]
@patriciahswe The files have been made private.  I also sent a list of URLs to the share folks to see if they can remove them.

**Comment by patriciahswe** [comment]
@cam156 Many thanks!

**Comment by awead** [comment]
SHARE now has a delete feature in their API. We just need to make use of it - https://osf.io/dajtq/wiki/Push%20API/
