### ISSUE TITLE
Message for the upload page on ScholarSphere's Content Policy

### ISSUE THREAD

**Issue by patriciahswe** [psu-libraries/scholarsphere-3#246]
@mtribone We need a message on the upload page that gives the gist of the following: 

"If your file contains personal signatures or personally identifiable information (PII), such as security numbers, it is not permitted in ScholarSphere. If your file is a résumé or a CV, it is also not permitted in ScholarSphere. If these types of files are deposited, they will be removed from ScholarSphere. Please review [ScholarSphere’s Content Policy](https://scholarsphere.psu.edu/about#Content_Policy) to make sure you are not depositing materials that are sensitive."

Maybe we could take a checklist approach? Like:

Does your file contain, or is your file, any of the following:
- Personal signature
- Social security number
- Résumé or CV
- Personal health information

If so, then the file is not allowed in ScholarSphere. If deposited, the file will be removed, and the depositor of the file will be notified of its removal.

Too much?

**Comment by mtribone** [comment]
Hmmm...we could put the check list in the right column of the upload page next to the restrictions. However, it feels like the interface is getting a little wordy.

**Comment by patriciahswe** [comment]
I have the same concern. If you have suggestions for less wordiness, I'd welcome them! It's just that in the last six months or so, we've had deposits of files that are either sensitive in some way or inappropriate content for ScholarSphere. Maybe a link back to the content policy, with bullets identifying the types of content we don't want in ScholarSphere, might help.

**Comment by mtribone** [comment]
@patriciahswe yeah. Perhaps that might be a good first step. Would be good to get users feedback on what they "see" on screen when they upload files. Or we could pop up a modal when they select upload that contains a picture of kittens and the text overlay says,"A kitten dies every time you upload PII."

**Comment by patriciahswe** [comment]
@mtribone Oooh, yes, please! 

Another thing I'm thinking about: perhaps have another checkbox underneath the one for the deposit agreement that says "By clicking this box I am verifying that my file contains no personal signatures, or personally identifiable information, and it is not a résumé or CV." Maybe that's too specific.

In the meantime, I'll work on making the content policy more readable.

**Comment by mtribone** [comment]
<img width="1023" alt="screen shot 2016-02-18 at 12 58 46 pm" src="https://cloud.githubusercontent.com/assets/4163828/13152898/6b8151d8-d63f-11e5-883d-0b5f5c6907dc.png">

Trying to keep things aligned left and not off to the side, so that a user gets that left edge all the way down to the buttons. _shrugs_ I'd like to know if the messaging at the top is effective or seen by users in general.
