### ISSUE TITLE
Collection containing items has zero size and item count

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#262]
I'm not entirely sure how this happened.  When I created the collection the size was correct.
After running through a few more test the size and file count is now zero

![screen shot 2016-02-24 at 9 18 42 am](https://cloud.githubusercontent.com/assets/1599081/13287973/b72a116e-dad7-11e5-8398-f700341f2a96.png)

**Comment by mtribone** [comment]
Tested this morning and is working

![screen shot 2016-03-02 at 10 53 47 am](https://cloud.githubusercontent.com/assets/4163828/13465797/26981428-e065-11e5-8dc6-6521ee04889b.png)
