### ISSUE TITLE
Batch Edit Permissions is showing open access even though the files are all private

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#263]
All files are private, but when I bring up the form is shows open access.

![screen shot 2016-02-24 at 9 31 09 am](https://cloud.githubusercontent.com/assets/1599081/13288313/66faa2a6-dad9-11e5-88b5-f3105aaacb45.png)

The form does change the access level, but it still shows as open access when the form is brought up.

**Comment by carolyncole** [comment]
Let's make sure this works with the new PCDM version of things...  When you edit the permissions the editing does work now.

**Comment by carolyncole** [comment]
related to sufia/#2450  We should verify this is fixed by that ticket

**Comment by awead** [comment]
Verified.
