### ISSUE TITLE
Undefined method `fetch' for Net::LDAP::Entry

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#264]
Seeing this error a lot in the resque failed queue. Reloading one job from the queue shows: `#<ShareNotifyJob:0x007fdc95da1168 @id=\"8623j753j\">` which is for this file:

https://scholarsphere.psu.edu/files/8623j753j

Which should have been sent to ShareNotify, but has not because of the fetch error.

**Comment by awead** [comment]
The error occurs multiple times, but it's for the same file, so this may be one of only a few affected files.

**Comment by awead** [comment]
The problem is "Lrm4" is the creator and that's not getting resolved to "Linda Musser" and her email. Perhaps an easier fix is for @patriciahswe to contact her and have her update the creator field?

**Comment by carolyncole** [comment]
Tested this file against share and it send correctly
