### ISSUE TITLE
Return 401 instead of redirecting

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#274]
The GenericWorksController will now return a 401 for unauthorized access, instead of redirecting and using a flash message. We could adopt the new behavior, but will require adding back the new behaviors. On the other hand, returning 401 and showing a page with more explanations might be a better way to go.

See projecthydra/sufia#1829

**Comment by hectorcorrea** [comment]
:+1: for proper HTTP status codes!

**Comment by awead** [comment]
I know, right? Because then we'd actually get the 401 instead of the 302...
