### ISSUE TITLE
CSS overhaul

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#279]
Our CSS overrides and structure should be reviewed and overhauled as needed to account for the new changes in Sufia 7.

**Comment by carolyncole** [comment]
Bootstrap column resize & general fitness of the css for ScholarSphere.  Related to #283

**Comment by carolyncole** [comment]
write new ccc to make ScholarSphere look pretty.

**Comment by mtribone** [comment]
http://csswizardry.com/2016/08/refactoring-css-the-three-i-s/

**Comment by mtribone** [comment]
- [x] Site Review
- [ ] Refactor Style to resemble Bootstrap and rely on classes
- [x] Header, Nav, Footer
- [x] Dashboard
- [x] Home page
- [x] My Works, Collections, etc. listings
- [ ] Work - New/Edit 
- [ ] Collection - New/Edit
- [ ] File Sets
- [ ] Profile - View/Edit

**Comment by mtribone** [comment]
http://codeguide.co/
