### ISSUE TITLE
Header, Home Page, and General Layout Tweaks and Fixes

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#283]
I've cut out most of Scholarsphere's views because they didn't align with Sufia anymore. This has caused only a few issues, fortunately. We'll need to fix:
- system statistics link display dashboard
- logo
- spec/views/dashboard/index.html.erb_spec.rb
- spec/views/users/show.html.erb_spec.rb

**Comment by carolyncole** [comment]
Make the home page header look nice with CSS updates.
Put back in our image, and make ScholarSphere Display.

**Comment by carolyncole** [comment]
<img width="1288" alt="screen shot 2016-09-28 at 9 51 53 am" src="https://cloud.githubusercontent.com/assets/1599081/18916100/3db65fba-8561-11e6-9d6f-0d204796bb9d.png">

**Comment by carolyncole** [comment]
This also includes the toolbar staying below PSU logo

**Comment by nrm149** [comment]
PSUSprint03

**Comment by mtribone** [comment]
@olendorf @cam156 What sort of tweaks were we thinking for this round of the home page?

![screen shot 2016-10-24 at 3 44 07 pm](https://cloud.githubusercontent.com/assets/4163828/19661224/e12de038-9a00-11e6-9e81-0160aef2e55d.png)

**Comment by carolyncole** [comment]
@mtribone Wow that looks so much better!  I'm thinking that should be enough for now.  We can ticket individual items later.

**Comment by mtribone** [comment]
Need to make sure that the templates replace "container" with "container-fluid"
