### ISSUE TITLE
Works to include Collections that they belong to

### ISSUE THREAD

**Issue by hectorcorrea** [psu-libraries/scholarsphere-3#294]
In ScholarSphere 2.x we display what Collections that a File belongs to in the Dashboard/My Files tab:

![screen shot 2016-05-12 at 11 20 48 am](https://cloud.githubusercontent.com/assets/568286/15220212/aa804eca-1834-11e6-8347-7ccab28cc147.png)

However, Sufia 7 does not support this functionality out of the box. This ticket is here to document the missing functionality in case we want to re-add it. Below is how works listing is displayed in ScholarSphere with Sufia 7.

![screen shot 2016-05-12 at 11 24 46 am](https://cloud.githubusercontent.com/assets/568286/15220236/beb00f0c-1834-11e6-9bd4-f6091db850e6.png)

**Comment by mtribone** [comment]
@olendorf Here is the view for adding the title of the collection that a work is a part of in the works listing. This follows the previous pattern from SS 2.0.

![screen shot 2018-04-02 at 9 10 02 am](https://user-images.githubusercontent.com/4163828/38197419-f9ea4038-3655-11e8-9da5-7c00b4d45cf2.png)


Another option would be to add the collection data to the additional metadata via the disclosure triangle.

![part_of](https://user-images.githubusercontent.com/4163828/38197744-cef6efb4-3657-11e8-8d75-5c0689577b2c.png)

**Comment by mtribone** [comment]
Earlier code that renders collections links via a helper. May be useful?
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/views/my/_index_partials/_list_works.html.erb#L28

https://github.com/samvera/sufia/blob/master/app/helpers/sufia/collections_helper.rb

**Comment by olendorf** [comment]
@mtribone a bit confused still. Can you show me tomorrow and standup quick?
