### ISSUE TITLE
Right modal is no longer used

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#314]
The rights modal, which shows additional information about which license to choose, has been removed in Sufia 7. We're still testing for it, so do we follow Sufia or roll our own?

**Comment by awead** [comment]
There's a ticket in Sufia to replace it, but it hasn't been picked up yet: projecthydra/sufia#2007

**Comment by mtribone** [comment]
We'll need to handle this in ScholarSphere ourselves with an additional documentation page that helps users understand the choices. Thinking of using the suggestions https://github.com/projecthydra/sufia/issues/2007#issuecomment-218247337 and https://github.com/projecthydra/sufia/issues/2007#issuecomment-218239637

**Comment by carolyncole** [comment]
Duplicate of  #375
