### ISSUE TITLE
Remove DirectoryController?

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#316]
It's unclear how or if the DirectoryController is being used. It was removed in Sufia 7, but still remains in Scholarsphere.

**Comment by carolyncole** [comment]
Remove it anything see what if anything breaks. Document it better if we leave it in there.

**Comment by carolyncole** [comment]
Looks like the UsersController is the new controller for user information.  The DirectoryContorller used to supply groups and users for permissions.
