### ISSUE TITLE
Update to latest Penn State brand guidelines

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#328]
Strategic Communications has asked our IT Comms to provide us with the latest logo and such. The guidelines are here: http://visualidentity.psu.edu/standard/brand-architecture-tier-3-institutes-and-centers

I have the favicon and new logo.

**Comment by mtribone** [comment]
Repurposing this ticket for Sufia 7 and ScholarSphere 3 work, since SS Sufia 6 in production is up-to-date.

![screen shot 2016-08-31 at 2 40 53 pm](https://cloud.githubusercontent.com/assets/4163828/18141798/f7c96832-6f88-11e6-9bad-dd72542e04c3.png)

**Comment by carolyncole** [comment]
Will be fixed by #283
