### ISSUE TITLE
Penn State Mark, ScholarSphere, Column Tweaks (400px to 768px)

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#330]
I think that there might be some room for improvement with the number of columns and size of the ScholarSphere text, since we don't have a full user bar with the full name until 768px.

Challenges
1. col-xs  is < 768 pixels
2. col-sm is >= 768 pixels

Possible solutions
1. Reduce size of Penn State mark within a certain range (400...600)
2. Increase size of ScholarSphere within a certain range (500...700)

Extras
1. Text color for ScholarSphere
2. Letterspacing

![screen shot 2016-08-04 at 9 23 27 am](https://cloud.githubusercontent.com/assets/4163828/17403342/474e0558-5a25-11e6-8127-0c7808346b1a.png)

![screen shot 2016-08-04 at 9 12 47 am](https://cloud.githubusercontent.com/assets/4163828/17403249/eb4b3258-5a24-11e6-92a0-05e568db1a8a.png)

**Comment by carolyncole** [comment]
#328 will fix this
