### ISSUE TITLE
Need to make certain the autocompletes match up with the new QA format

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#331]
Currently our database is loaded with the old format for languages and subjects. With Sufia 7.0 we need to use the new table format in questioning authority.

see: https://github.com/projecthydra-labs/questioning_authority/pull/107

This is done when I can add additional metadata on a new work or and editing a work and get an autocomplete for the subject and language fields.

**Comment by nrm149** [comment]
PSUSprint03

**Comment by carolyncole** [comment]
Need to load the data on the servers from Library of congress via Cap

**Comment by awead** [comment]
Blocked by https://github.com/projecthydra-labs/questioning_authority/issues/113

Waiting on 0.10.2 release address the issue.

**Comment by awead** [comment]
I've written up some documentation here https://github.com/psu-stewardship/scholarsphere/wiki/Updating-Authorities

Capistrano might not be the best solution because it only needs to be run on selected servers, and not very often. It also takes a looong time for subjects.
