### ISSUE TITLE
Need to be certain the Autocomplete for location works

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#332]
Need to be certain the autocomplete for location is configured properly.  It is currently not working on my local server or on QA so the configuration must have changes in Sufia 7.

This is complete when upload a new work or edit an existing work and get an autocomplete on the Location field

**Comment by carolyncole** [comment]
Looks like the routes are missing:

2016-08-08 09:26:08 -0400 (70552) Started GET "/authorities/search/geonames?q=locat" for ::1 at 2016-08-08 09:26:08 -0400
2016-08-08 09:26:08 -0400 (70552) 
ActionController::RoutingError (No route matches [GET] "/authorities/search/geonames"):
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in`call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in`call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in`call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in`call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in`call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in`call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in`call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  railties (4.2.6) lib/rails/railtie.rb:194:in`public_send'
  railties (4.2.6) lib/rails/railtie.rb:194:in `method_missing'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in`call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  unicorn (5.1.0) lib/unicorn/http_server.rb:562:in`process_client'
  unicorn (5.1.0) lib/unicorn/http_server.rb:658:in `worker_loop'
  unicorn (5.1.0) lib/unicorn/http_server.rb:508:in`spawn_missing_workers'
  unicorn (5.1.0) lib/unicorn/http_server.rb:132:in `start'
  unicorn-rails (2.2.0) lib/unicorn_rails.rb:33:in`run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.6) lib/rails/commands/server.rb:80:in`start'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:75:in`tap'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.6) lib/rails/commands/commands_tasks.rb:39:in`run_command!'
  railties (4.2.6) lib/rails/commands.rb:17:in `<top (required)>'
  railties (4.2.6) lib/rails/app_rails_loader.rb:45:in`require'
  railties (4.2.6) lib/rails/app_rails_loader.rb:45:in `block in exec_app_rails'
  railties (4.2.6) lib/rails/app_rails_loader.rb:34:in`loop'
  railties (4.2.6) lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
  railties (4.2.6) lib/rails/cli.rb:5:in`<top (required)>'
  railties (4.2.6) bin/rails:9:in `require'
  railties (4.2.6) bin/rails:9:in`<top (required)>'
  /Users/cam156/.rbenv/versions/2.3.1/bin/rails:23:in `load'
  /Users/cam156/.rbenv/versions/2.3.1/bin/rails:23:in`<top (required)>'
  bundler (1.12.3) lib/bundler/cli/exec.rb:63:in `load'
  bundler (1.12.3) lib/bundler/cli/exec.rb:63:in`kernel_load'
  bundler (1.12.3) lib/bundler/cli/exec.rb:24:in `run'
  bundler (1.12.3) lib/bundler/cli.rb:304:in`exec'
  bundler (1.12.3) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  bundler (1.12.3) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in`invoke_command'
  bundler (1.12.3) lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  bundler (1.12.3) lib/bundler/vendor/thor/lib/thor/base.rb:440:in`start'
  bundler (1.12.3) lib/bundler/cli.rb:11:in `start'
  bundler (1.12.3) exe/bundle:27:in`block in <top (required)>'
  bundler (1.12.3) lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
  bundler (1.12.3) exe/bundle:19:in`<top (required)>'
  /Users/cam156/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
  /Users/cam156/.rbenv/versions/2.3.1/bin/bundle:23:in`<main>'

**Comment by awead** [comment]
I wonder if we need to add the QuestioningAuthority gem routes to routes.rb, although I though Sufia already handled that for us.

**Comment by awead** [comment]
`mount Qa::Engine => '/authorities'` is in the internal_app's routes.rb

**Comment by carolyncole** [comment]
Yep, I think we have to mount the routes.  That may be the only issue here...
