### ISSUE TITLE
Google Analytic setDomainName

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#334]
Sufia now includes a _setDomainName for google analytics.  It is currently being set to none.  What is it and what should we be setting it to?

**Comment by awead** [comment]
It's used to track statistics from multiple domains. Since we're not doing this, setting is to "none" is considered the traditional approach.
 
See:
 https://developers.google.com/analytics/devguides/collection/gajs/methods/gaJSApiDomainDirectory#_gat.GA_Tracker_._setDomainName
