### ISSUE TITLE
The footer is wrong

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#338]
The footer is missing a link to versions
It has the sufia version instead of ScholarSphere
I does not have a link to the UL

![screen shot 2016-08-04 at 2 51 00 pm](https://cloud.githubusercontent.com/assets/1599081/17414301/e304dd00-5a52-11e6-8983-8ae94ce43f49.png)
![screen shot 2016-08-04 at 2 49 29 pm](https://cloud.githubusercontent.com/assets/1599081/17414305/e499d8d2-5a52-11e6-9567-044731cdc724.png)

**Comment by nrm149** [comment]
PSUSprint03
