### ISSUE TITLE
Description is not required for work

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#347]
We need to review the required metadata fields with the libraries.  Description used to be required for a File.  I'm guessing it should still be required for a work.

**Comment by carolyncole** [comment]
We will also need Resource Type to be move up since we are keying off of that for sending information to Share Notify.

**Comment by awead** [comment]
Should be as easy as just overriding the form and adding the fields to the required array.

**Comment by carolyncole** [comment]
Any item required for Google Scholar should be a required item.

**Comment by nrm149** [comment]
PSUSprint03
