### ISSUE TITLE
Creator is no longer defaulted to depositor.

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#349]
Moving this issue from sufia to ScholarSphere.

https://github.com/projecthydra/sufia/issues/2396

@awead I saw you comment, but having the users type in whatever instead of defaulting it gives us worse facets.

What should we be defaulting.  If we do not default the creator should we do so populating from LDAP?

**Comment by awead** [comment]
@cam156 what's the present behavior in production? It looks like you can just type anything now.

I think we could default to a formatted string of what the depositor is, using current user's LDAP response. For example, _Wead, Adam Garner_. If the user needs to change or add users, we still rely on LDAP. However, if we need to allow non-PSU creators or people who aren't in LDAP, we could use some string validation that enforces the LastName, FirstName format and disallow numbers so folks can't use "agw13" or emails as a creator.

Alternatively, we could place non-PSU users in a different field and make creator use LDAP as an authority.

**Comment by carolyncole** [comment]
@awead the default is a formatted depositor string, but you can change it to anything.

![screen shot 2016-08-08 at 2 32 29 pm](https://cloud.githubusercontent.com/assets/1599081/17491300/02dd2752-5d75-11e6-9207-02abddd5e85e.png)

I was just commenting on your comment on the ticket in Sufia that defaulting it was a bad idea.  I think from a PSU perspective defaulting it is better than not.  For other people's perspective I can see that they do not care or even want it.  

What we really need is an email to be added along with the name so we can stop looking it up to send to share...

**Comment by carolyncole** [comment]
The old code that gets the field value can be reused.  This will then need to be plugged into the new actor stack.

**Comment by carolyncole** [comment]
Here is the code that was used to put the name in the correct format

```
    parsed = Namae::Name.parse(current_user.name)
    generic_file = ::GenericFile.new(creator: [parsed.sort_order], title: @batch.generic_files.map(&:label))
```

This will need to be inserted into the form:
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/forms/curation_concerns/generic_work_form.rb#L5
