### ISSUE TITLE
Indexing works

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#352]
When indexing technical metadata and full text from a work, we can either choose a representative FileSet from the work from which to extract the metadata, or exact the metadata from every FileSet (or subset thereof) and add it all to the Work's record in Solr.

**Comment by carolyncole** [comment]
@awead At one point I looked at joining metadata between works and their included FileSets in a solr query.  Would that approach work in this situation.  For some reason I thought Sufia was already doing that.

**Comment by awead** [comment]
Yes, it does and that makes searching work, but we'll still need to pull terms from the fileset for faceting.

**Comment by carolyncole** [comment]
So what terms do we need for faceting? I this only for #350 or are there others you are aware of?

**Comment by awead** [comment]
I think it's just file format. I'm almost done with the pending tests, at least the ones that I have clear solutions for. I can merge that into sufia-7 and that will include the file format fix.
