### ISSUE TITLE
Share Notify integration seems to be broken

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#355]
From what I can tell items are not getting sent to share, and when you delete a work or update permissions it causes errors in the system.  This is related to #344, but it seems the entire integration is not working, not just the delete.  It seems that when work is uploaded there is no trigger to send the file to share.  When the permission changes or the file is deleted an error gets created.

I think our jobs need to be revamped for the new Job running strategy in Sufia.  

![screen shot 2016-08-11 at 7 49 58 am](https://cloud.githubusercontent.com/assets/1599081/17587768/3e5c9752-5f98-11e6-9017-2cea41ee525f.png)

**Comment by awead** [comment]
Ah, looks like those haven't been convert to Active::Job yet.

**Comment by awead** [comment]
I've held off tackling the SHARE stuff because of #277

**Comment by carolyncole** [comment]
@awead I added a comment to #277.  At the very least we should convert the methods to ActiveJob, but I think using the new work url is the best.  I also pinged Rob.

**Comment by nrm149** [comment]
PSUSprint00

**Comment by carolyncole** [comment]
Comment for waffle

**Comment by nrm149** [comment]
PSUSprint00 done
