### ISSUE TITLE
Configure passenger to support X-Sendfile

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#363]
config.action_dispatch.x_sendfile_header = "X-Sendfile" is not working on QA.  It seems like passenger is not configured to server files from disk.

Here is a link to configuring:
https://makandracards.com/makandra/990-speed-up-file-downloads-with-rails-apache-and-x-sendfile

**Comment by carolyncole** [comment]
A link to a public work: https://scholarsphere-qa.dlt.psu.edu/concern/generic_works/h989r3203
A link directly to the thumbnail: https://scholarsphere-qa.dlt.psu.edu/downloads/x633f100h?file=thumbnail

**Comment by carolyncole** [comment]
/opt/heracles/deploy/scholarsphere/releases/20160829130614/tmp/derivatives/x6/33/f1/00/h-thumbnail.jpeg

**Comment by jrpatterson** [comment]
QA and staging have now been prepped for this.  Once your ready I can add the changes to demo and prod.
