### ISSUE TITLE
Acts as following will be removed from sufia

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#365]
The community is planning to remove follower following capabilities from Sufia becuase the gem we are using is no longer being maintained.  The community is discussing the problem here:  https://github.com/tcocca/acts_as_follower/issues/54

We have around 50 users taking advantage of this feature out of 1400 users.  Dean Dewy stands out having 4 followers and 4 people she is following.

Should we plan to maintain the capability ourselves or can this feature be removed.

Here are the users with followers:

```
rb(main):020:0> User.all.each{ |u| puts "#{u.login} #{u.followers.count} #{u.display_name}" if u.followers.count >= 1 }
cam156 2 CAROLYN A COLE
jgm106 1 JEFFREY MINELLI
mjg36 5 MICHAEL JOSEPH GIARLO
dmc186 4 DANIEL M COUGHLIN
mjf25 6 MICHAEL FURLOUGH
pmh22 6 PATRICIA M HSWE
lxf5 4 LINDA C FRIEND
cdc17 3 C DAWN CHILDRESS
mum28 2 MAIREAD MARTIN
sjw31 1 STEPHEN WOODS
jjm38 3 JOHN MEIER
bmg17 6 BENJAMIN MATTHEW GOLDMAN
tlr15 4 THOMAS REINSFELDER
lbg10 5 LISA B GERMAN
sxh36 2 SUSAN HAMBURGER
avh3 1 ANDREA HARRINGTON
cpl2 2 CHRISTOPHER PHILIP LONG
bid1 4 BARBARA IRENE DEWEY
asc17 3 AMANDA SARA CLOSSEN
pag191 1 PATRICIA ANNE GAEL
tdp11 2 TIMOTHY DWIGHT PYATT
mus54 2 MARCEL SALATHE
rah29 2 RUSSELL HALL
txl133 1 TIERNEY LYONS
bal19 3 BERNADETTE LEAR
cjw29 1 CHRISTOPHER JOSEPH WEAVER
lrm4 2 LINDA MUSSER
aws131 1 ALAN WILLIAM SHAY
hap10 1 HENRY ANDREW PISCIOTTA
mlo10 2 MONA LEE OSTROWSKI
mjk46 1 MICHELE JEAN KENNERLY
bxh13 1 BARUCH HALPERN
mat141 1 MICHAEL ANTHONY TRIBONE
jak47 1 JEFFREY ALLEN KNAPP
eyd1 1 ESTHER DELL
ecn1 1 ERIC CHARLES NOVOTNY
dpb11 1 DAVID P BRENNAN
mrf22 2 MATTHEW ROBERT FRANCIS
sgt3 1 SANFORD GRAY THATCHER
mim6 1 MARY FRANCES MCLAUGHLIN
saw4 2 SUSAN ARLENE WARE
agw13 1 ADAM GARNER WEAD
lal29 1 LORI ANN LYSIAK
njm5277 1 NISHANT JAYESH MODI
```

Here are the users who are following others:

```
cam156 2 CAROLYN A COLE
jgm106 1 JEFFREY MINELLI
mjg36 5 MICHAEL JOSEPH GIARLO
dmc186 4 DANIEL M COUGHLIN
mjf25 6 MICHAEL FURLOUGH
pmh22 6 PATRICIA M HSWE
lxf5 4 LINDA C FRIEND
cdc17 3 C DAWN CHILDRESS
mum28 2 MAIREAD MARTIN
sjw31 1 STEPHEN WOODS
jjm38 3 JOHN MEIER
bmg17 6 BENJAMIN MATTHEW GOLDMAN
tlr15 4 THOMAS REINSFELDER
lbg10 5 LISA B GERMAN
sxh36 2 SUSAN HAMBURGER
avh3 1 ANDREA HARRINGTON
cpl2 2 CHRISTOPHER PHILIP LONG
bid1 4 BARBARA IRENE DEWEY
asc17 3 AMANDA SARA CLOSSEN
pag191 1 PATRICIA ANNE GAEL
tdp11 2 TIMOTHY DWIGHT PYATT
mus54 2 MARCEL SALATHE
rah29 2 RUSSELL HALL
txl133 1 TIERNEY LYONS
bal19 3 BERNADETTE LEAR
cjw29 1 CHRISTOPHER JOSEPH WEAVER
lrm4 2 LINDA MUSSER
aws131 1 ALAN WILLIAM SHAY
hap10 1 HENRY ANDREW PISCIOTTA
mlo10 2 MONA LEE OSTROWSKI
mjk46 1 MICHELE JEAN KENNERLY
bxh13 1 BARUCH HALPERN
mat141 1 MICHAEL ANTHONY TRIBONE
jak47 1 JEFFREY ALLEN KNAPP
eyd1 1 ESTHER DELL
ecn1 1 ERIC CHARLES NOVOTNY
dpb11 1 DAVID P BRENNAN
mrf22 2 MATTHEW ROBERT FRANCIS
sgt3 1 SANFORD GRAY THATCHER
mim6 1 MARY FRANCES MCLAUGHLIN
saw4 2 SUSAN ARLENE WARE
agw13 1 ADAM GARNER WEAD
lal29 1 LORI ANN LYSIAK
njm5277 1 NISHANT JAYESH MODI
```

**Comment by mjgiarlo** [comment]
There is a PR in Sufia that would remove this feature, but I'm reluctant to merge it until I hear back from folks about how widely they use the feature.

FWIW, I'm comfortable deferring this decision to y'all at Penn State (esp. since no one else has spoken up in defense of it). If Penn State users don't get much value out of it (given the very low #s for followers/following above), perhaps we should remove it and not take on the additional management burden of the unmaintained `acts_as_follower` gem.

If Penn State does require this feature, we have a few different options:
1. Keep it in Sufia and maintain `acts_as_follower`
2. Move it to ScholarSphere and maintain `acts_as_follower`
3. Extract to new gem and maintain `acts_as_follower`

And, once again, I do defer to y'all, and I will not merge the Sufia PR until we all feel comfortable with a decision.

**Comment by carolyncole** [comment]
@olendorf We need to commit to maintaining the gem if we want to keep this in ScholarSphere.

**Comment by olendorf** [comment]
@cam156  @mjgiarlo  I've emailed dean Dewey, so I'll update with her response.

**Comment by carolyncole** [comment]
The response from Dean Dewey was that she was not using the follow following portion of the software this will be removed in ScholarSphere 3.0
