### ISSUE TITLE
Poster ideas for Hydra Conect

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#366]
What do we want for our poster for Hydra Connect?  I'm assuming we would put ScholarSphere in some form out there.

What do people think? @mtribone @awead @olendorf @DanCoughlin @kestlund

**Comment by mtribone** [comment]
@cam156 and I talked about ideas for the poster today and we're thinking that we could do a PCDM timeline with respect to our goals, contributions and milestones. What do you think?

**Comment by awead** [comment]
I like it. It can give other people an idea about how much work it would take and help them plan accordingly.

**Comment by carolyncole** [comment]
Schedule:
https://docs.google.com/presentation/d/1V7YqpMLi_apKZBkr3gzNw03GV8YPG-N-bkfxDAQR-F4/edit#slide=id.p

**Comment by carolyncole** [comment]
Portland Code4Lib PCDM Meeting February 2015
LCDX PCDM Planning April 2015

**Comment by carolyncole** [comment]
Sufia 7.0 August 2016

**Comment by carolyncole** [comment]
Sufia  & Curation Concerns Design Summer 2015

**Comment by carolyncole** [comment]
ScholarSphere 3.0 Coming Winter 2016/2017

**Comment by carolyncole** [comment]
UI Working Group November 2015 - April 2016

**Comment by carolyncole** [comment]
Penn State PCDM Sprint - Curation Concern Break Out and initial Sufia based on Curation Concerns  May 2015

**Comment by carolyncole** [comment]
- Portland Code4Lib PCDM Meeting February 2015 - Stag
- LCDX PCDM Planning April 2015 - LDCX Logo
- Penn State PCDM Sprint - Curation Concern Break Out and initial Sufia based on Curation Concerns May 2015 ( Mega Sprint - PSU Logo)
- Sufia & Curation Concerns Design and Implementation Summer 2015 - Gob Stopper
- UI Working Group November 2015 - April 2016  ( Use wireframe from group)
- Sufia 7.0 August 2016 (Capture of Sufia Home Page)
- ScholarSphere 3.0 Coming Winter 2016/2017 (Capture of PSU Homepage)

**Comment by DanCoughlin** [comment]
Nov. of 2014 there was also a community meeting around this (called Hydra:Works) that took place in Portland. Giarlo attended this for PSU.

**Comment by mtribone** [comment]
_moves everything down_

**Comment by kestlund** [comment]
https://wiki.duraspace.org/display/hydra/Hydra+Developers+-+Making+Progress+Fall+2014

That's the meeting where the structure really bore out for review as to what would become PCDM.

**Comment by mtribone** [comment]
And that's the meeting Giarlo attended, yes? Focusing on Penn State timeline with respect to PCDM.

**Comment by kestlund** [comment]
@mtribone yes, that's the meeting. I was trying to quickly clarify Dan's addition.

**Comment by mtribone** [comment]
Quick screen shot of the general idea of the timeline and repurposing last year's layout. holler back, yo!

![screen shot 2016-09-27 at 2 40 22 pm](https://cloud.githubusercontent.com/assets/4163828/18887016/68360c5a-84c0-11e6-832e-4133c7da7138.png)

**Comment by mtribone** [comment]
The rectangles are where pictures go and still working out fonts, colors, and spacing.

**Comment by awead** [comment]
@mtribone nice! needs the new zombie lion, though. 😄

**Comment by mtribone** [comment]
@awead plenty of room on the bottom right for zombie lion!

**Comment by mtribone** [comment]
Made some adjustments to background colors to limit distractions, added some photos of things to keep it lighter on the logos, word fixes, and color adjustments. Almost there. Holler back if you have some concerns.

![screen shot 2016-09-28 at 11 16 52 am](https://cloud.githubusercontent.com/assets/4163828/18919703/22ab5c1e-856d-11e6-9b6e-3f2cb61eb124.png)

**Comment by mtribone** [comment]
Might do version B and bring back the white boxes with darker text to compare the two versions. Running through my brain as I walked the dog.

**Comment by mtribone** [comment]
Went back to a white box for better legibility and to tie the pics and timeline together. _Seacrest out_

![screen shot 2016-09-28 at 3 44 39 pm](https://cloud.githubusercontent.com/assets/4163828/18929462/8b5be268-8592-11e6-9375-2ee41630f46b.png)

**Comment by mtribone** [comment]
Photo Credits:

Pattee-Paterno Library (background), Penn State Live, Anne-Marie Mountz
https://www.flickr.com/photos/pennstatelive/4951124525/
Attribution-NonCommercial 2.0 Generic (CC BY-NC 2.0) - No changes
https://creativecommons.org/licenses/by-nc/2.0/

Flag of Portland, City of Portland, Douglas Lynch
https://en.wikipedia.org/wiki/Flag_of_Portland,_Oregon
Public Domain

White Stag, By Tony Webster
https://flic.kr/p/t3GWjV
[CC BY 2.0 (http://creativecommons.org/licenses/by/2.0)], via Wikimedia Commons

Stanford Memorial Church, Michael A. Tribone

Pattee-Paterno Library (tulips), Penn State Live, Alina Gluck
https://www.flickr.com/photos/pennstatelive/8678850950/
Attribution-NonCommercial 2.0 Generic (CC BY-NC 2.0) - No changes
https://creativecommons.org/licenses/by-nc/2.0/

**Comment by kestlund** [comment]
Looks great! Thanks for all your work!

I  was going to ask about the photo credits.  Thanks for supplying! Can you
also ensure any Creative Commons ones list the license?

Minor suggestions, feel free to disregard:
- I wonder if an early data model or the photo from the wiki page for the
  making progess event would work for the Hydra Works block.
- Can you add "Portland" to the Hydra works text, maybe in parentheses?
  It's part of the naming history.
- The white stag image is pretty old. The sign said during the events and
  now, Portland, Oregon. I have one a CC license in the pcdm presentation if
  that works.

**Comment by mtribone** [comment]
Already printed and ready for pickup. Sorry! Felt it was important to complete before travel.  We'd have to upload a version to FedEx and pickup in Boston. Certainly can do it, we'll just need to spend an additional $45.

**Comment by kestlund** [comment]
n.p.

**Comment by mtribone** [comment]
@kestlund If you'd really like the changes, I got this afternoon to make 'em.

**Comment by kestlund** [comment]
@mtribone the only part I'm really concerned about are proper citations for the images.  If you can fix that, that would be great.

I can pay for changes if needed, too.

**Comment by mtribone** [comment]
@kestlund I referenced the the github issue in the poster, just didn't get to adding them here until now.

**Comment by mtribone** [comment]
<img width="1111" alt="screen shot 2016-09-30 at 11 26 28 am" src="https://cloud.githubusercontent.com/assets/4163828/18997037/ca2f184c-8700-11e6-8187-9142a7d6fea9.png">

**Comment by carolyncole** [comment]
What would we like to say about each topic?  I have put in some stuff on certain topics, but please anyone else edit this comment. @mtribone @DanCoughlin @kestlund @awead 

Hydra Works (Portland) November  
- Model discussion in a small group to design a common data model for the Hydra Community

Code4Lib PCDM Meeting 
- Pass the model past a more broad group to validate names and design.

LDCX PCDM Planning 
- Getting tickets written and organized for the PCDM Sprint as a unconference topic for a LDCX breakout

Penn State PCDM Sprint
- Intial coding of Curation Concerns moving sufia modesl to curation concerns and Sufia based on curation concers. 

Sufia & Curation Concerns Design & implementation
- Princeton, PennState, Michigan continued to work on creating Curation Concerns, and Sufia based on Curation Concerns. 

User Interface Working Group
  *

Sufia 7.0 Release
- Initial released version of PCDM Sufia with with PCDM::Works

ScholarSphere 3.0 
- Future release of ScholarSphere including Sufia PCDM 
- Migrated Data from Sufia 6 - Sufia PCDM

**Comment by carolyncole** [comment]
@mtribone great poster!  Closing since it is done
