### ISSUE TITLE
Title Order and Creator order

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#369]
Since multiple titles will either be in random order or alpha order in the current Sufia 7 implementation, I have checked production to see what kind of impact that will have.

We currently have 39 depositors using more than one title:
{"sxs551"=>1, "mjf25"=>5, "gmr159"=>1, "mjl9"=>1, "jsm334"=>3, "sem268"=>31, "gnf1"=>5, "bqw5095"=>1, "dgn2"=>2, "sxh36"=>6, "tlr15"=>1, "dvo"=>3, "sjs49"=>1, "cwc5"=>1, "mus54"=>1, "jdw5170"=>221, "mjp5130"=>1, "adm135"=>1, "tdp11"=>1, "lcb11"=>3, "cpl2"=>4, "jjd264"=>1, "jjm38"=>1, "oom5021"=>1, "jgm106"=>1, "pmh22"=>2, "ajs23"=>2, "dmc186"=>1, "gac2"=>1, "esc10"=>1, "aus50"=>1, "ard19"=>1, "wuw12"=>1, "cej14"=>1, "bal19"=>1, "bah1"=>1, "bzl1"=>4, "ahh139"=>1, "lmo11"=>1}

Those depositors have deposited 317 files into the system. 

Will add Creator information soon.

@olendorf Any other fields where order has an implied meaning?

**Comment by carolyncole** [comment]
We have 148 depositors using more than one creator on 757 files.

```
[["sxs551", 1], ["nzs3", 1], ["mjl9", 1], ["sua30", 1], ["jmc85", 1], ["bnj108", 1], ["nuc15", 1], ["dgn2", 1], ["kxm", 1], ["mat141", 1], ["bec169", 1], ["ell5107", 1], ["sjs49", 1], ["cwc5", 1], ["mus54", 1], ["lah40", 1], ["emb28", 1], ["lbg10", 1], ["jev11", 1], ["jar5757", 1], ["ard", 1], ["adm135", 1], ["oom5021", 1], ["bid1", 1], ["jgm106", 1], ["dmc186", 1], ["sjs230", 1], ["cjb30", 1], ["cjg130", 1], ["sgt3", 1], ["ixj111", 1], ["dmp5380", 1], ["syk5497", 1], ["bmg17", 1], ["tdp11", 1], ["mam1196", 1], ["wuw12", 1], ["hap10", 1], ["sxm468", 1], ["tms5611", 1], ["bah1", 1], ["ajs23", 1], ["rqj5133", 1], ["wxs5138", 1], ["dcc5235", 1], ["jjp18", 1], ["jqj5228", 1], ["alh5626", 1], ["sps5394", 1], ["ack12", 1], ["els22", 1], ["hih103", 1], ["ahh139", 1], ["smm6714", 1], ["moa5297", 1], ["jlh6110", 1], ["grs5176", 1], ["jsr25", 1], ["sbm19", 1], ["dxf19", 1], ["klb489", 1], ["cbm5125", 1], ["dan182", 1], ["amv5430", 1], ["jur5004", 1], ["rip5213", 1], ["pfl5008", 1], ["mak411", 1], ["rjm5786", 1], ["kap5708", 1], ["lme20", 1], ["krp5219", 1], ["sjl5366", 1], ["jrp5569", 1], ["pbp5043", 1], ["cnn5053", 1], ["elf113", 1], ["ard21", 1], ["cxc754", 1], ["gxa9", 1], ["bzl1", 1], ["vrc112", 1], ["jmm7148", 1], ["plf14", 1], ["smt254", 1], ["cld310", 1], ["mjg36", 2], ["iym6", 2], ["siw101", 2], ["hul157", 2], ["jas1218", 2], ["nea11", 2], ["fxc8", 2], ["epd103", 2], ["tll30", 2], ["dbm2", 2], ["ala5124", 2], ["jqt5124", 2], ["gac2", 2], ["sxg37", 2], ["mkg5248", 2], ["klf5363", 2], ["pmh6", 2], ["nbp104", 2], ["sph5202", 2], ["bus146", 2], ["jah1147", 2], ["mam1201", 2], ["fxm13", 3], ["gmr159", 3], ["lrm4", 3], ["lcb11", 3], ["cpl2", 3], ["jak47", 3], ["cjt171", 3], ["pwg5087", 3], ["uxg3", 3], ["jak6029", 3], ["lxf5", 4], ["txl133", 4], ["cdc17", 4], ["esc10", 5], ["ibb3", 5], ["mjf25", 6], ["jsm334", 6], ["sxh36", 6], ["mob5256", 6], ["cej14", 6], ["eal17", 6], ["jpm46", 7], ["tlr15", 8], ["aus50", 8], ["cja12", 8], ["jjm38", 9], ["jrl1209", 9], ["mls164", 9], ["gnf1", 10], ["ard19", 10], ["jjd264", 10], ["sdq", 13], ["eyd1", 14], ["saw4", 20], ["sas76", 21], ["pmh22", 24], ["sem268", 43], ["mgs190", 45], ["jdw5170", 109], ["smh56", 162]]
```

**Comment by carolyncole** [comment]
@olendorf it looks like Joshua Wilkins(jdw5170) and Sarah Chilenski ( sem268)  are a power users in both groups.
Here is a link to Joshua Wilkins files in ScholarSphere: https://scholarsphere.psu.edu/catalog?depositor=%22jdw5170%22&search_field=advanced
It looks like most of Sarah Chilenski's files are private: https://scholarsphere.psu.edu/catalog?depositor=%22sem268%22&search_field=advanced

**Comment by awead** [comment]
FYI: We can continue to use the latest Sufia, which is the forthcoming 7.2 release, and maintain the current behavior of a pseudo-preserved ordering. However, we will we need to pin our Gemfile to RDF ~> 1.99 and ActiveFedora ~> 10.3, so we'd be unable to take advantage of newer features in ActiveFedora 11, for example.

This should at least buy us some time to decide on alpha-sorted fields, or wait for a complete solution on the issue.

**Comment by olendorf** [comment]
@cam156  @awead Should I be assignee on this?

**Comment by carolyncole** [comment]
@olendorf I believe so.  We need to decide what we want to do with the multiple titles and creators when we move to hyrax.  I think the original thought was that we could reach out to existing users to see what they meant by having multiple creators and titles so we could modify our metadata appropriately. That said I do not think this is needed for 3.0

**Comment by olendorf** [comment]
@cam156  Oh right. I actually did that. Creator order is important as entered. For manuscripts, one person said it wasn't too important because the manuscript counts. However, for things that are only published in Scholarsphere, expecially things like data, it becomes more important. Multiple titles, no one thought that they would do that.

**Comment by carolyncole** [comment]
ref #764 as we refactor creator we should consider allowing for orcid, or ids to be entered instead of text.

**Comment by carolyncole** [comment]
For creator we should preserve the order they input the items into the system.
Possibly using a secondary field that contains the display order of all items.

For title we will allow a single title field and a single subtitle field.  The user can use punctuation within the titles if they feel they need more.

**Comment by carolyncole** [comment]
possible solutions:
1. Smash all the values into the current creator field
1. Use Order proxies
1. Keep current creator field as is and add a new predicate for storing display order

The last option is the current fan favorite.
