### ISSUE TITLE
Which fields are required for the work?

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#374]
What fields do we need for Share, Google, PAGES, and other external systems?
#359 will influence this issue.

**Comment by olendorf** [comment]
Google is still title, creator and date published. They also suggest other things but based on looking at repos that are indexed these aren't required.

For share, I can't find the documentation for it, although based on their API, maybe nothing is required? Needs further looking into.

**Comment by olendorf** [comment]
I think this ticket can be closed in the sense that we currently required the correct metadata. Google require Title creator and data published. Talking with their rep so far (only two brief emails) it sounds like they also try to verify the info. Not sure how they do it for all the content that doesn't really have that embedded. 

I think now that we are live, have the new required fields in place we can see if we improve over the three? items that are in google scholar? 

I will continue the dialogue with google as well.

Additionally, we should look at tweaking our ingest forms/workflow to get better metadata. I.e. actual informative titles, not file names or crypto-garbage.

Good descriptions.

Things such as that.
