### ISSUE TITLE
Add new license options for CC4 & software licenses

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#376]
Add additional options for CC4 and software license to the drop down box for rights.
Remove the CC3 options from  the list, but keep them valid for existing works (configuration option)

**Comment by carolyncole** [comment]
Set all the CC3 to inactive. Add CC4 & Software licenses.
https://github.com/psu-stewardship/scholarsphere/blob/develop/config/authorities/rights.yml

**Comment by carolyncole** [comment]
@olendorf What software licenses would you like to see?

**Comment by olendorf** [comment]
Sorry, didn't see this. I would say Apache 2.0, GPL and MIT?

**Comment by olendorf** [comment]
Based  on a conversation with Anne Langley as a user and also my experience as a user, I think licensing could be "smarter". Perhaps change default license based on content type?
