### ISSUE TITLE
uninitialized constant BrowseEverything::Retriever::Addressable

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#383]
When a File is uploaded from box the content does not get attached.  The following error is captured in resque:

```
ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
Arguments

---
job_class: ImportUrlJob
job_id: e58b305c-310f-418c-a3fc-df29fba66fc1
queue_name: default
arguments:
- _aj_globalid: gid://scholar-sphere/FileSet/gh93gz487
- _aj_globalid: gid://scholar-sphere/CurationConcerns::Operation/17
locale: en
Exception
NameError
Error
uninitialized constant BrowseEverything::Retriever::Addressable
```

**Comment by awead** [comment]
See https://github.com/projecthydra/browse-everything/blob/master/lib/browse_everything/retriever.rb#L33

I think we need to require addressable somewhere so it finds it at the top of the namespace.

**Comment by mtribone** [comment]
We need to look at the batch upload for the same workflow. QA demo was a bit confusing.
