### ISSUE TITLE
Tumblr share does not work

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#384]
The link to share via tumbler is going to an error page.  We may need a new version of the gem that shows those items.

```
<a class="resp-sharing-button__link" target="_blank" rel="noopener noreferrer" title="Tumblr" href="https://www.tumblr.com/widgets/share/tool?content=https%3A%2F%2Fscholarsphere-qa.dlt.psu.edu%2Fconcern%2Fgeneric_works%2F9g54xh64n&amp;posttype=link&amp;shareSource=tumblr_share_button">
    <div class="resp-sharing-button resp-sharing-button--tumblr resp-sharing-button--small"><div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
      <svg version="1.1" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
          <g>
              <path d="M13.5,0.5v5h5v4h-5v5.515c0,5.028,3.52,4.427,6,2.798v4.433c-6.728,3.172-12-0.064-12-4.255V9.5h-3V6.668 c0.903-0.293,2.245-0.714,2.889-1.261c0.646-0.551,1.162-1.208,1.551-1.976C9.331,2.664,9.6,1.686,9.746,0.5H13.5z"></path>
          </g>
      </svg>
      </div>
    </div>
</a>
```

**Comment by carolyncole** [comment]
Looks like we removed the other gem that did this and just put in our own code:
https://github.com/projecthydra/sufia/blob/master/app/views/curation_concerns/base/_social_media.html.erb

The content attribute should be canonicalUrl according to tumblr's documentation: https://www.tumblr.com/docs/en/share_button

**Comment by awead** [comment]
We should have a scholarsphere tumblr account so we can fully test this.

**Comment by carolyncole** [comment]
Here is a group email that could possibly be used: umg-up.its.sas.scholarsphere-email@groups.ucs.psu.edu

**Comment by awead** [comment]
I wasn't able to use that email because I can't get messages sent to me if I use it. I however get umg-up.its.scholarsphere-support@groups.ucs.psu.edu to work. But, I'm unable to create a tumblr account. After going through the process, it creates a yahoo account, but tumblr doesn't think I have one.

**Comment by awead** [comment]
It's been a few days now and I'm still having the same problem. I attempted to cancel the existing account on Yahoo and start over, but doesn't work either. I'm unable to cancel the existing Yahoo account with scholarsphere-support. At this point, the only alternative I can see is to try this again but with a different email.
