### ISSUE TITLE
On the Home Page the Unified Search Drop down is really hard to read

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#385]
The following is a screenshot of the unified search drop down. On other pages the drop down is ok

![screen shot 2016-10-10 at 7 22 34 am](https://cloud.githubusercontent.com/assets/1599081/19234560/6a92ce94-8eba-11e6-8885-2e9150ad6371.png)

**Comment by carolyncole** [comment]
Css for the tool bar in the header is being applied to the drop down. The css is too specific. In Sufia change the homepage css selectors

**Comment by mtribone** [comment]
https://github.com/projecthydra/sufia/issues/2850
