### ISSUE TITLE
Upload a Folder and only got one of the two files

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#387]
When I go to my work 
And I click Upload Folder
I should always get all of the files

**Comment by carolyncole** [comment]
Not able to repeat

**Comment by carolyncole** [comment]
Verify that this is an actual issue and not just a problem behind the keyboard.  Write up the the steps to cause the issue.

**Comment by carolyncole** [comment]
I was able to verify that this is an issue.  Will document the steps to create the issue in another ticket.  It seems that sometimes blank lines are inserted into the upload instead of an actual file.
![screen shot 2016-11-14 at 11 39 15 am](https://cloud.githubusercontent.com/assets/1599081/20273556/c453a08c-aa5f-11e6-8d1d-12b52886114d.png)

**Comment by mtribone** [comment]
Still unsure if this has been resolved.

**Comment by awead** [comment]
I'm able to replicate this in QA, but not locally. I tested it with 100 1.5 KB files. When uploading, 6 files appear as empty rows. When watching the process on the back-end, I am seeing that 100 Sufia::UploadedFile objects are added, however when I proceed with the work creation, only 96 out of the 100 files make it into the work.

**Comment by awead** [comment]
Duplicate of #453
