### ISSUE TITLE
I should see size in characterization metadata

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#390]
When I view characterization metadata I should see the FileSet size in the characterization metdata.

**Comment by carolyncole** [comment]
Looks like it is not being index for display.  The display items are here: https://github.com/projecthydra/curation_concerns/blob/master/app/presenters/curation_concerns/characterization_behavior.rb

Or we are not using the version of curation concerns that displays that information

**Comment by nrm149** [comment]
PSUSprint3
