### ISSUE TITLE
Update the namae gem

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#392]
The namae gem is pinned to "0.9.3" but I can't tell if there's a reason for that. Should we update?

**Comment by carolyncole** [comment]
@awead is there a reason to update or are you just updating to update?  We are not at the point in the project to just randomly update, becuase we want to reduce unnecessary change.  That is why we are pinning to Sufia 7.2.

**Comment by awead** [comment]
Update to the latest version to stay current, or pin to specific version if there are conflicts, and note those conflicts in the Gemfile. If significant failures occur due to the update, those should be ticketed for later resolution.
