### ISSUE TITLE
Help Page has Patricia's information

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#394]
The help page editable content has Patricia's email and possibly phone number.  This should be changed and can be changed by any administrator.  

![screen shot 2016-10-11 at 7 47 15 am](https://cloud.githubusercontent.com/assets/1599081/19269179/0c1157b4-8f87-11e6-823d-989a504aef78.png)

I also modified the links to point to pages in the new Library web site yesterday.  I am not positive I picked the correct pages.

**Comment by olendorf** [comment]
@cam156 The boilerplate file also has patricias info. how can I change that?

**Comment by carolyncole** [comment]
@olendorf Patricia uploaded a file to ScholarSphere and linked to it: https://scholarsphere.psu.edu/files/cv43nw822

You could create a new version of that file, or go ahead and upload another file.  The only people with edit access to the file have left, but as an administrator we can change the file.

**Comment by olendorf** [comment]
@cam156  OK. thanks I'll work on that then.

**Comment by olendorf** [comment]
@cam156 I uploaded a revised doc to box at https://psu.app.box.com/file/138258319704

**Comment by carolyncole** [comment]
@olendorf I converted your box file to pdf as it loads into the browser nicer.  In addition I change the help page text to include your information.

One question did you really want 
```
Robert Olendorf,  ScholarSphere User Services and Research Data Librarian
```
instead of the following in the document?
```
Robert Olendorf, Head, ScholarSphere User Services and Research Data Librarian
```

**Comment by olendorf** [comment]
@cam156  That looks good to me. Thanks.
