### ISSUE TITLE
Sufia 6 now has Collection Permissions, is this something I should deploy

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#396]
We now have the ability to change the visibility of collections and share edit permissions in Sufia 6.

Is this something I should be deploying to production next week?  Is this something that I should avoid deploying to production?

Current Collection UI
![screen shot 2016-10-11 at 12 15 38 pm](https://cloud.githubusercontent.com/assets/1599081/19278834/df542730-8fac-11e6-8e3c-be0f18421664.png)

New Collection UI with sharing

![screen shot 2016-10-11 at 12 20 23 pm](https://cloud.githubusercontent.com/assets/1599081/19278917/252bd28a-8fad-11e6-9603-7185562772ad.png)

**Comment by carolyncole** [comment]
You can see the new collection feature in action on staging: https://scholarsphere-staging.dlt.psu.edu

**Comment by awead** [comment]
I'm on the fence about this. It would be another (potential) thing to migrate, and it might be better to just present this feature along with all the other new stuff in the upcoming 3.0 release. However, if others feel strongly the other way, I'm not opposed to releasing into production now.

Is it stable in Sufia 6? I thought I saw some slack chatter about broken tests, but maybe I'm misunderstanding.

**Comment by carolyncole** [comment]
@awead it is stable in Sufia 6.   We had overridden views that needed additional fields for Collections to work.  We are already planning to migrate permissions with Collections, so I do not see it as another migration.  It is a good point.

**Comment by olendorf** [comment]
@cam156  Can this be closed?
