### ISSUE TITLE
Thumbnail creation fails for documents

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#400]
See: https://github.com/projecthydra/hydra-derivatives/issues/109

To reproduce, create a new work with this file https://dl.dropboxusercontent.com/u/9554743/test.odt

**Comment by carolyncole** [comment]
Not allowed to resize.  Rewrite to convert to PDF and then use image magic.
Cut a new hydra derivatives version

**Comment by nrm149** [comment]
Sprint 3 PSU
