### ISSUE TITLE
Allow large files to be uploaded by an Administrator

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#403]
As an administrator I would like to allow for files larger than 5 gb to be uploaded on behalf of another user.

The files would be located on a network drive available to the servers
The file would be ingested on behalf of the requesting user, or transferred to the user after upload.

**Comment by carolyncole** [comment]
@olendorf These are the tickets

**Comment by mtribone** [comment]
Close this one out as it will be handled by the new SS.

**Comment by mtribone** [comment]
Moving this to the new work for the new TBD ScholarSphere
