### ISSUE TITLE
Allow browse everything file system upload for administrators

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#404]
Browse everything can be configured to allow for file system upload.  Part of #403 

We would like to configure that capability, but only for administrative users.
1. create network location available to web app servers and jobs servers
2. configure files system upload for that location
3. override browse_everything/_providers.html.erb to only show file system for administrative users

```
<form class="form-inline">
  <label target="provider-select">Source:</label>
  <select class="form-control" id="provider-select">
    <% browser.providers.each_pair do |key, provider| %>
      <% next if key == 'file_system' && !current_user.administrator? %>
      <option value="<%=browse_everything_engine.contents_path(key)%>">
        <%= provider.name %>
      </option>
    <% end %>
  </select>
</form>
```

**Comment by mtribone** [comment]
Focus of the project has changed and we are moving to a new ScholarSphere that may not be dependent on the current technology stack.
