### ISSUE TITLE
Announcement Text for Collections Permissions

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#411]
We need to create text to announce the new Collection Permissions that will come out with the release of ScholarSphere 2.8.

**Comment by olendorf** [comment]
@cam156 OK...so now that I'm exploring it, I realize I'm not quite sure what those changes are. #feelingstupid

**Comment by carolyncole** [comment]
@olendorf I should have referenced this issue: https://github.com/psu-stewardship/scholarsphere/issues/396

**Comment by olendorf** [comment]
@cam156 Got it, working on it now.

**Comment by olendorf** [comment]
@cam156 Here you go.

---

New Feature! We have recently updated Scholarsphere and while many of the changes aren't very noticeable we have one shiny new feature you might like. If you use collections to group your Scholarsphere content, now you can control the visibility, making a collection Public, Private or Penn State only. Also you will be able to share the collection with specific individuals or groups of individuals. Give it a try and tell us what you think. If you have any problems or suggestion feel free to user our Contact Us page.

**Comment by carolyncole** [comment]
The text above has been put out on Production.
