### ISSUE TITLE
All jobs are running on the default queue now.

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#414]
When resolrize runs it seems to only run on the default queues.

Other jobs seem to be the same way

**Comment by carolyncole** [comment]
I do not know how many jobs this needs to be done for.  It may only be the resolrize, but many may have the issue.  The queue should get set in the job.

**Comment by awead** [comment]
The resolrize job that is defined in CurationConcerns isn't given a specific queue. There is a `config.ingest_queue_name` that defines the queue for IngestFileJob, CharacterizeJob, and CreateDerivativesJob.

**Comment by carolyncole** [comment]
I have seen items running on the different queues
