### ISSUE TITLE
Cap did not precompile the assets on the jobs server

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#415]
running `rake assets:precompile` created the collection.png

I thought the cap task did this each time we deploy.  Why did that not happen?

from looking at the logs it is only happening on ss1 & ss2 not on the jobs server

```
     01 RBENV_ROOT=$HOME/.rbenv RBENV_VERSION=2.3.1 $HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
    ✔ 01 deploy@ss1qa.dlt.psu.edu 31.205s
    ✔ 01 deploy@ss2qa.dlt.psu.edu 39.271s
** Invoke deploy:assets:backup_manifest (first_time)
** Execute deploy:assets:backup_manifest
```

**Comment by carolyncole** [comment]
Only related to scholarsphere. Fix would be in the deploy.rb

**Comment by awead** [comment]
@cam156 ssjobs1qa does not have the "web" role in its cap config. Is there a reason the assets need to be on the jobs server? The config hasn't changed in a while:
https://github.com/psu-stewardship/scholarsphere/blob/develop/config/deploy/qa.rb

**Comment by carolyncole** [comment]
@awead yes, but the issue is that Jobs was not creating assets before.  Now the Jobs servers are creating the thumbnails when the file is ingested and storing that URI into solr.  If the assets are not precompiled this causes issues.

**Comment by awead** [comment]
ok. I'll add the "web" profile in and see if that fixes things. Hopefully it won't pull in extra things we don't want.

**Comment by awead** [comment]
I ended up choosing a more conservative option that simply compiles the assets for job servers. I'm now seeing assets being compiled for ssjobs1qa. If this still doesn't fix this problem, we can go ahead and add the "web" role to jobs.
