### ISSUE TITLE
Make the colors consistent for work and collection images

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#417]
One should not be blue and the other be black

![screen shot 2016-10-21 at 10 50 10 am](https://cloud.githubusercontent.com/assets/1599081/19602709/437c4784-977c-11e6-9622-1ab949aaf4f9.png)

**Comment by carolyncole** [comment]
Generate image in a different color.  Change the catalog list view and gallery view to use the thumbnail url in solr, which would use the image instead of font awesome.

**Comment by mtribone** [comment]
Some inconsistency during the QA demo. Need to reindex solr and double check. Broken thumbnails and incorrect color of icons.
