### ISSUE TITLE
Dashboard Layout Needs to be Improved

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#418]
The top top rows of the dashboard need to be improved, so that they stack and align properly with each other and when on smaller screen sizes

![screen shot 2016-10-25 at 9 02 12 am](https://cloud.githubusercontent.com/assets/4163828/19687078/0f676046-9a92-11e6-91ac-b01ab999d827.png)

**Comment by carolyncole** [comment]
Addressing the spacing between Hello, and Name and System Stats.  ALso put buttons more centrally.  Make sure it stacks nicely between mobile and desktop.
May need some additional bootstrap classes along with CSS

**Comment by mtribone** [comment]
The `_heading_actions.html.erb` partial has been updated in Sufia, but split into 2 partials – create work and actions. Should I override the headings actions or wait for the update from Sufia.

**Comment by mtribone** [comment]
https://github.com/projecthydra/sufia/blob/master/app/views/dashboard/_index_partials/_heading_actions.html.erb

**Comment by mtribone** [comment]
Looks like the dashboard is hosed on QA
