### ISSUE TITLE
Replace Old Audio Icon

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#424]
Version for ScholarSphere
https://github.com/projecthydra/sufia/issues/2427

**Comment by mtribone** [comment]
What if we use the volume icon for our default audio png file?

![screen shot 2016-10-26 at 9 41 56 am](https://cloud.githubusercontent.com/assets/4163828/19728391/2d84abb8-9b61-11e6-8f30-d971b6989b77.png)

**Comment by olendorf** [comment]
I'm a fan of this one.

**Comment by mtribone** [comment]
https://github.com/projecthydra/sufia/issues/2427

**Comment by mtribone** [comment]
Still seeing the old icon in QA. Maybe the new file wasn't moved over?

<img width="1214" alt="screen shot 2016-11-04 at 9 39 04 am" src="https://cloud.githubusercontent.com/assets/4163828/20007446/a5349cf0-a272-11e6-930a-0b9d9ff7d7f6.png">

**Comment by mtribone** [comment]
I think that this is still an issue. Just uploaded a fresh file and get the default *document* icon.


![screen shot 2016-12-15 at 8 17 42 pm](https://cloud.githubusercontent.com/assets/4163828/21248237/a77c5938-c303-11e6-9044-f2b778cf8663.png)
