### ISSUE TITLE
ScholarSphere User Testing Participants

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#433]
Create a list of volunteers for User Testing of works.

**Comment by olendorf** [comment]
Ken Mankoff mankoff@psu.edu  Climate Science/Glaciology (done)
Zhao Su zxs6@psu.edu Biology (willing)
Yin Tang yxt148@psu.edu Integrative Biosciences (willing)
Philip Bevilacqua Biology cb5@psu.edu Chemistry 
Sheila Trampush smt254@psu.edu (mid-late january)
Moriah Loise Szpara mls164@psu.edu
Jason Kaye jpk12@psu.edu
Andrew Deans ard19@psu.edu
John Leeman jrl1209@psu.edu 
Stephen Schaeffer sws4@psu.edu
Miriam Freedman maf43@psu.edu
John Meier jjm38@psu.edu (willing need to set up time) (done)
Alexis Sullivan aps216@psu.edu
Iliana Baums ibb3@psu.edu
Sarah Mcclure sbm19@psu.edu (January)
Sridhar Anandakrishnan sxa17@psu.edu (in the field until january)
Timothy Reluga treluga@math.psu.edu (willing)

**Comment by olendorf** [comment]
emailed the above list of people

**Comment by olendorf** [comment]
Just making it so Nigel is a participant @nrm149

**Comment by olendorf** [comment]
Ready to start testing, I will start contacting the participants copying @cam156 and @mtribone

**Comment by olendorf** [comment]
We're done with this so closing it.
