### ISSUE TITLE
Location autocomplete still not working in QA

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#434]
When attempting to enter a location name into the location meta field there is not dropdown of suggested locations.

**Comment by carolyncole** [comment]
Could be a configuration issue on QA.  Could also be the javascript is broken

**Comment by carolyncole** [comment]
https://sites.psu.edu/dltdocs/?p=3330

**Comment by awead** [comment]
Looks like we need to configure the account username:
`Qa::Authorities::Geonames.username = 'myAccountName'`
