### ISSUE TITLE
Missing Required Metatdata when Editing a Work

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#435]
When I select a previously created work for editing, the abstract and resource type metadata is missing.

Needs verification

**Comment by carolyncole** [comment]
During the demo when editing existing works the metadata was not getting saved.  Can we figure out how to reproduce this.  This happened on QA during the demo.

**Comment by awead** [comment]
I can't reproduce this, but batch creation does not have the right required fields. So if a resource was created using batch, those fields would be missing.

**Comment by mtribone** [comment]
I've just tested the batch upload and it appears that the rights aren't being set. When I view a work individually, I don't see the rights listed. When I edit the work based on a batch, the required rights field is not set.
