### ISSUE TITLE
Make Marketing Text Legible above the image on the home page

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#437]

**Comment by carolyncole** [comment]
Could be create a new image, could be taking out the image completely.
May include mock ups and a few iterations.

**Comment by mtribone** [comment]
Reworking the home page. I've made the navbar consistent with the other portions of the site and have started to "rough in" the basic blocks a piece at a time. Flash messages and announcements are next then I'll work on the color scheme a bit to make the content less blue.

![screen shot 2016-11-30 at 2 38 16 pm](https://cloud.githubusercontent.com/assets/4163828/20768127/bafd80ae-b70a-11e6-9e79-bd38a471f10c.png)

**Comment by mtribone** [comment]
@olendorf I've just blocked in some sections, updated spacing, and added a pinch of color. Thoughts so far?

![screen shot 2016-12-06 at 9 54 31 am](https://cloud.githubusercontent.com/assets/4163828/20930091/4390ce2e-bb9a-11e6-92c4-fe4909871698.png)

**Comment by olendorf** [comment]
@mtribone  This is looking pretty good. Couple questions/thoughts. 

* What does the **_Explore Collections_** tab do? 
* Does the yellow seem a bit incongruous to you? I'm feeling maybe a lighter green or blue would be more in keeping with the theme.
* The search box seems really lost to me. Would it be possible to make it more Googley and make it big and prominent, maybe just below where the new feature block goes?

**Comment by mtribone** [comment]
@olendorf 

1.  The explore collections tab lists the administrative collections created by administrators.
1. The yellow is definitely noticeable! :-) I can try out a different color and see if it recedes too much visually
1. I certainly can move it to the middle and under the announcement block. I moved it up to the bar to keep it consistent with the rest of the site. However, if we're trying to promote discovery a bit more how about in a row right under the marketing block?


![screen shot 2016-12-07 at 10 37 24 am](https://cloud.githubusercontent.com/assets/4163828/20974405/10333208-bc6a-11e6-919a-597b3b648de1.png)

**Comment by mtribone** [comment]
Trying out a green...

![screen shot 2016-12-07 at 2 08 42 pm](https://cloud.githubusercontent.com/assets/4163828/20982473/bd970656-bc86-11e6-8d2a-d28e07380fcd.png)

**Comment by mtribone** [comment]
And the search in the middle...

![screen shot 2016-12-07 at 2 29 36 pm](https://cloud.githubusercontent.com/assets/4163828/20983223/a77a7c42-bc89-11e6-8ffa-fa13b9a22bbd.png)

**Comment by mtribone** [comment]
@olendorf I had to go one step darker for both the share button background and the new feature background. Yes/No? Otherwise I would need to make the white text larger with the previous colors to hit sufficient contrast.

![screen shot 2016-12-09 at 9 45 44 am](https://cloud.githubusercontent.com/assets/4163828/21052782/a413d53c-bdf4-11e6-861a-7c95bc004e68.png)

**Comment by mtribone** [comment]
I'm starting to question the WAVE tool's contrast evaluator. Black over dark blue _shouldn't_ pass!

![screen shot 2016-12-09 at 9 52 52 am](https://cloud.githubusercontent.com/assets/4163828/21052973/6c795cd6-bdf5-11e6-8aa9-16bd0229609f.png)

**Comment by mtribone** [comment]
I worked it out with bigger text


![screen shot 2016-12-09 at 10 20 38 am](https://cloud.githubusercontent.com/assets/4163828/21053864/4032129a-bdf9-11e6-98c3-a6f7326b3885.png)
