### ISSUE TITLE
Automatically generate DOI for work as it is deposited

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#442]
- [x] Work
- [x] Collection
- [ ] Batch or Works

**Comment by carolyncole** [comment]
Use identifier field for storing automatically generated DOIs

**Comment by olendorf** [comment]
As a depositor I would like to easily generate DOIs for my works so that they can be cited unambiguously.

**Comment by carolyncole** [comment]
There is an API and a ruby gem for getting a DOI.
Wrapping the api and sending metadata from the work: They require creator and title.

Add a check box to the new work or edit work form to say Yes create a DOI.

The check box should be in the metadata or the save button.  A DOI would be generated as part of the save process, not in the form.

DOI creation should only be done once for any work.
If the user changes the title and creator, or other metadata the DOI system would need to be updated.

If there is a failure to the identifier will get set to "DOI Failed"

**Comment by carolyncole** [comment]
@olendorf  will add a list of fields to send to the API

**Comment by carolyncole** [comment]
dependent on #1054, because we should be able to generate a DOI for a collection too.

**Comment by olendorf** [comment]
Really just the required will work. I typically put in the abstract and key words too. I don't know if the DOI metadata is ever used for anything though.
