### ISSUE TITLE
A better resolrize job

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#445]
The default resolrize job in CC calls `.index_everything` which submits one job to reindex everything. If one of the objects fails to index, then the job fails and no further items are indexed. A better solution is to submit an individual job for each object in the repo, that way if one fails to index, it will be reported clearly and the other items in the repo would continue to be reindexed.

**Comment by carolyncole** [comment]
@awead I have updated that in the current production version.  We will need to integrate this job into develop: https://github.com/psu-stewardship/scholarsphere/blob/master/app/jobs/resolrize_job.rb

**Comment by carolyncole** [comment]
Make the above commit and active job and make sure it runs.
