### ISSUE TITLE
Can't upload filenames with spaces using Browse Everything

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#447]
When uploading a file from the local filesystem using Browse Everything, if the filename as a space in it, I get:

`bad URI(is not URI?): file:///path/to/file with spaces.jpg`

**Comment by carolyncole** [comment]
Need to URI encode the file name before sending it to URI.

**Comment by carolyncole** [comment]
Need to configure QA to have browse everything file system so this can be fully tested on the server

**Comment by awead** [comment]
This is done via #546 and is now working with both local files and Box. However, local files will fail characterization and derivatives because of #448
