### ISSUE TITLE
Uploading from Browse Everything deletes the file

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#448]
When uploading from the local filesystem using Browse Everything, after I have selected a file and created the work, the file is uploaded into the work, but the original file is deleted from my filesystem.

**Comment by carolyncole** [comment]
@awead I am assuming this is in ScholarSphere 3.0 version?

**Comment by carolyncole** [comment]
This ScholarSphere 3.0.

**Comment by awead** [comment]
@cam156 I'm upgrading this to a blocker. Now that large file upload is configured in #546, if we upload a file via BE and local filesystem, Scholarsphere attempts to delete the file. Although it fails because it doesn't have the access rights, it halts the rest of the process chain and no characterization or derivatives are created. Here's the Resque error:
```
Worker
  ssjobs1qa:22408 on files at 2017/01/16 16:30:29 -0500
  Retry or Remove
Class
  ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
Arguments
---
  job_class: IngestLocalFileJob
  job_id: b0cc0888-59d2-42eb-ad4e-0c2bcb02389d
  queue_name: files
  arguments:
  - _aj_globalid: gid://scholar-sphere/FileSet/n02870x783
  - "/dlt/scholarsphere/upload_qa/browse_everything_file_system/Filename with spaces.txt"
  - _aj_globalid: gid://scholar-sphere/User/9
  locale: en
Exception
  Errno::EACCES
Error
  Permission denied @ unlink_internal - /dlt/scholarsphere/upload_qa/browse_everything_file_system/Filename with spaces.txt
```
