### ISSUE TITLE
Recognize when there is a timout error with importing a url from box or drop box

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#449]

**Comment by carolyncole** [comment]
Looking at this, it seems to occur more often when I my session with Box is stale, aka I uploaded stuff, waited a while and then uploaded some more stuff.  I wonder if the url access length is related to how much time is currently left with the hour long users session.  Aka if the URLs are created with an old session they have less time to upload, than if they are created with a new session.

**Comment by carolyncole** [comment]
<img width="1075" alt="screen shot 2017-04-11 at 10 23 03 am" src="https://cloud.githubusercontent.com/assets/1599081/24914026/fb08bca6-1ea0-11e7-9885-e2cff9ac88fd.png">

**Comment by awead** [comment]
@cam156 we could put something in the import_url_job that might detect expired urls, but there isn't a way to message that to the user. Beyond that, there isn't really a way that I can see checking for this without digging into the BE code, and we're in code freeze right now.

**Comment by carolyncole** [comment]
This is done when when we do not ingest the error page as content and the user gets a notification that the file has errored and that they should try uploading it again.

**Comment by awead** [comment]
@cam156 Here's a strategy for checking the url before downloading.

The above error page is a 404 response from Box, at least, I use an expired URL, that's the same page I get and the code is 404. If you look at a correct head request for a file in box:

``` bash
$ curl --head http://a.good.box.url/
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: private
X-Robots-Tag: noindex, nofollow
Content-Type: application/octet-stream
X-Content-Type-Options: nosniff
Content-Disposition: attachment;filename="99bottles (1).epub";filename*=UTF-8''99bottles%20%281%29.epub
Content-Length: 1013573
Date: Mon, 15 May 2017 20:30:17 GMT
Age: 0
Server: ATS
Connection: keep-alive
```

I think it's safe to assume that good url, with the correct content will be a 200 response and have the Content-Disposition set in the header. We could use HTTParty to do a head on the url and check it before downloading.
