### ISSUE TITLE
Depositor is shown as id instead of name in the file set

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#457]
The depositor in the file set view is shown as the ID not the users name
![screen shot 2016-11-15 at 1 57 06 pm](https://cloud.githubusercontent.com/assets/1599081/20319274/7de0677a-ab3b-11e6-88b8-05651b8fa2a1.png)

**Comment by mtribone** [comment]
I don't think that this is an issue any more.

![screen shot 2016-12-09 at 8 58 30 am](https://cloud.githubusercontent.com/assets/4163828/21051315/bfc6609e-bded-11e6-9d66-8d5539a8f7b9.png)
