### ISSUE TITLE
Strange errors in the dashboard with proxy deposits

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#461]
New Note 4

2016-11-17 11:53:53 -0500 (30460) 
ActiveFedora::ActiveFedoraError (Model mismatch. Expected CurationConcerns::WorkRelation::DummyModel. Got: FileSet):                                            
  active-fedora (10.3.0.rc2) lib/active_fedora/relation/finder_methods.rb:204:in `class_to_load'                                                                
  active-fedora (10.3.0.rc2) lib/active_fedora/relation/finder_methods.rb:195:in `load_from_fedora'                                                             
  active-fedora (10.3.0.rc2) lib/active_fedora/relation/finder_methods.rb:181:in `find_one'                                                                     
  active-fedora (10.3.0.rc2) lib/active_fedora/relation/finder_methods.rb:228:in `find_with_ids'                                                                
  active-fedora (10.3.0.rc2) lib/active_fedora/relation/finder_methods.rb:52:in `find'                                                                          
  active-fedora (10.3.0.rc2) lib/active_fedora/relation/finder_methods.rb:85:in `exists?'                                                                       
  /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/bundler/gems/sufia-35c01618b4d3/app/models/proxy_deposit_request.rb:83:in `deleted_work?'

**Comment by carolyncole** [comment]
It seems that if you have old proxies where the item no longer exists you get a very strange error about model miss match.  Once I deleted my proxy deposit request all was well.  That said we should look at how those request are being migrated and make sure they work.

**Comment by carolyncole** [comment]
Handle any StandardException (Runtime or Other) instead of erroring

**Comment by awead** [comment]
Steps to recreate:

1. bundle exec rake dev:clean db:reset
2. bundle exec rails s
3. log in and create a work
4. Visit the file set page for the work and copy the file set id from the url
5. bundle exec rails c
6. user = User.create
7. ProxyDepositRequest.create(work_id: [fileset id], sending_user_id: [your user id], receiving_user_id: user.id)
8. Visit http://localhost:3000/dashboard with your user id logged in

**Comment by carolyncole** [comment]
@awead was there a change to handle the error?  Or did we decide not to handle the error?  What makes this ticket closed?

**Comment by awead** [comment]
@cam156 I've rescued the error here:

https://github.com/psu-stewardship/scholarsphere/commit/6699ed03c926a3ca33d5b856e4b8662c323bcebf#diff-bc64481b69da55982a8f91c2b2eca2fbR86

If you recall, there's a PR that's ready to merge that addresses this, but we decided to hold off on merging because we're overriding an entire class to make a one-line change, and the error will not occur in the normal course of operations, only when migrating.

**Comment by carolyncole** [comment]
@awead I moved the ticket to the next milestone.  I had forgotten to do that earlier.

**Comment by awead** [comment]
@cam156 thanks!
