### ISSUE TITLE
We need to store the file_size as something other that an integer

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#466]
We had this in the code pre Sufia 7.
solr_doc[Solrizer.solr_name('file_size', STORED_SYMBOL)] = object.content.size.to_i

I think that was to allow for sizes over the solr integer field.

**Comment by carolyncole** [comment]
Here is the error message we see: 

/rsolr/client.rb:288:in `adapt_response': RSolr::Error::Http - 400 Bad Request (RSolr::Error::Http)                                                             
Error: 'ERROR: [doc=3t945q772] Error adding field \'file_size_is\'=\'3091666335\' msg=For input string: "3091666335"','code'=>400}}

**Comment by carolyncole** [comment]
I am still seeing this error when importing file on QA.  Either the code did not get out to qa, I deployed yesterday mid morning or this is not entirely fixed.

**Comment by awead** [comment]
Looks like I didn't set FileSet to use the custom FileSetIndexer.

**Comment by awead** [comment]
@cam156 what size file do we need to use to test this?

**Comment by carolyncole** [comment]
@awead one of the files that is failing is 3091666335 (see the comment above).  I'm guessing than is larger than needed, but a good number to work with.  I'm guessing the solr documentation would give you the real limit.

**Comment by awead** [comment]
@cam156 that's a little over 3 GB. What's the present size limit on file uploads?

**Comment by carolyncole** [comment]
@awead I believe the cloud files are 7G

**Comment by awead** [comment]
Fixed, maybe, but there might be another issue with the work size display. https://scholarsphere-qa.dlt.psu.edu/concern/generic_works/k35694774

**Comment by carolyncole** [comment]
Check this file since the above file is no longer in the system: https://scholarsphere-qa.dlt.psu.edu/concern/parent/k6d56zx87n/file_sets/4b8515n08m
