### ISSUE TITLE
Highlighted Files should show proper thumbnail

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#47]
When I highlight a file
And I go to my dashboard
Then I should see the same thumbnail as I do on my dashboard
![screen shot 2015-01-19 at 9 47 13 am](https://cloud.githubusercontent.com/assets/1599081/5803149/be67fb5c-9fc9-11e4-868d-e22e0a57b3a1.png)
![screen shot 2015-01-19 at 9 46 57 am](https://cloud.githubusercontent.com/assets/1599081/5803150/be6a4092-9fc9-11e4-8aa7-d0fa17b9cf4c.png)

**Comment by jcoyne** [comment]
This is because the mime_type() method on GenericFile is different when the file is instantiated using find  vs load_instance_from_solr:

``` ruby
f = GenericFile.find('ad2722b8-a1cf-41d3-8184-4e15e24335d7')
=> #<GenericFile id: "ad2722b8-a1cf-41d3-8184-4e15e24335d7", mime_type: "image/jpeg",  ...
g = GenericFile.load_instance_from_solr('ad2722b8-a1cf-41d3-8184-4e15e24335d7')
=> #<GenericFile id: "ad2722b8-a1cf-41d3-8184-4e15e24335d7", mime_type: "i", ...
f.mime_type
=> "image/jpeg"
g.mime_type
=> "i"
```

**Comment by jcoyne** [comment]
The fix is in https://github.com/projecthydra/active_fedora/pull/694
