### ISSUE TITLE
Dashboard will not display on QA

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#488]
When visiting the my dashboard, I get a generic error message from the Chrome browser:

"The scholarsphere-qa.dlt.psu.edu page isn’t working"

The log file is showing two problems. First, the actual error:
`2016-12-07 10:19:39 -0500 (14143) Rendering 500 page due to exception: #<ActionView::Template::Error: Model mismatch. Expected CurationConcerns::WorkRelation::DummyModel. Got: FileSet>`

And then the reason for the generic error page seems to be a missing template:
`ActionView::MissingTemplate (Missing template errors/500 with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}`

**Comment by carolyncole** [comment]
My dashboard loads.  I'm guessing this is related to wiping out fedora?

**Comment by carolyncole** [comment]
Related to #461

**Comment by carolyncole** [comment]
We should find out if this is the same issue as #461.  If it is not create a separate ticket.

**Comment by awead** [comment]
It is related. I deleted the proxy deposit requests and all is well. Perhaps we can close this and work on the other ticket?
