### ISSUE TITLE
Adding ARIA Hidden True to Font Awesome Icons

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#511]
"Modern versions of assistive technology, like screen readers, will read CSS generated content (how Font Awesome icons are rendered), as well as specific Unicode characters. When reading our default markup for rendering icons, assistive technology may have the following problems."

- The assistive technology may not find any content to read out to a user
- The assistive technology may read the unicode equivalent, which could not match up to what the icon means in context, or worse is just plain confusing
- Many dyslexic people find it helpful to swap out a website’s typeface for something like OpenDyslexic. But icon fonts get replaced as well, which makes for a frustratingly broken experience.

http://fontawesome.io/accessibility/

As a first step to providing better accessibility, we can "hide" the font icons from the accessibility tree. 

`aria-hidden="true"`

**Comment by carolyncole** [comment]
Here is the output from bgrep : https://gist.github.com/cam156/200e9c0869ed1c4246f272ac50e3e357

**Comment by carolyncole** [comment]
So only update the views in ScholarSphere.  Ignore the ones in the other gems for now.

**Comment by mtribone** [comment]
Need to replace `<i>` with `<span>` and add `aria-hidden="true" to both glyphicons and fa icons.
