### ISSUE TITLE
About and Help Pages Need Better <head><title> and Page H1

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#512]
"Web pages should include a TITLE tag within the HEAD area, and the title should be unique to each page on the Web site. The TITLE can be repeated as the H1 of the page."

http://accessibility.psu.edu/titleshtml/

About Page
`<title>Show Page // ScholarSphere</title>`
`<h1>` is missing

Help Page
`<title>Help Static // ScholarSphere</title>`
`<h1>Help</h1>`

**Comment by carolyncole** [comment]
`About | ScholarSphere`
`Help | ScholarSphere`
