### ISSUE TITLE
Empty Link Elements for Social Media Icons

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#514]
We may not be able to do much about this since we use an outside resource, but the links for the social media icons are empty. The SVG is in a `<div>` that is `aria-hidden="true"` which is good, but there isn't any text _inside_ of the link. The link has a `title` attribute, but this is not read consistently with all assistive technology.

Proposing that we use a `<span>` inside the link that says Tumblr, Twitter, Facebook, etc. and hide it visually.

**Comment by carolyncole** [comment]
`<span class="sr-only">Tumbler</span>` needs to be added for each case
