### ISSUE TITLE
File Set Show <head><title> Content Can be Better

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#516]
"Web pages should include a TITLE tag within the HEAD area, and the title should be unique to each page on the Web site. The TITLE can be repeated as the H1 of the page."

http://accessibility.psu.edu/titleshtml/

We could do a little better job with the `<head><title>` and the work `<h1>` even though they both can be the same. Per the example on the accessibility site, we could give the `<head><title>` some context about its relationship in the site.

Currently, the file set `<head><title>` doesn't provide any meaningful context. It is literally `Show File Set // ScholarSphere`.

Better Example
1.  "File Set Title | I am the Work Title | ScholarSphere"

**Comment by carolyncole** [comment]
```
Edit File| Star Wars Interfaces| File id: 70r967436w| ScholarSphere
File| Star Wars Interfaces| File id: 70r967436w| ScholarSphere
```
