### ISSUE TITLE
Use Underline for Visual Treatment of Hyperlinks System-Wide

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#517]
Even though stylistically the hyperlinks not being underlined and a slightly different color is a thing in Bootstrap and other modern frameworks, without the default visual cue of an underline people with vision or color impairments may have a hard time distinguishing links in body text.

It would be best to underline hyperlinks like facets, keywords, work and collection titles, pagination,  etc. Otherwise people new to the system may not understand the conventions used and have to explore to understand what is clickable.

![screen shot 2016-12-20 at 1 11 42 pm](https://cloud.githubusercontent.com/assets/4163828/21362447/651b33aa-c6b6-11e6-8f06-4ce40c0b988e.png)

![screen shot 2016-12-20 at 1 13 58 pm](https://cloud.githubusercontent.com/assets/4163828/21362452/6aff6dd6-c6b6-11e6-9f8c-4d6b60db1178.png)

**Comment by mtribone** [comment]
Change all links over gray, like zebra stripe, to #265986 for better contrast.

**Comment by carolyncole** [comment]
This could be many css changes to get all the links not just the a tag
