### ISSUE TITLE
Darken Link Colors when Over Grey or Zebra Stripe

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#518]
Contrast ratio for hyperlinks over grey and/or the zebra stripe in tables isn't high enough to pass current accessibility requirements. Use recommended link color from the WAVE accessibility tool.

Double A: #2d699e
Triple A: #265986

![screen shot 2016-12-20 at 2 35 46 pm](https://cloud.githubusercontent.com/assets/4163828/21365150/fe66a1ce-c6c1-11e6-948d-f9b4d6b98a44.png)

**Comment by carolyncole** [comment]
We will just darken the text color everywhere.  Override bootstrap declaration with a very specific css override for the color.
