### ISSUE TITLE
Changing the ID generation string to include one more letter of number

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#519]
Instead of reworking the import it was suggested that we could just change out minter template to make the new ids generated longer than the older ids so no old id would get used for creating new files.

What do people think?  Is an 11 digit id ok with everyone? @olendorf you have the final say...

**Comment by carolyncole** [comment]
If we change the template we need to remove the state file for the template change to take affect.

**Comment by olendorf** [comment]
fine with me. I don't think the library has a real stance on this other than that they are indeed unique and it works.
