### ISSUE TITLE
Show "uploads in progress" message for files loaded remotely

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#520]
When uploading large files from Box or Dropbox, the fileset will display showing zero bytes until the file is finished being ingested. We should not display the fileset until this is finished and show an "in progress" message as we do with local uploads.

**Comment by carolyncole** [comment]
An adjustment that is made in the job to set and unset flags that are used in the view.  These flags exists and are being set in the AttachFilesToWorkJob.

**Comment by carolyncole** [comment]
Since the remote files are all done inline this is not needed
