### ISSUE TITLE
Editing a Collection throws ArgumentError

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#527]
When I select to edit a collection from my Collection Listing using the dropdown OR by viewing the Collection Show Page and selecting the edit button, I get an ArgumentError.

`wrong number of arguments (given 0, expected 1)`

**Comment by mtribone** [comment]
This does not happen in QA, it only happens locally with the latest develop branch.

**Comment by mtribone** [comment]
<img width="1372" alt="screen shot 2017-01-06 at 9 18 37 am" src="https://cloud.githubusercontent.com/assets/4163828/21720440/31f3479a-d3f1-11e6-95a7-f446b4e97459.png">

**Comment by carolyncole** [comment]
Change render_404 override in application controller to not require a an exception.
