### ISSUE TITLE
Contrast Error for Bootstrap Buttons and Labels

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#528]
The colored buttons and labels from Bootstrap with white text do not have sufficient contrast between background and text to pass minimum requirements.

http://webaim.org/standards/wcag/checklist#sc1.4.3

We can do either increase the text size of elements like buttons and the visibility labels OR we can darken the the colored background.

**Comment by carolyncole** [comment]
Any button on the screen with a default bootstrap css for example:

![screen shot 2017-01-06 at 9 05 37 am](https://cloud.githubusercontent.com/assets/1599081/21720120/5f744f04-d3ef-11e6-9d66-3e3eb879b7ff.png)
![screen shot 2017-01-06 at 9 06 16 am](https://cloud.githubusercontent.com/assets/1599081/21720123/65ec5408-d3ef-11e6-88d3-1ee921d5fa8d.png)

**Comment by carolyncole** [comment]
Override button-info, button-success...  all in the style sheet.  Preference to increase the font size.

**Comment by carolyncole** [comment]
Need the wav accessibility toolbar in chrome to verify the changes
