### ISSUE TITLE
Unable to batch create works using files from Box

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#533]
On QA, when selecting multiple files from Box to batch create works, it won't be successful unless these two criteria are met:

1. none of the file names have spaces
2. you enter your PSU ID in the creator field

Oddly, neither of these criteria are needed if you upload one (1) file via batch create. However, if you upload more than one, and one of the files has a space OR you don't use your PSU ID in the creator field, you'll see these errors in Resque:

No locks available @ rb_file_flock - /dlt/scholarsphere/shared_qa/minter-state

I was unable to reproduce these behaviors locally. It appears to only affect QA at the moment. I've also seen other Resque errors and irregular paths paths getting created in Fedora, but I haven't been able to consistently reproduce them. Ex:
![weird-path](https://cloud.githubusercontent.com/assets/312085/21783997/b828a736-d687-11e6-8548-0c1299b45370.png)

**Comment by carolyncole** [comment]
@awead I tested this and I got flock errors using my user id as the depositor.  I think it is related to the fact that the minter state file is now being stored on the isilon and not the regular disks.  We saw flock errors when the minter state file was originally on isilon in the very first iteration of ScholarSphere.  I wonder if we should change to use the database implementation of the noid.  I also wonder if Share Notify is causing issues when the creator is not a PSU person.
