### ISSUE TITLE
Uploading a new version fails ingest

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#537]
To reproduce:

1. Create a new work with a single file
2. Edit the file set
3. Add a new version of the file
4. Check the Resque admin page

*Note:* this problem only appears in QA, so it's likely a configuration problem with the multi-server setup.

This is the error from Resque:
```
Class
  ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
Arguments
  ---
  job_class: IngestFileJob
  job_id: 76307ebd-6bd6-4261-8dd4-760b95e900a3
  queue_name: files
  arguments:
  - _aj_globalid: gid://scholar-sphere/FileSet/sj3860811v
  - "/tmp/RackMultipart20170111-31822-1qlckni.png"
  - _aj_globalid: gid://scholar-sphere/User/9
  - mime_type: image/png
     filename: TARDIS2.png
     relation: original_file
     _aj_symbol_keys:
     - mime_type
     - filename
     - relation
  locale: en
Exception
  Errno::ENOENT
Error
  No such file or directory @ rb_sysopen - /tmp/RackMultipart20170111-31822-1qlckni.png
```

**Comment by carolyncole** [comment]
The job seems to be looking in the wrong place for the file.  This only occurs in QA.

**Comment by carolyncole** [comment]
This could be related to Dir.tempdir being set current directory.

**Comment by carolyncole** [comment]
We put this back into in progress because, the ingest no longer failed in resque, but we did not see the thumbnail being update.

**Comment by awead** [comment]
@cam156 I've tested this multiple times and it's worked for me on QA. I'm unable to reproduce the problem. I'm uploading a file, followed by a new version, and then restoring the original. Each time the thumbnail is updated. See https://scholarsphere-qa.dlt.psu.edu/concern/file_sets/nzs25x855j

At this point, I don't know how to proceed.

**Comment by awead** [comment]
@cam156 Ok, I have seen this now, but it looks like it's related to stale urls. Do we want to create a new ticket for this since it's an unrelated issue?

**Comment by carolyncole** [comment]
@awead Yes.  That seems reasonable.  
**Special note when demoing! CRTL refresh page to see thumbnail change**
