### ISSUE TITLE
Add Google analytic configuration changes to migration instructions

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#542]

**Comment by carolyncole** [comment]
#382 needs to be complete first

Add the key example to https://github.com/psu-stewardship/scholarsphere/blob/develop/config/scholarsphere.yml
Also add the instructions for changing the server to the documentation created in #382

**Comment by awead** [comment]
see http://sites.psu.edu/dltdocs/?p=3521 and https://github.com/psu-stewardship/scholarsphere/wiki/Fedora-4-to-Sufia-7-(PCDM)-Migration-Information#tasks-prior-to-production-deployment-todo-these-are-a-copy-from-last-time
