### ISSUE TITLE
Configure large file workflow on QA

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#546]
Configure the FileSystem in browse everything so large files can be uploaded on QA

**Comment by carolyncole** [comment]
https://github.com/psu-stewardship/scholarsphere/blob/develop/config/sample/browse_everything_providers.yml#L3
We should match what is being done in production and staging

**Comment by awead** [comment]
I've updated QA to point to `/dlt/scholarsphere/upload_qa/browse_everything_file_system` with the same file size limitations as staging and production.
