### ISSUE TITLE
Add Figaro configuration to migration instructions

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#553]
We need a `application.yml` shared file for each server. See 1705124f0f649ca653e37084a335d74ddb691b8f

**Comment by carolyncole** [comment]
We need to create a sites page that give the information for the file.

**Comment by carolyncole** [comment]
The file already exists on QA, but one needs to be created for Demo, Staginging, & Production along with the sites documentation.

**Comment by awead** [comment]
http://sites.psu.edu/dltdocs/?p=3521
