### ISSUE TITLE
Merge scholarsphere.yml config into application.yml

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#554]
This would refactor our current config method that uses `config/scholarsphere.yml` and replace it with `config/application.yml` which Figaro uses. The Figaro gem was installed to manage the temp. directory environment variable, but could be used to manage any other kind of system-specific variable.

**Comment by awead** [comment]
See related: #542 #553

**Comment by carolyncole** [comment]
Change application.rb to use figaro and move the information into application.yml instead of scholarsphere.yml
