### ISSUE TITLE
As a research data librarian and repository product owner I would like to get notification of when datasets are uploaded so I can work with the creators to better curate them

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#558]
Looking over the research data sets in the repo, most of them are pretty bad as far as documentation goes. Until we get a more formal mediated deposit going on, would it be possible to get at least email notification when a dataset is uploaded? I can then contact the creators to try and improve the, usually with a readme file, but sometimes other things.

**Comment by carolyncole** [comment]
This is currently just for dataset resource type, but should be done s a list of configured types can be sent.

**Comment by olendorf** [comment]
I'm closing this, because I essentially get this from the reports.
