### ISSUE TITLE
Admin Stats page is empty

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#561]
When I click on Administration
Then I get forwarded to the Administration page
When I click on statistics
Then I end up on an empty white page

<img width="949" alt="screen shot 2017-01-19 at 7 17 55 am" src="https://cloud.githubusercontent.com/assets/1599081/22106594/6e76a2c2-de17-11e6-8819-35c9fcbf90b4.png">

**Comment by carolyncole** [comment]
This is related to the users that have deposits not being in the database on QA:
https://github.com/projecthydra/sufia/blob/7.2-migration/app/services/sufia/statistics/depositors/summary.rb#L20

I think that the simplest solution would be to run this code from HttpHeaderAuthenticatable for each user that has "deposited".  
```
            u = User.create(login: user, email: user)
            u.populate_attributes
```
Possibly create a rake task so that when we go into production we can just run it to be certain this error will not creep up on us...

**Comment by carolyncole** [comment]
This could be a non blocker, but we would need to support and request for information in the meantime.

**Comment by awead** [comment]
https://scholarsphere-qa.dlt.psu.edu/admin/stats
