### ISSUE TITLE
Batch upload link is hidden

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#591]
Where is the link on the page (where is waldo) see if you can find it...

<img width="1436" alt="screen shot 2017-02-02 at 1 07 15 pm" src="https://cloud.githubusercontent.com/assets/1599081/22562092/18e114d6-e949-11e6-8b6b-74182ec5747b.png">
`To create a separate work for each of the files, go to Batch upload`

**Comment by awead** [comment]
@mtribone do you want to field this one, or give me some pointers? I'm a little UI-challenged here.

**Comment by mtribone** [comment]
@awead Maybe we can trade or pair because I'm JS challenged with #640
