### ISSUE TITLE
Add A New Work Help text

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#592]
Need help for what a Work is in the context of ScholarSphere below `New Work`.  Also mention what is a collection. Refs #591

<img width="766" alt="screen shot 2017-02-02 at 1 09 31 pm" src="https://cloud.githubusercontent.com/assets/1599081/22562045/e6d85b48-e948-11e6-947c-3b54d8c8ebe8.png">

**Comment by carolyncole** [comment]
depends on #604

**Comment by olendorf** [comment]
A **work** consists of one or more files that work together as a functional unit. This might be software, a research project, or a presentation with associated images. If you are uploading multiple files that are more related by theme, considering creating a **collection** instead.

**NOTE: ** If you are uploading files in multiple directories, they will be flattened into a single directory. If this behavior is not desirable, please zip up your files and upload the zip file instead.
