### ISSUE TITLE
Add New work Tab Labels

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#595]
Descriptions should be Metadata
Relationships should be Collections
Share should be Collaborators

**Comment by mtribone** [comment]
Should this change happen on the fileset edit page, too?

<img width="1257" alt="screen shot 2017-03-15 at 1 43 12 pm" src="https://cloud.githubusercontent.com/assets/4163828/23962728/6dfbfa4c-0985-11e7-8d49-1553a7eab34a.png">
