### ISSUE TITLE
Browse Everything check box should appear with each file.

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#598]
Having the select all boxes but not an box each item.

<img width="565" alt="screen shot 2017-02-02 at 1 37 30 pm" src="https://cloud.githubusercontent.com/assets/1599081/22562982/c8886c42-e94c-11e6-8a1a-cf2fa342db39.png">

**Comment by carolyncole** [comment]
I think we should still do this in the browse everything gem.  We are not yet at gem freeze and there are not many changes to the gem so this adds little risk.

**Comment by carolyncole** [comment]
I'm wondering if we could add a quick fix for a truncation issue while in the gem.  When I have a really long folder name in Box it just truncates the name.  When I have a really long folder name in Browse everything items get pushed to the side.   I was hoping when we were in adding the check box we could also truncate the display.

![screen shot 2017-02-27 at 9 35 01 am](https://cloud.githubusercontent.com/assets/1599081/23366961/abc0e06a-fcd6-11e6-9b4a-115411d7f2bf.png)

![screen shot 2017-02-27 at 10 22 54 am](https://cloud.githubusercontent.com/assets/1599081/23367017/c54dabe4-fcd6-11e6-971f-21abad325def.png)

**Comment by awead** [comment]
@cam156 I'm not seeing that. Which browser are you using? I have a screen shot, but it's not uploading... probably due to the S3 outage.

**Comment by carolyncole** [comment]
@awead do you have a really long folder name in you box folder?  It only happens when the name should be truncated.

I shared with you a very long folder in box so you should see it.

**Comment by awead** [comment]
@cam156 ok, now I'm seeing it. It only affects folders and not files so we ought to be able to apply the same truncating process to the folder names.

**Comment by awead** [comment]
Fixed now with https://github.com/projecthydra/browse-everything/pull/151
![box](https://cloud.githubusercontent.com/assets/312085/23468686/72fabcca-fe6f-11e6-8465-4410dbe7753c.png)
