### ISSUE TITLE
When Uploading folders with file structure warn the user that the structure will be flattened

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#599]
Suggest that the user can upload a zip if they want to create structure.

Add it as help text for the files tab.  Add it down with the buttons.

**Comment by carolyncole** [comment]
If #600 verification fails then we need to put the help text above all upload buttons.  If we are keeping track of the folder in the local files the put it down by the cloud providers buttons

**Comment by awead** [comment]
@cam156 should #600 be done first?

**Comment by carolyncole** [comment]
@awead Yes.  Let me pull that into the sprint.

**Comment by carolyncole** [comment]
@awead and others I confirmed that the help text need to be above all the buttons.  We are NOT keeping relative on either the work of the file set

**Comment by carolyncole** [comment]
In new Work the wording should not say separate work
