### ISSUE TITLE
Browse everything add labels for timing

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#602]
Add submit ("This may take a while")
Make sure the mouse spinner happens over selection as well as outside.  Currently only occurring outside the browse everything modal.

**Comment by awead** [comment]
@cam156 we're in gem freeze now. Do we want to try and do this in Scholarsphere or sneak another BE update in?

**Comment by carolyncole** [comment]
@awead Have any other changes been made to BE?  If not then it should be low risk to add another change.

**Comment by awead** [comment]
@cam156 yes, in fact, I still need to cut a new release for us. We're running off of master at the moment. I could add this other change and then release the version that we'll use.

**Comment by awead** [comment]
@cam156 When/where does the "This may take a while" text appear? Presently, when the submit button is pressed, it's greyed-out and replaced with the text "Loading..." Do you want to change that or have something in addition to it?

I fixed the mouse spinner issue in a recent commit: https://github.com/projecthydra/browse-everything/commit/d841ec74b848f9818e1745cb041b0f8d1e3200f3#diff-0a43a9fbdccde442ca9a8005c537e169R185

**Comment by carolyncole** [comment]
@awead this may already be completed.  The text was to be added after the user hits the submit button.  The user selects files, and then they hit submit, and browse everything goes off into lala land.  Before lala the user should be notified that this may take a few minutes.

**Comment by awead** [comment]
We've agreed to call this done. The recent commit mentioned above has resolved this issue.
