### ISSUE TITLE
Create the Help Text for Collection vs Work

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#604]
We need help text to help the user decide if they want to create a work or a collection.

What should the wording for that be?

**Comment by olendorf** [comment]
Create a **work** if you have one or more files that work together as a cohesive unit. For example, software or data with analyses. Create a **collection** if you have multiple items that have a common theme, for instance presentations on a topic.

**Comment by olendorf** [comment]
This needs to be reassigned to someone else so I'm taking my name off it.

**Comment by carolyncole** [comment]
This should be added to the Batch Upload page

**Comment by awead** [comment]
@cam156 is this *only* on the batch upload page?

**Comment by carolyncole** [comment]
@awead there is an analogous ticket for the work upload page

**Comment by awead** [comment]
@cam156 should be combine them then?

**Comment by carolyncole** [comment]
@awead this ticket is only for the batch upload.  There is another ticket: https://github.com/psu-stewardship/scholarsphere/issues/592  which put the correct text for a work on that page.

**Comment by mtribone** [comment]
I feel as though I took care of this already. Ah. No. Just in the work.

**Comment by carolyncole** [comment]
Add the text to the new  Collection Page in addition to the new work oages

**Comment by mtribone** [comment]
Do we need the file structure text on the new collection screen? You don't upload files in a collection. You add works. and works have the file structure text.
