### ISSUE TITLE
Update descriptions of edit fields to explain why they are required

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#605]
`The more descriptive information you provide the better we can serve your needs.`
This should more clearly describe how this serves the needs.

**Comment by carolyncole** [comment]
Define the why for each field.
Change the help text for each field to contain the why
Update the top text to include an overall reason "Better search results"

**Comment by carolyncole** [comment]
@olendorf Please create the language for the why.

**Comment by olendorf** [comment]
### Creator
This makes sure that this item can be searched on all the creators' names.

### Title
A descriptive title will make it much easier to find your work. Avoid uninformative titles.

### Keyword
Keywords help others find your work and also help build facets.

### Rights
A rights statement or license ensures your work gets used appropriately and that you get credit when your work is used.

### Abstract or Summary
Providing a concise but informative description greatly increases the ability of search engines to index your work . It also helps others quickly understand the content of your work.

### Resource Type
Defining the correct resource type allows others to quickly find the type of content they need.

**Comment by olendorf** [comment]
@cam156 I put in some brief explanations. I will revisit them Monday with a fresh eye, but feel free to edit.

**Comment by mtribone** [comment]
@cam156 @olendorf These "why" descriptive edits are to _replace_ the current help text for the required metadata?

**Comment by carolyncole** [comment]
@mtribone good question, I would have thought they we additive.

**Comment by mtribone** [comment]
The ticket does say "Update" but I was just concerned about wordiness. Let me pop them in and we'll take a look at the results.
