### ISSUE TITLE
Missing Content on Production ScholarSphere

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#610]
Here are the files that have no content in the production version of ScholarSphere.  They are organized by depositor.

1. Jacob Tyler Shreve  (jus57)                                       
   1. VirGA-VM_v1-1.vdi https://scholarsphere.psu.edu/files/8623j023c
       * there are no other copies of the file in the system
1. Dolores Lavon Pavliska (dlp5189)
   1. AU-Mito_Transcription-16.pdf https://scholarsphere.psu.edu/files/8623j317v
      * There are 4 other files in the system with the same title deposited by Dolores
         1.  https://scholarsphere.psu.edu/files/8623j3604
         1.  https://scholarsphere.psu.edu/files/8623j390v
         1.  https://scholarsphere.psu.edu/files/8623j3515
         1.  https://scholarsphere.psu.edu/files/sf268m854
      
   1. AU_3C-Mutants_RNA_binding-1.pdf https://scholarsphere.psu.edu/files/8623j3850
      * There are 2 other files in the system with the same title deposited by Dolores
         1.   https://scholarsphere.psu.edu/files/8623j335s
         1.   https://scholarsphere.psu.edu/files/sf268m75w

1. Md Tarekul Alam (mta143) 
   1. march 14_baoming_WS2/ https://scholarsphere.psu.edu/files/vm40xr584
       * There is one other file in the system with a similar title, "march 14_baoming_WS2.zip"
          1. https://scholarsphere.psu.edu/files/tb09j575m

1. Jennifer Lynne Van Hook (jxv21)
   1. __MACOSX/ https://scholarsphere.psu.edu/files/zc77sq19f
      * There are no other files with this title

1. Linda Musser (lrm4)
   1. (no title) https://scholarsphere.psu.edu/files/fx719m462
   1. (no title) https://scholarsphere.psu.edu/files/9s1616164

**Comment by carolyncole** [comment]
I found another one without any title or descriptive metadata

Yao Zehng (yzz122) https://scholarpshere.psu.edu/files/7d278x872

**Comment by olendorf** [comment]
@cam156  

Jacob Tyler Shreve and Moriah Szparza are both no longer at the University. Also, I am looking at all the related files here https://scholarsphere.psu.edu/files/8623j328c and I haven't found one yet that works. They are private. Delete?

Dolores Lavon Pavliska 
Looking at those and all the related ones. None work and they all seem private. Also no longer at the University.

Md Tarekul Alam
Same story. All private, no longer at he university.

Jennifer Lynne Van Hook


__MACOSX/ https://scholarsphere.psu.edu/files/zc77sq19f 
This one looks like a mistake too, but the related file is there.  Delete the _MACOSC one.

The Musser ones too have nothing. I will talk to her, I suspect they were mistakes.

**Comment by olendorf** [comment]
Just delete all this content. Just make sure that Jennifer Lynne Van Hook's one good file associated with the _MACOSX remains.

**Comment by carolyncole** [comment]
Deleted files from production.
