### ISSUE TITLE
Edit Actions on the Items Contained within a Collection

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#619]
Duplicate of #2409

**Comment by carolyncole** [comment]
https://github.com/projecthydra/sufia/issues/2409

**Comment by carolyncole** [comment]
Remove the delete work from the collection action list.

**Comment by mtribone** [comment]
This looks like it has already been done?

<img width="1091" alt="screen shot 2017-02-22 at 2 49 41 pm" src="https://cloud.githubusercontent.com/assets/4163828/23229423/3a2cb56c-f90e-11e6-9897-72fa6a01ad66.png">

**Comment by carolyncole** [comment]
This is from the Edit screen not the show screen.  I know the two are confusing.  We still have the ability to delete the work.  See screen capture:

<img width="1380" alt="screen shot 2017-03-13 at 10 39 50 am" src="https://cloud.githubusercontent.com/assets/1599081/23859345/af8fa060-07d9-11e7-9eab-f2d7543c3479.png">
