### ISSUE TITLE
As a user I would like to download an entire collection 

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#624]
Probably just do it as a zip file of the contents.

**Comment by carolyncole** [comment]
One zip file for all works in the collection.  Zipping up the zip file for each work in the collection.  Dependant on #625

**Comment by carolyncole** [comment]
After the button is clicked the user will get feedback to say that the zip is being created, and then data will then be returned when it is done.  Help information beside the button saying this may take some time.

**Comment by carolyncole** [comment]
We may want this to be a different route than download to have the ability to block robots.
