### ISSUE TITLE
As a user I would like to download all the files in a work at once so that I spend less time downloading.

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#625]
Probably just do it as a zip

**Comment by carolyncole** [comment]
This is also desired for a collection.  We may need to look into maximum sizes and create multiple files that get downloaded

**Comment by carolyncole** [comment]
Create on zip with the entire content set into a zip file named based on the title of the work.  No metadata will be included. allow for download.  Do this on the fly when it is requested.

**Comment by carolyncole** [comment]
After the button is clicked the user will get feedback to say that the zip is being created, and then data will then be returned when it is done.

**Comment by carolyncole** [comment]
Need to be capturing google analytics for the download
