### ISSUE TITLE
File Names in the list of Files in a Work get Page Title

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#628]
File Names in the list of Files in a Work get Page Title and not the name of the file. This is most likely caused by my work on the page titles versus head titles. 

https://github.com/psu-stewardship/scholarsphere/pull/555 and https://github.com/psu-stewardship/scholarsphere/pull/538

https://github.com/psu-stewardship/scholarsphere/blob/333198f71a5ea150236b1b82fd6757cb1732fccc/app/presenters/file_set_presenter.rb#L17

<img width="1085" alt="screen shot 2017-02-08 at 2 51 36 pm" src="https://cloud.githubusercontent.com/assets/4163828/22754700/73592df8-ee0e-11e6-8fc3-fa696f874dc4.png">

**Comment by carolyncole** [comment]
Need to make sure that the tab and the listing both show the right information.  The listing should show the first title and the page title should show all the items.
