### ISSUE TITLE
Date Uploaded and Date Created inconsistency

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#629]
There is a date uploaded sort. There is a date created field shown in the metadata but its just a string field with any data. This is potentially confusing, how should we handle it?

**Comment by awead** [comment]
The date created field allows someone to put in fuzzy dates without having to adhere to a format, and we don't run into indexing problems. Date uploaded is a real date, and indexed as such, so you can do the sorting. I agree, though, it's confusing.

**Comment by carolyncole** [comment]
Modify the search results to show date uploaded & remove Date Modified from the sort.  You catalog controller for both of these.
