### ISSUE TITLE
Collection list view page doesn't view properly

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#630]
The items are spewed all over the page.

![image](https://cloud.githubusercontent.com/assets/857767/22797339/d99169ba-eecb-11e6-8732-45efa9847f19.png)

https://scholarsphere-qa.dlt.psu.edu/catalog?f%5Bhas_model_ssim%5D%5B%5D=Collection&q=&view=list

**Comment by carolyncole** [comment]
Duplicate of #633
