### ISSUE TITLE
Facets should be case insensitive

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#632]
Having case sensitive sorting of facets may not be the best way to do it.

Also how to handle a clever reordering of names yielding meaning

**Comment by carolyncole** [comment]
Change the ALL 9 solr facet result to be white space, punctuation and case agnostic.
"Patricia  Hswe" ~= "Patricia Hswe"
"PATRICIA HSWE" ~= "Patricia Hswe"

This may be accomplished in the solr schema or via another solr field created by to_solr.  We do not have a preference, but if solr changes then the chef scripts will need to be updated.
