### ISSUE TITLE
Collections are not being displayed correctly in the search

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#633]
![screen shot 2017-02-10 at 7 01 56 am](https://cloud.githubusercontent.com/assets/1599081/22826149/eec440f8-ef5e-11e6-8781-2428a9987b45.png)

To reproduce this problem, 
 1. click on the search box without a search term to get all results
 1. click on the object type facet and choose collections

Notice the facets are missing.

**Comment by carolyncole** [comment]
collections are the worst, but regular objects are also having an issue.  I think one of the more recent commits may have caused this bug.  The gallery view is ok.

![screen shot 2017-02-10 at 7 17 55 am](https://cloud.githubusercontent.com/assets/1599081/22826601/40302dec-ef61-11e6-9f8b-18e5b60701c1.png)

**Comment by carolyncole** [comment]
I can fix this by reverting this commit: ad9ebe4872017cb370f

**Comment by mtribone** [comment]
I think we have some Bootlint errors that may be contributing to the issue.

![screen shot 2017-02-10 at 11 18 58 am](https://cloud.githubusercontent.com/assets/4163828/22834359/dfba4ea8-ef82-11e6-81ff-1896b1742f70.png)
