### ISSUE TITLE
Visibility label and Radio Buttons

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#641]
reword the header for the section "Choose Visibility" instead of "Visibility." Also we have combo boxes inside of radio buttons for lease and embargo that need to be reevaluated. They weren't expected when reading the screen.

**Comment by carolyncole** [comment]
During the edit or create new work change the visibility heading, move the input outside of the label and make sure to use label for, and also make sure the embargo and lease read properly when selected.
