### ISSUE TITLE
Show Status or Feedback after saving a Work

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#643]
A user creates a new work by adding the required metadata, visibility, and uploads files to be processed. Then checks the deposit agreement and hits save. 

System starts to process files, the save button is greyed out, but there is no indication that something is happening. Both sighted and users of screen readers asked for more feedback during this process, i.e., a status bar or percent complete.

**Comment by carolyncole** [comment]
This should be read and visually shown.  "We are you saving your work this may take a few moments"  I think to get the screen reader to read this content on the fly the div will need to be labeled with aria-active.
