### ISSUE TITLE
Contributor is a facetable link but there's no listing

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#659]
If I have a record with contributor, then I can click on the value in the field at it will execute a facet search using the contributor as the facet. However, contributor is not listed as a facet on the left-hand side in the search results. Perhaps it should be?

**Comment by awead** [comment]
For consistency, I'm going with "yes" because it also informs how #632 works as well.

**Comment by carolyncole** [comment]
We should clean the link, but not show the facet.

**Comment by carolyncole** [comment]
No need to fix this.  It is not needed as a facet
