### ISSUE TITLE
Batch is not related object but a new metadata field

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#664]
We need a new metadata field on the GenericWork for allowing the old batch information to be preserved.  I am not sure of the actual metadata RDF property we would like to use, but we want something that means upload set (uploaded together), which is what a batch really was.

We need to add the field to the GenericWork and then change the Batch Translator to populate that field instead of the Related Object field.

**Comment by carolyncole** [comment]
Rdf predicate should be determined
RDF predicate need to be added to the work
Batch translator needs to fill in the field with the id

**Comment by awead** [comment]
@cam156 @olendorf have we determined which predicate we're using?

**Comment by carolyncole** [comment]
Assigning to @olendorf to choose the predicate.

**Comment by carolyncole** [comment]
I went looking for a predicate while I was waiting for data to clear.  I asked around on the hydra metdata channel and got a bit of help:

**Comment by carolyncole** [comment]
Carolyn [2:12 PM] 
Could I use something like http://www.essepuntato.it/lode/http://purl.org/co is_element_of ?

Julie Hardesty [2:23 PM] 
that's possible. it doesn't have a range limitation that it has to be a URI so a string value should work.

[2:24]  
the only other thing I was coming across might be https://raw.githubusercontent.com/timrdf/csv2rdf4lod-automation/master/doc/ontology/vocab.ttl# conversion:dataset_identifier

**Comment by carolyncole** [comment]
We should use our own key upload_set to keep this information.  This could be an expansion of dublin core related resource.

**Comment by carolyncole** [comment]
This was run on QA and you can see in this image the upload_set was set by the translator:

<img width="897" alt="screen shot 2017-04-04 at 11 07 48 am" src="https://cloud.githubusercontent.com/assets/1599081/24663822/04a38298-1927-11e7-9054-f888e9d080e7.png">
