### ISSUE TITLE
Search Test Automation

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#7]
Testing Object Search:
1. Connect to https://scholarsphere-staging.dlt.psu.edu/
2. Choose a key term from the recently uploaded and put it in the search bar
3. Verify that recent file shows up along with any other files
4. Choose an item from every facet and search for each
5. Verify that you get at least the facet count (it may find more since the search is broader than the facet)
6. Choose a key from the keywords facet
7. Verify that the expected number of files show up
8. Choose another facet to slim down the results
9. Verify that the expected number of files show up
10. Choose a facet from each list and verify that the count is the same as the count in the facet list
11. Log in using the Login button at the top right of the page and repeat all steps up to this step
12. Choose a .pdf document and down load it to view the content (or look at the thumbnail).
13. Pick an obscure word from the content and put it into the search bar
14. Verify that the document you chose shows up in the search

**Comment by mjgiarlo** [comment]
This for building out a new feature spec?  Looks awesome!

**Comment by mjgiarlo** [comment]
:metal:

**Comment by carolyncole** [comment]
Yes we are enlisting West Arete to help out.  I am putting the script from redmine here so they can have access.
