### ISSUE TITLE
Redirect to collection show page

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#702]
If I am creating new works
And a collection is specified
When I click "Save"
I should redirect to the collection show page

**Comment by carolyncole** [comment]
Given I am viewing an existing collection 
And I click on "Add new works"
When I upload Files
And Add metadata
And click Save
Then I should get redirected to the collection show page

Given I am creating a new collection 
And I click on Create Collection and Upload Works
When I upload Files
And Add metadata
And click Save
Then I should get redirected to the collection show page

When I batch create works 
And I select a collection 
Then I should get redirected to the collection show page
