### ISSUE TITLE
Feedback for collections being modified

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#703]
If a collection is having items added to it
Then the user should see a message indicating that this process is underway
And should display until all the items have been added to it.

**Comment by carolyncole** [comment]
Investigate if there is a background job being used at any point in the process.  Could be when we deposit works directly into a collection.

**Comment by carolyncole** [comment]
This is done when we can write a ticket that specifies the exact workflow why we would need this OR we do not need this period.

**Comment by awead** [comment]
There aren't any background jobs that add items to collections, it's all processed inline in CurationConcerns::CollectionsControllerBehavior.

https://github.com/projecthydra/curation_concerns/blob/b073550c40a1c1088f85970aa8c0e9538bc2d5ce/app/controllers/concerns/curation_concerns/collections_controller_behavior.rb

**Comment by awead** [comment]
Here are the use cases:
1. **New collection with new single work**
    No feedback needed. After hitting save on the new work, it redirects to the work's page where it shows that it's part of the new collection.
1. **New collection with new batch works**
    Feedback needed.  Redirects to new collection but shows no works.
1. **Existing collection with new single work**
    Same as 1.
1. **Existing collection with new batch works**
    Same as 2.
1. **New collection with existing works**
    No feedback needed. Works are added after save.
1. **Existing collection with existing works**
    Same as above.

I was only able to test this locally, with resque running, because of #665. I really think that it blocks the eventual solution for this issue because we can't accurately test it without have to remove ourselves as admins, which is complicated.

The only use cases that required user feedback are batch upload operations where either a new or existing collection has batches of works added to it. To address this, we should probably use the same approach in 922ff2cd312dcbdfc3fe6145102f261dd2888424 and keep track of which works are going to be added to the collection and remove them from the table as they're added.
