### ISSUE TITLE
Derivative creation failures

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#706]
ImageMagick (IM) cannot convert lsm image files with multiple channels. The Resque job fails with, "Sorry, can not handle RGB image with Color channels=2." However, when running the conversion command from the command line, an image is still created.

Note: The original is still uploaded correctly. It's just the thumbnail derivative that doesn't show.

There are a couple of things we can do:
1. Leave it as-is, with the error in Resque
2. Let hydra-derivatives fail more "gracefully"
3. Capture the error and continue since an image is created, logging the error somewhere
4. Others?

This could also be expanded for any IM-related failure in hydra-derivatives.

**Comment by carolyncole** [comment]
Option 2/3 Handle the failure more gracefully and send a notification to the user that they may upload a representative thumbnail when the derivatives fails.
