### ISSUE TITLE
Processing files with parentheses

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#727]
If the filename has a parenthesis, OpenOffice complains:

```
2017-04-05 10:05:55 -0400 (29520) Rendering 500 page due to exception: #<RuntimeError: Unable to execute command "soffice --invisible --headless --convert-to pdf --outdir /tmp /var/folders/r8/qgwk_gbs1n97yb5q0wt6skgh0000gp/T/Development Team Projects and Milestones (not downloaded).xlsx". Exit code: pid 29699 exit 2
Error message: sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `soffice --invisible --headless --convert-to pdf --outdir /tmp /var/folders/r8/qgwk_gbs1n97yb5q0wt6skgh0000gp/T/Development Team Projects and Milestones (not downloaded).xlsx'
```

**Comment by awead** [comment]
Looks like we need to either escape the spaces and parentheses, or put quotes around the file path. Running the command locally, with everything properly escaped, succeeds in creating the pdf.

**Comment by carolyncole** [comment]
File names should only  include Alpha numeric and dot. This should be fixed in the background for the user.  This can be done as it is ingested.  Add something to the controller, actor, or job to clean the name.  Possibly in carrier wave

**Comment by awead** [comment]
CarrierWave already sanitizes uploaded files, removing non-alphanumeric characters and replacing them with underscores. However, this is a remote file downloaded by BrowseEverything, which doesn't do that... so making it do that, could be a good idea.
