### ISSUE TITLE
I can not save before all the files are done uploading

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#733]
When I choose a large number of files or ones that take a while to upload
Then the save button becomes active after the first file has uploaded
If I hit the save button before all the files have uploaded
Only the ones that have uploaded get added to the work

**Comment by awead** [comment]
Fixed in Sufia https://github.com/projecthydra/sufia/commit/e61cb64322816485a191b69cdb7de2a07519379e
