### ISSUE TITLE
Create collection from my work fails

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#735]
When I go to my works
And I click on the boxes beside one or more works
And I click on Add to collection 
And I click on create new collection
Then I should not get a 500 error

Here is the url that is giving me the 500 error
```
https://scholarsphere-qa.libraries.psu.edu/collections/new?batch_document_ids%5B%5D=5tb09j578b&batch_document_ids%5B%5D=xpn89d889b
```

**Comment by awead** [comment]
I wasn't able to reproduce this with my own works on the either the .dlt .libraries box. It could be something with these specific works that are causing the problem.

**Comment by carolyncole** [comment]
I also can not repeat this.  I'm closing the issue.
