### ISSUE TITLE
As data depositor I would like to see the README files supplied with data sets to be displayed on the splash page so that users can better understand the data set before downloading it.

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#747]
I've had a couple researchers bring this up. They would like to have a better splash page for their data sets. One specifically mentioned Github README support as a really good thing. I think it would help in a few ways.

1. It will provide better documentation of a data project without having to download stuff.
2. It will encourage researchers to write better README files which are the most important documentation they can write.
3. It will enhance the indexing of data sets which are hard to index in general.

**Comment by carolyncole** [comment]
ref #1012

**Comment by carolyncole** [comment]
Duplicate of #1012
