### ISSUE TITLE
As an uploader when uploading a work with a many files from different sources I would like to be able to handle different licensing for different parts of the directory tree so that I can appropriately license my work.

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#776]
Scholarsphere currently applies one license to an entire work. However, sometimes, especially with complex data sets, the work my require multiple licenses. For instance Apache for code, and CC-X for other stuff. Also if they are using other peoples data, it may require that they apply that license.

This may be as simple as allowing no license and letting the user upload license documents much like Github.

**Comment by carolyncole** [comment]
License per files set or a license per directory (if we kept directory)
As part of the work the licenses would be part of the work, so user would need to select a "Licensed Included Work"

**Comment by carolyncole** [comment]
dependant on #213

**Comment by awead** [comment]
@olendorf closed this because you don't want the feature anymore :smile:
