### ISSUE TITLE
Works Shared with Me Label is not correct

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#777]
The "Works shared with Me" list can include collections.  This should be "Shared with me"

**Comment by carolyncole** [comment]
Need to change this line in the tests: https://github.com/psu-stewardship/scholarsphere/blob/develop/spec/features/dashboard/dashboard_shares_spec.rb#L25

Need to add an override for the translation in sufia: https://github.com/projecthydra/sufia/blob/master/config/locales/sufia.en.yml#L167

**Comment by awead** [comment]
@cam156 which release is this in?

**Comment by carolyncole** [comment]
@awead what are you asking about?  The scholarSphere or Sufia release?

**Comment by awead** [comment]
@cam156 I didn't see the Scholarsphere 3.0 milestone, but it's there now... probably just missed it.
