### ISSUE TITLE
Remove fix sticky for save widget

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#778]
Pin the save widget to the top of the screen and add a jump to the top link in the page.

**Comment by mtribone** [comment]
Back to Top Link without additional metadata

![screen shot 2017-04-26 at 9 34 08 am](https://cloud.githubusercontent.com/assets/4163828/25437290/db883c70-2a63-11e7-9e4c-b48317574555.png)

**Comment by mtribone** [comment]
Bach to Top link with additional metadata

![screen shot 2017-04-26 at 9 34 47 am](https://cloud.githubusercontent.com/assets/4163828/25437340/0289618c-2a64-11e7-91b9-af793e6ce4ef.png)
