### ISSUE TITLE
Update the daily Audit to use the sufia audit

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#783]
https://github.com/psu-stewardship/scholarsphere/blob/develop/script/audit_repository

https://github.com/projecthydra/sufia/blob/7.2-migration/app/services/sufia/repository_audit_service.rb

**Comment by awead** [comment]
@cam156 I am deeply suspicious of the Sufia:: RepositoryAuditService. If I forcibly corrupt a file in Fedora, the service doesn't report its failure.

**Comment by awead** [comment]
@cam156 ok, it will recognize a failure. I forced it by removing all the records from ChecksumAuditLog. The failing file looks like:
```
#<ChecksumAuditLog id: 16, file_set_id: "83b5919121", file_id: "83b5919121/files/9eff14dd-9a61-4cdc-819a-006b1fa86...", version: "http://127.0.0.1:8986/rest/dev/83/b5/91/91/83b5919...", pass: 0, expected_result: nil, actual_result: nil, created_at: "2017-05-04 19:54:54", updated_at: "2017-05-04 19:54:54">
```
There's nothing for expected_result or actual_result, but at least it's catching the error.
