### ISSUE TITLE
About Page Upload Link

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#787]
On the about page right before the "Story of ScholarSphere" section, there is a link to "go to our upload page." When I click the link, I get redirected to an error page. 

https://scholarsphere-qa.libraries.psu.edu/files/new

If I right click and open in a new tab, same error

https://scholarsphere-qa.libraries.psu.edu/concern/generic_works/new

unless I do it several times then I get the correct link

**Comment by olendorf** [comment]
seems to work now.

**Comment by awead** [comment]
This is working in production now.
