### ISSUE TITLE
Publication and Curation Services Link on About Page

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#789]
in the "Story of ScholarSphere" section, the link to Publication and Curation Services is broken. Should be:

https://libraries.psu.edu/about/departments/publishing-and-curation-services

**Comment by olendorf** [comment]
Ask Linda Friend about what she wants 

needs to be done along with #826

**Comment by olendorf** [comment]
@cam156  Go ahead and take them off, and put me on as a contact. But don't put the stuff about voice mail, cause I get so few of them, I'll likely not see it.
