### ISSUE TITLE
Admin Pages not Found

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#796]
When I am logged in and direct my browser to `admin/queues` or `admin/stats`, I get a 404 error.

**Comment by carolyncole** [comment]
@mtribone did you reload your groups after I added you back into admin?

**Comment by mtribone** [comment]
@cam156 On QA I get queues but not stats

**Comment by carolyncole** [comment]
@mtribone I think this is related to which groups you are in Stats is one admin group and queues is another.  Can you double check to see if you are still experiencing this issue?  I do not get the same error.

**Comment by carolyncole** [comment]
I think this is related to the database not getting migrated from QA-old to QA-new.  We need to be certain when we backup data from production we not only backup fedora but also the database, and then that database also gets migrated to the new hardware.

**Comment by mtribone** [comment]
@cam156 Both QA-New and Stage-New have the content now.

**Comment by mtribone** [comment]
Nope. Strike that. Just Stage.

**Comment by carolyncole** [comment]
Ran on staging
`mysqldump -p -u fedoraAdmin -h mariadb1test.vmhost.psu.edu ssstagerails users > users.sql`
`mv users.sql /dlt/scholarsphere/config_qa_new/`

On qa-new I ran:
`mv /scholarsphere/config_qa_new/users.sql .`
`mysql -p -u fedoraAdmin -h  mariadb1test.vmhost.psu.edu -D ssqarail < users.sql`

Now we need to run an import and see if the the stats page is still available.
