### ISSUE TITLE
Featured Works only Shows When Logged In

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#808]
If I navigate to SS QA New and am not logged in, the featured works are not featured.

**Comment by mtribone** [comment]
![screen shot 2017-05-01 at 11 17 26 am](https://cloud.githubusercontent.com/assets/4163828/25583449/cf33d4ac-2e5f-11e7-84f4-012fb0ff111a.png)

**Comment by carolyncole** [comment]
@mtribone This is strange.  Are you sure you are looking at the same machine?  When I tried this there was nothing feature on https://scholarsphere-qa.libraries.psu.edu but there was a feature on https://scholarsphere-qa.dlt.psu.edu

**Comment by mtribone** [comment]
@cam156 My bad. If you look at the screen shot, I was on dlt and not libraries.
