### ISSUE TITLE
Rights not Retained when Editing Work

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#810]
When I edit one of my existing works, the required metadata icon turns to a red X and my choice for the rights is no longer selected.

**Comment by mtribone** [comment]
<img width="1068" alt="screen shot 2017-04-27 at 12 17 57 pm" src="https://cloud.githubusercontent.com/assets/4163828/25587863/e94e4458-2e73-11e7-8c67-82ae75f97551.png">

**Comment by mtribone** [comment]
![screen shot 2017-05-01 at 1 39 35 pm](https://cloud.githubusercontent.com/assets/4163828/25587882/072ebebc-2e74-11e7-9330-dcd6e54e4dc6.png)

**Comment by awead** [comment]
@mtribone how old was the existing work? If was created with a rights statement that is no longer present, it would be blank now, i.e. Attribution International 3.0 versus 4.0.

**Comment by mtribone** [comment]
@awead Hmmm...perhaps it was old. I will verify.

**Comment by mtribone** [comment]
Cannot reproduce
