### ISSUE TITLE
Format Facet does not Update after Updating Work

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#818]
On stage when I create a work with one item and then go back later and edit the work by adding more files to the works with differing file extensions, the format facet doesn't update with the new formats.

**Comment by mtribone** [comment]
![screen shot 2017-05-02 at 10 51 25 am](https://cloud.githubusercontent.com/assets/4163828/25623782/be14ed34-2f25-11e7-93b7-be1348a714b6.png)





![screen shot 2017-05-02 at 10 52 28 am](https://cloud.githubusercontent.com/assets/4163828/25623783/be1e8f92-2f25-11e7-94fe-bfadb982593d.png)

**Comment by awead** [comment]
@mtribone the format facet is based on the representative file set, which by default, is the first file. If you change the representative file_set to a different one with a different format, then the facet should change. However, it will only every show one value.
