### ISSUE TITLE
Characterization errors with multiple files

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#829]
This is on QA New

Uploading multiple files via Box produces characterization errors in Resque.

To reproduce, create a single work with four files from Box, such as:
![error](https://cloud.githubusercontent.com/assets/312085/25673518/b3e555d4-3005-11e7-9c74-8848b4ed19f6.png)

After saving, look at the Resque log. One or two of the files will fail with:
```
Worker
ssjobs1qa-new:10649 on files at 2017/05/03 13:32:28 -0400
Retry or Remove
Class
ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
Arguments
---
job_class: CharacterizeJob
job_id: 801866bd-e7ca-4fe2-abd7-5df476cb0884
queue_name: files
arguments:
- _aj_globalid: gid://scholar-sphere/FileSet/sj3860934k
- sj3860934k/files/72809470-dbc5-4e49-afca-1e94ad7ca8a2
- "/scholarsphere/upload_qa_new/tmp/Development_Team_Projects_and_Milestones__not_downloaded_.xlsx"
locale: en
Exception
Errno::ENOENT
Error
No such file or directory @ rb_sysopen - /tmp/Development_Team_Projects_and_Milestones__not_downloaded_.png
```

**Comment by awead** [comment]
OK, this seems to be working now, but see #830

**Comment by carolyncole** [comment]
If I choose the exact same files I also get errors.  I do believe it is related to the format of the file and not the fact that it comes from box.  The files that fail are xlsx files.  
![screen shot 2017-05-08 at 12 30 37 pm](https://cloud.githubusercontent.com/assets/1599081/25814141/5e9aa410-33ea-11e7-98c4-9ef1c9e633f9.png)
