### ISSUE TITLE
Thumbnails are not corresponding to files

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#830]
I'm seeing this in QA old and new:
https://scholarsphere-qa.dlt.psu.edu/concern/generic_works/gqn59q5174
https://scholarsphere-qa.libraries.psu.edu/concern/generic_works/pvm40xt006
https://scholarsphere-qa.libraries.psu.edu/concern/generic_works/t1g05fg289
https://scholarsphere-qa.libraries.psu.edu/concern/generic_works/t1g05fg289

To reproduce: upload a work with many files from Box and look at their thumbnails.

**Comment by awead** [comment]
See #829

**Comment by awead** [comment]
Here's a picture from qa old:

![picture](https://cloud.githubusercontent.com/assets/312085/25674504/067acad8-3009-11e7-9099-2fc464b1e7f5.png)

Thumbnails are named according to the fileset's id, so I think the minter state was reset at some point and old thumbnails were not removed. As a result, a pre-existing id was minted that matched an existing thumbnail. At the very least, it seems, we need to remove old thumbnails, but there's still a question as to whether the minter is minting old ids.

**Comment by carolyncole** [comment]
Need to remove the thumbnails and rerun the import process.

**Comment by carolyncole** [comment]
@pke3 is rerunning the import.  We should check tomorrow to see if the thumbnails are matching up

**Comment by carolyncole** [comment]
I am seeing this today.  There are no instructions for removing the thumbnails as part o the migration.  I believe that may "solve" the issue if those were added.

**Comment by awead** [comment]
`rm -Rf /scholarsphere/[server]/derivatives/*` where server is `qa_new` or `stage_new`

**Comment by awead** [comment]
I'm also curious as to why the system is generating noids that have already been used. Are we dropping all the database files that maintain minter state prior to migration?
