### ISSUE TITLE
Long files in BrowseEverything

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#834]
Long file names get truncated. Hovering over them should display the full filename so you can tell the difference between similarly-named long files.
![be](https://cloud.githubusercontent.com/assets/312085/25746927/9bedad0e-3173-11e7-8ef4-80fc8c862066.png)

**Comment by carolyncole** [comment]
Add title to each file link that  is the entire file name
Create a caption tag for the table with the original table title
Remove title from table
