### ISSUE TITLE
Upload workflow

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#835]
The process for uploading files has some problems. We need to fix the underlying issue in jQuery Upload that is preventing mass uploads (see #453) as well as address interface issues.

More transitions could alert sighted users to changes in the uploads.

**Comment by carolyncole** [comment]
@awead was this fixed by the second upload button?

**Comment by awead** [comment]
@cam156 no, the second button was a hack fix. This ticket is to find a way to fix the problem in jQuery uploader so we don't need that second button. It's also for some accessibility improvements that @mtribone was mentioning to me earlier. We can definitely break this up into different tickets, if you want, I was just registering the issues here.

**Comment by carolyncole** [comment]
We should do some investigation to see if hyrax has solved this issue. We may be able to use the solution from there.  We could investigate other uploaders like shrine.

This will be done when we have decided what direction we want to go and have created a new ticket for the work needed.

**Comment by mtribone** [comment]
Preliminary tests using Nurax indicates that perhaps this problem has been solved in Hyrax. I'll keep uploading some files in multiples of tens to see if it breaks.

**Comment by mtribone** [comment]
@cam156 and I have copied the code from the current version of Hyrax and it seems to perform both locally and on QA. See our branch: [i#835-upload](https://github.com/psu-stewardship/scholarsphere/tree/i%23835-upload)

**Comment by carolyncole** [comment]
@mtribone and I also tried to just use the sufia 7.4 upload screen.  We think we like the hyrax one better,  but it works QA too. https://github.com/psu-stewardship/scholarsphere/tree/i%23835-delete
