### ISSUE TITLE
XSLX files are not getting derivatives generated

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#837]
Derivatives for xslx files are not getting generated on staging.  We need ot determine why this is the case.  I wonder if the version of libre office is updated?

**Comment by awead** [comment]
@mtribone @cam156 

I'm seeing consistent behavior locally and on staging. It isn't exactly "correct" but it appears be functioning correctly.

Given a spreadsheet with a first page that looks like:
![sample-spreadsheet](https://cloud.githubusercontent.com/assets/312085/26002171/d199d43a-36fc-11e7-92b5-8d448c881f95.png)

LibreOffice converts it to a PDF with a first page that looks like:
![sample-spreadsheet-thumb](https://cloud.githubusercontent.com/assets/312085/26002216/f7043e0e-36fc-11e7-8781-6e2d7148e4ea.png)

This is then getting shrunk down to a thumbnail via ImageMagick:
![09-thumbnail](https://cloud.githubusercontent.com/assets/312085/26002236/0ad55d5a-36fd-11e7-8b50-51a050ed7609.jpeg)

So given that the initial PDF conversion is only capturing text without any lines, and only the cells that it's determining can fit on a page, the resulting shrunken image bears little resemblance to the original spreadsheet.

We might be able to tweak the PDF conversion, but LibreOffice's command line parameters are limited. I'm wondering if there should be another ticket to investigate using an icon for xls and xlsx formats, similar to those we use for audio. I'm not really sure the value of spreadsheet thumbnails at this point.

**Comment by mtribone** [comment]
Yeah I could stand behind a default icon for xsl and xslx files.

**Comment by mtribone** [comment]
They don't seem that great in SS 2.0 either
https://scholarsphere.psu.edu/catalog?_=1494599760082&f%5Bfile_format_sim%5D%5B%5D=vnd.ms-excel+%28XLS%2C+Microsoft+Excel+Format%29&q=

**Comment by awead** [comment]
@cam156 do we want to close this ticket and open another for replacing excel thumbnails with icons? It could be under the post-PCDM milestone.

**Comment by carolyncole** [comment]
@awead I believe that the issue behind this ticket has been solved.  We needed the latest Libre Office to be installed on staging.  It was only installed on QA.  I think we need to ask the users what would be a helpful icon given the size, is a thumbnail really useful for any item with text (word, excel, txt, ect) or should there just be a standard thumbnail...  Lets wait and see if anyone asks us about this before we make more work.  I know I like seeing the thumbnail when I upload as it give me a warm fuzzy that the system got the data correctly...
