### ISSUE TITLE
Powered by Fedora

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere-3#838]
Please, add the 'powered by Fedora logo' to ScholarSphere.
![poweredby_fedora](https://cloud.githubusercontent.com/assets/398837/25856373/cc900406-34a3-11e7-956c-97e3a7aa0a27.jpg)

**Comment by carolyncole** [comment]
@mtribone is checking to see if University policy prohibits this.

**Comment by carolyncole** [comment]
Investigate where we can put this logo if anywhere.  Check the guru policies and possibly go through legal.

**Comment by mtribone** [comment]
Spoke with Jill Shockey about adding the Fedora logo to SS and we both are in the position that it is not a good idea to imply endorsement. However there are exceptions to _linking_ to outside parties and if needed we can speak with Strategic Communications and Licensing about the matter if the logo is a "must-have" for us.

Policy reference:
http://guru.psu.edu/policies/AD52.html#F
http://guru.psu.edu/policies/AD52exemptions.htm

**Comment by mtribone** [comment]
Discussed adding some  additional content to the About page in the "ScholarSphere and The Underlying Technology are Open Source" section.
