### ISSUE TITLE
Remove Collection Icon Overrides

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#84]
The new SVG graphic has been moved to Sufia, so we need to get rid of the overrides in SS. See https://github.com/projecthydra/sufia/pull/947/files for reference.

**Comment by carolyncole** [comment]
fixed in https://github.com/psu-stewardship/scholarsphere/commit/1c3af4b9eda2dd2d5c3e7312ef3bf5bea57596ec
