### ISSUE TITLE
Caching a works stats results exceeds GA daily quota

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#856]
When running the rake task to cache user statics, we exceed our quote for Google Analytics.

`RAILS_ENV=production bundle exec rake scholarsphere:stats:user_stats`

Results in:

```
2017-05-18 10:54:23 -0400 (27483) Sufia::UserStatImporter: Last exception {"errors"=>[{"domain"=>"global", "reason"=>"dailyLimitExceeded", "message"
=>"Quota Error: profileId ga:74306755 has exceeded the daily request limit."}], "code"=>403, "message"=>"Quota Error: profileId ga:74306755 has exce
eded the daily request limit."}:  
{"error":{"errors":[{"domain":"global","reason":"dailyLimitExceeded","message":"Quota Error: profileId ga:74306755 has exceeded the daily request li
mit."}],"code":403,"message":"Quota Error: profileId ga:74306755 has exceeded the daily request limit."}}
rake aborted!
```

**Comment by carolyncole** [comment]
Need migrate the cached analytics from the old system.  We need to migrate and move the items to the Work.

Get the old data into the table and see if this fixes the issue.

GenercFile Analytic becomes and GenericWork analytic for page view and download.
