### ISSUE TITLE
ScholarSphere 3.0 version page

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#857]
What do we want to put in the version release notes for ScholarSphere 3.0?
https://scholarsphere-qa.dlt.psu.edu/versions/

**Comment by carolyncole** [comment]
Accessibility Improvements
Multifile work 
Added Embargo and Lease and removed Private Permissions

Use text from the email that we are sending to the existing users. #717

**Comment by cam156** [comment]
#717

**Comment by olendorf** [comment]
Looks good to me.
