### ISSUE TITLE
Which tables need to be migrated from the old database to the new database

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#859]
Should we pull the entire database and run the migration?

Autocomplete values for subjects and languages would not be needed, because we are now using Questioning Authority for those.

Try migrating everything and see what breaks?

**Comment by carolyncole** [comment]
1) Mysqldump, 
2) mysqlimport
3) rake db:migrate
4) test

**Comment by awead** [comment]
Tables in Prod:
``` bash
+---------------------------------+
| Tables_in_SSprodRails           |
+---------------------------------+
| bookmarks                       |
| checksum_audit_logs             |
| content_blocks                  |
| domain_terms                    |
| domain_terms_local_authorities  |
| featured_works                  |
| file_download_stats             |
| file_view_stats                 |
| follows                         |
| local_authorities               |
| local_authority_entries         |
| mailboxer_conversation_opt_outs |
| mailboxer_conversations         |
| mailboxer_notifications         |
| mailboxer_receipts              |
| migrate_audits                  |
| proxy_deposit_requests          |
| proxy_deposit_rights            |
| schema_migrations               |
| searches                        |
| single_use_links                |
| subject_local_authority_entries |
| sufia_migration_survey_items    |
| superusers                      |
| tinymce_assets                  |
| trophies                        |
| user_stats                      |
| users                           |
| users_10042015                  |
| version_committers              |
+---------------------------------+
```

**Comment by awead** [comment]
SS 2.0 has some tables that I don't think we need anymore. They're all authority tables:
``` bash
> domain_terms
> domain_terms_local_authorities
> local_authorities
> local_authority_entries
> subject_local_authority_entries
```
These have all been subsumed into two new tables, created via QA, `qa_local_authorities` and `qa_local_authority_entries` which handle authority entries for subjects and languages. The entries table is quite large, ~ .5 million rows, and re-importing everything from is rdf sources takes many hours.

Steps should probably be:
1. export qa tables
1. drop target database, i.e. stage-new or qa-new
1. import current production database, minus the above tables
1. run rake db:migrate
1. restore qa tables

**Comment by carolyncole** [comment]
FYI if we synchronize the version_committer table after we run the import it overrides the generated version information.  That table would be one I suggest we also drop if we are not going to import the entire database.

**Comment by awead** [comment]
Actually, there's already a migration in Scholarsphere to drop those old authority tables. I put it in there and completely forgot about it. So, we could import the entire database. In looking at the QA authority tables on staging, they're empty so we'll have to do an authority import anyway.

**Comment by carolyncole** [comment]
We also may not want to import the tiny mce assests as that would override any changes made on the QA or stage system prioir to migration.  Aka we could override any of @olendorf's changes that he has staged on qa or staging.  I may have done that this morning when I ran a full import on staging.

**Comment by awead** [comment]
`tinymce_assets` hasn't been changed since it was first created, so no problem there.

**Comment by awead** [comment]
Using production data, without the tinymce_assets table, works fine. Running db:migrate seems to work. I've updated the migration instructions. We'll need to run it through a complete process to make sure it all works.
