### ISSUE TITLE
Add a search interface for finding collections to add items to

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#863]
On the work upload and the My listing allow the user to search the collections available.

**Comment by carolyncole** [comment]
Looking for something similar to the search and select that you get when authorizing proxies

**Comment by nrm149** [comment]
- will do this with HTML 5 data list

**Comment by mtribone** [comment]
An updated version of select2 with search and multi-select: https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox

**Comment by mtribone** [comment]
Ticket will not be complete until we are able to load more than 100 collections. Look to see how Hyrax has already solved this problem.

Issue: https://github.com/samvera/hyrax/issues/2973
PR: https://github.com/samvera/hyrax/pull/3027
