### ISSUE TITLE
Help page 'Boilerplate Language for DMPs' link is broken

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#866]
The link goes directly to a download link for 
https://scholarsphere-stage.libraries.psu.edu/downloads/cv43nw822

The item still exists in the system, but is just present at a different location:

https://scholarsphere-stage.libraries.psu.edu/downloads/51c18dg40v

**Comment by olendorf** [comment]
Thought I fixed it, but it wasn't, it is fixed now.
