### ISSUE TITLE
Circular navigation for updating filesets

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#873]
When I am editing a file set and I want to update the attached file I go to "Edit this File" (see attached image)

![edit_file](https://cloud.githubusercontent.com/assets/857767/26404247/29f2e476-405f-11e7-94aa-44fb48e79fbb.png)
 
On the next page I see  "Update Attached File"  (see below)  which I thought meant to update the version of the file. If I click brings me right back to the edit screen. I suspect it should read "Update Metadata" or something like that so that I know I am editing the information in the box(es)? 

![edit2](https://cloud.githubusercontent.com/assets/857767/26404382/b0ab1ca4-405f-11e7-8aa2-6328a687dcea.png)

**Comment by carolyncole** [comment]
Change the text on the button to be Save
