### ISSUE TITLE
Update Version Page

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#88]
Update version page to include the fedora 4 information and update the version to 3.0(?)

**Comment by mjgiarlo** [comment]
I wonder if we should go with a minor version update, since our users may not notice a very large difference with 2.0, and our major version updates tend to be marketed and very public?  3.0 is fine too, though!

**Comment by awead** [comment]
What are the semver rules when changing major versions of dependencies?

**Comment by carolyncole** [comment]
From http://semver.org/n -
"What should I do if I update my own dependencies without changing the public API?

That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it's obviously a minor level increment."

I'm thinking we added new functionality, but that is just me.  @mjgiarlo @awead ?

**Comment by carolyncole** [comment]
Ok we are going with 2.2 - not wearing a tu tu :dancers:

**Comment by mjgiarlo** [comment]
Yay for 2.2.  Thanks, y'all!

(I don't think we've followed semver very closely for ScholarSphere -- our versioning has typically been more for marketing than anything else since we have and will probably continue to have 0 downstream adopters of ScholarSphere.)
