### ISSUE TITLE
Adding/Removing from others' collections

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#886]
If you're an admin, you can add files to someone else's collection, but you can never remove them. Hotel California!

**Comment by carolyncole** [comment]
This is really that the remove from collection button does not appear if there is only one item in the colection
![screen shot 2017-06-15 at 2 08 14 pm](https://user-images.githubusercontent.com/1599081/27195300-321e2300-51d4-11e7-94ed-3c92021bd7b4.png)

**Comment by carolyncole** [comment]
![screen shot 2017-06-19 at 9 30 13 am](https://user-images.githubusercontent.com/1599081/27287514-f3994c6c-54d1-11e7-85bd-cc29181584c5.png)

**Comment by carolyncole** [comment]
Put the button back when there is only one item.

**Comment by carolyncole** [comment]
This should be ticketed in hyrax when this item is complete
