### ISSUE TITLE
Removed permissions are not getting copied to contained file sets

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#890]
Given I have a work with two sets of permissions
When I am on the Collaborators edit tab
And I remove one of the permissions
And I click Save
Then I should see the page "Apply changes to contents?"

**Comment by carolyncole** [comment]
@awead here is the place in curation concerns where that occurs: https://github.com/samvera/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/permissions_controller_behavior.rb#L12

I wonder if our changes to where the controller is forwarding based on the collection parameter mucked that up...
