### ISSUE TITLE
Collection edit drop down menu is split

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#90]
The far right menu the arrow is split from the menu bar

Looks like there is plenty of room there for the menu to be on the same line...

![screen shot 2015-03-31 at 9 12 51 am](https://cloud.githubusercontent.com/assets/1599081/6919642/db578bd4-d786-11e4-88d7-2361cf9351fd.png)

**Comment by awead** [comment]
@cam156 where is this? What's the url?

**Comment by awead** [comment]
@cam156 ah, nm, found it!

**Comment by carolyncole** [comment]
@awead I saw you fixed this in sufia.  Since we will not be getting a new version of sufia for the fedora 4 release I changed the milestone to the next version.

**Comment by mtribone** [comment]
![screen shot 2015-06-25 at 10 55 12 am](https://cloud.githubusercontent.com/assets/4163828/8357380/aa00a7a6-1b28-11e5-9420-8520d91f7223.png)
