### ISSUE TITLE
Autocompletion not working on Subject metadata field

### ISSUE THREAD

**Issue by pketienne** [psu-libraries/scholarsphere-3#908]
When editing a record, autocompletion does not work on the Subject field. Other fields (location, language) work okay.

Ref: https://github.com/psu-stewardship/scholarsphere/wiki/File-View%2C-Edit%2C-and-Download

**Comment by carolyncole** [comment]
When I tried this just now it worked.  @informaticianme can you send a link to the work that is not working.

**Comment by pketienne** [comment]
I took another look at this and am not able to reproduce the behavior that I'd gotten before - other than through using a combination of a set of two first letters that do not have any associated terms. I believe it's most likely that the feature was working and I just used one of the few two letter combinations that don't have associated terms. I'm closing this issue.
