### ISSUE TITLE
Link to Information Technology Services on Scholarsphere Footer

### ISSUE THREAD

**Issue by jonibar** [psu-libraries/scholarsphere-3#909]
There's a link to Information Technology Services in the ScholarSphere footer.

Scholarsphere is using its.psu.edu which resolves to http://pennstateit.psu.edu/

The link and name should be updated --or should the link be removed since we're no longer part of ITS?

**Comment by carolyncole** [comment]
change `A service of the University Libraries and Information Technology Services.` to `A service of the University Libraries.`    And change `Penn State |  University Libraries |  Information Technology Services |  Accessibility` to `Penn State |  University Libraries |  Accessibility`
