### ISSUE TITLE
User profile formatting

### ISSUE THREAD

**Issue by jonibar** [psu-libraries/scholarsphere-3#911]
When editing my user profile in SS3.0,  'Remove Highlight Designation' checkbox is not displaying properly in Chrome or Firefox.  It appears to be wrapping and the checkbox is cut off on the left side of the page.
 
![screen shot 2017-06-06 at 2 49 01 pm](https://user-images.githubusercontent.com/2422369/26846584-21da8a5a-4ac8-11e7-8ee2-91fe8059f518.png)

**Comment by carolyncole** [comment]
This issue is no longer in the current UI
