### ISSUE TITLE
Titles are not importing in the correct order

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#913]
Here is a list of multiple titles:
https://gist.github.com/cam156/0eedd5b00a0087c5390400cb65b77058

We should likely apply the title metadaat again on all these records since we are seeing records with them out of order.

**Comment by carolyncole** [comment]
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/actors/curation_concerns/actors/generic_work_actor.rb for live data

**Comment by awead** [comment]
Here's the process I used to fix the mis-ordered titles in production-new:
https://gist.github.com/awead/45c15e78381c60804db7e2aef06ac802
