### ISSUE TITLE
Redacted Content is not transferring correctly.

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#914]
Approximately 45 theses contained signatures from committee members. New PDFs were uploaded that redacted these signatures, but a the newly uploaded file was never marked as a version. When the import took place, only versioned files were imported and the redacted files where never imported.

**Comment by awead** [comment]
Here's a gist of the report I ran to check which files did not have proper versions:

https://gist.github.com/awead/57d3a56d5a997ed2b83a408b0c8e35db

It took about an hour to run.

**Comment by carolyncole** [comment]
This file still has signatures in the original system,  so it will have signatures in the new system: https://scholarsphere.psu.edu/files/8623j707f
 The rest of the files have been updated in the new system.
