### ISSUE TITLE
Item with signatures in the system

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#917]
There is currently at least this item with a signature in the system
https://scholarsphere.psu.edu/files/8623j707f

It is private so it may not be an issue...

**Comment by carolyncole** [comment]
@jonibar found another one:
https://scholarsphere.psu.edu/concern/generic_works/9306sz402

**Comment by olendorf** [comment]
@cam156 

I redacted both with adobe acrobat pro, and uploaded them. The unredacted files are deleted. I sorta messed it up with the versioning, but I think that it is just a learning curve.

I can't set either to private though, so I set them to penn state. The one that was private was anothe r one from Linda Musser that I suspect was either a failed attempt or testing a long time ago. She has/had a bunch of empty/weird ones.
