### ISSUE TITLE
Tag vs keyword

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#927]
This issue was brought up by a user, Paul Kocis <puk4@psu.edu>

google has the following hit:
https://scholarsphere.psu.edu/catalog?f%5Btag_sim%5D%5B%5D=i-STAT

This is the translated hit for the new system:
https://scholarsphere.psu.edu/catalog?f%5Bkeyword_sim%5D%5B%5D=i-stat

You can see that the old facet was tag_sim and the new facet is keyword_sim.

**Comment by carolyncole** [comment]
I went onto google to have it reindex the site as suggested during the standup.

@olendorf We need to decide if we also want to forward the tag url to the keyword url

**Comment by olendorf** [comment]
@cam156 If I understand correctly google has indexed a facet search? 

That seems weird first off. At any rate, I think this should be self correcting as google re-indexes stuff?
