### ISSUE TITLE
Sitemap has works as files

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#930]
Out sitemap.xml still has files links instead of work links

This is working, since we have forwarding to works from files.

for example the site map contains:
http://scholarsphere.psu.edu/files/0p096693w

**Comment by carolyncole** [comment]
We should ticket this in hyrax once it has been completed, as part of this issue

**Comment by mtribone** [comment]
Running `rake sitemap:generate` creates the correct sitemap, but we need to figure out why cap isn't generating the new sitemap.
