### ISSUE TITLE
We need a standard subset of tests for minimal testing when ScholarSphere is released

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#932]
What are the minimal test we should do before we call a release a success?

My minimal testing currently includes
 Create Work
 Create Collection
 Add work to collection
 Delete Work 
 Delete Collection

What else should we be doing?

**Comment by carolyncole** [comment]
@awead @mtribone Your thoughts?

**Comment by awead** [comment]
That's pretty good for me. You could add downloading the file, checking it's index view, and file set show view.
