### ISSUE TITLE
Stats report is using system created date instead of migrated created date

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#933]
The stats report is not looking at our migrated field, but must be looking at the actual system creation date.

This is ok, except when we migrate data.  This morning we got a report that 7324 items were uploaded last week.

**Comment by nrm149** [comment]
- override the date being queried by Sufia w/ our migrated date

**Comment by awead** [comment]
If we change `system_create_dtsi`  to `date_uploaded_dtsi` in Sufia::QueryService, that should give us what we want.

**Comment by awead** [comment]
The stats page isn't rendering because of:

```
NoMethodError: undefined method `[]' for nil:NilClass> - "/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.3.0/gems/sufia-7.4.1/app/services/sufia/statistics/term_query.rb:26:in `query'"
```

Maybe we can fix that so we can have a good feature test of the stats page that demonstrates the issue is resolved?

Related to #1346
