### ISSUE TITLE
Title should be singular with subtitle

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#948]
refs #369

We need to change the work form and collection form to allow for only one title.

We need to add sigular subtitle to work and collection.
This ticket does not include doing this for file set.

**Comment by carolyncole** [comment]
If there are two titles change the second title to subtitle field.  If there are more than two the last title get moved into the subtitle field separated by a semi colin

**Comment by mtribone** [comment]
There is a solution in Hyrax that might be useful.

http://samvera.github.io/customize-metadata-other-customizations.html#making-a-default-property-single-value
