### ISSUE TITLE
Creator order should be preserved in metadata not just implied

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#949]
ref #369

We should have a way of preserving the order that creators were input into the system that does not rely on RDF 1.0 semi ordering.

This could be a secondary display field, or multiple creator fields by number or something else.

There are no changes to the user form, we are just making sure we capture the order in a more permanent way.

**Comment by awead** [comment]
Here's how UVA did it: https://github.com/uvalib/libra-oc/commit/5d88527fcd68ef27a45aaf4f68bb23624d000d85

Later, they refactored it into a module https://github.com/uvalib/libra-oc/commit/0c9be010e344112eb8573ac7af1a475df66be3cf

**Comment by mtribone** [comment]
Are we liking the way that UVA handled it?

**Comment by awead** [comment]
One thing to note is that is looks like they are not using an additional predicate. They are serializing/deserializing the values using one predicate with a delimiter. One drawback to this is that it's not very linked-data-like. That's not really an issue since we aren't publishing any of this information; however, if we were to, we'd the to change this implementation so that the values are persisted using the right predicate. We'd want to use dc.creator for the real values, and have those values published, but then serialize/deserialize them as ordered elements in a different predicate, something like psu.orderedCreator, and definitely *not* publish that predicate.

**Comment by mtribone** [comment]
So do we want to "future  proof" it and go with a different solution? Like the title and subtile solution and use different fields with different predicates?

**Comment by awead** [comment]
I'm leaning towards the two-predicate solution. However, I think @olendorf and @kestlund should weigh-in on this.

**Comment by olendorf** [comment]
@awead Good argument for two predicates, I say do it the right way.

**Comment by mtribone** [comment]
So there is a predicate for `creator`, but is there a predicate for co-creator?
https://github.com/ruby-rdf/rdf-vocab/blob/develop/lib/rdf/vocab/ebucore.rb#L1523

**Comment by mtribone** [comment]
Specialization or Ordinal Properties?

http://infolab.stanford.edu/~stefan/daml/order.html#fig:specialization
http://infolab.stanford.edu/~stefan/daml/order.html#fig:ordinalprop

**Comment by awead** [comment]
I chatted @kestlund on Slack about this and her vote is _I would do all as dc.creator, then use a private ordering predicate or mechanism._

**Comment by mtribone** [comment]
@awead What would be an example of a private ordering predicate or mechanism? Do the two that I referenced above apply? Just trying to understand a little more.

**Comment by awead** [comment]
@mtribone an example would be:
```
<> dc:creator "Adam Wead"
<> dc:creator "Mike Tribone"
<> dc:creator "Joe Schmoe"
<> psu:orderedCreators "Joe Schmoe; Adam Wead; Mike Tribone"
```
`orderedCreators` is a private predicate, something that we define ourselves that isn't defined in an ontology anywhere, except in application code. Scholarsphere would write a semicolon-separated string to orderedCreators, and at the same time, update dc:creator with the individual terms as well.

The above links appear to discuss ordering with pure RDF. That's an ideal scenario, but one that ActiveFedora doesn't support yet. There are different ways to do collections and ordering in RDF, according to the spec, for example, https://www.w3.org/TR/rdf-schema/#ch_collectionvocab

**Comment by awead** [comment]
@cam156 @mtribone since creator is now its own Fedora resource, we could use `ordered_members` from `hydra-pcdm` to persist the order in true LDP fashion.
