### ISSUE TITLE
Migrating proxy deposits task

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#95]
NoMethodError: undefined method `pid' for #<ProxyDepositRequest:0x007f29fb3112e0>
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activemodel-4.1.9/lib/active_model/attribute_methods.rb:435:in`method_missing'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/attribute_methods.rb:213:in `method_missing'
/opt/heracles/deploy/scholarsphere/releases/20150401151428/lib/tasks/migrate.rake:38:in`block (4 levels) in <top (required)>'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in `each'
/opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in`each'
/opt/heracles/deploy/scholarsphere/releases/20150401151428/lib/tasks/migrate.rake:37:in `block (3 levels) in <top (required)>'
Tasks: TOP => scholarsphere:migrate:migrate_proxy_deposits
(See full trace by running task with --trace)

**Comment by awead** [comment]
@cam156 this needs to be done so migrating will work.

**Comment by carolyncole** [comment]
@awead I wonder if we should just delete our tasks and use the sufia ones
https://github.com/projecthydra/sufia/blob/master/sufia-models/lib/tasks/migrate.rake#L1-L21
