### ISSUE TITLE
Create a deployment backout plan

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#952]
Create a wiki page with instructions on how to roll back via cap

**Comment by carolyncole** [comment]
If the cap deployment is unsuccessful  no roll back is needed
   The current directory may have moved if cap was in cleanup when it failed
If the cap deployment is successful roll back

**Comment by awead** [comment]
FYI, Capistrano logs each step of the process to your terminal after you run `deploy`. If you see `deploy:symlink:release` execute successfully, then the app has been deployed. There are six additional steps that follow this, in order:

* `deploy:resquepoolrestart`
* `deploy:resolrize`
* `deploy:passenger:config_update`
* `deploy:cleanup`
* `rbenv_custom_ruby_cleanup:purge_old_versions`
* `deploy:log_revision`

If any of the above fail, it may appear that the deploy failed, but it didn't. The new application version is out there. It's possible to re-run these tasks, if needed. Ex:
`bundle exec cap deploy:log_revision BRANCH_NAME=[release-branch]`
But not all of them are critical for a successful release.

**Comment by carolyncole** [comment]
Added a wiki page for rolling back:

https://github.com/psu-stewardship/scholarsphere/wiki/Deployment-Rollback-Procedure
