### ISSUE TITLE
As a user, I would like to search on parts of filenames and titles so that I can find them easier.

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#956]
The current search on titles and filenames works for individual words but for file names that are a single "word" ie. no spaces it doesn't work so well. For instance

https://scholarsphere.psu.edu/concern/generic_works/wd375w48d

with file name and title TAXgg_Xerumbrepts_100m.tif can't be searched on xerumbrepts

**Comment by carolyncole** [comment]
configure the solr parser to allow this for any strings:
break on on '_' '.' '-' & '/'   This should work for both FileSet labels and Work titles, and other strings in the system.
