### ISSUE TITLE
Embargo Choices Present Institution Name as a Choice

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/scholarsphere-3#959]
When I am creating a new work or edit and existing work and choose embargo, I get "Institution Name" as a choice instead of "Penn State."

**Comment by mtribone** [comment]
![screen shot 2017-06-19 at 10 37 55 am](https://user-images.githubusercontent.com/4163828/27291177-8a7800d2-54dd-11e7-8369-f228357a1c35.png)

**Comment by mtribone** [comment]
![screen shot 2017-06-19 at 10 52 21 am](https://user-images.githubusercontent.com/4163828/27291199-9250c424-54dd-11e7-809f-e8663dbbbfd6.png)

**Comment by carolyncole** [comment]
This is also an issue on the batch edit screen

**Comment by carolyncole** [comment]
Should be an i18n change, but needs to be tested on New/edit Work, Embargo Management, and batch edit.
