### ISSUE TITLE
Description/Abstract/summary is not showing on work show page

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#967]
This should be showing on the show page.

**Comment by awead** [comment]
@olendorf can you provide an example? I'm not seeing this with new works I create.

**Comment by carolyncole** [comment]
@olendorf Although it is not part of the metadata section you can see it is available directly under the title on this record.  Can you give us an example of one where the description is not being displayed?
![screen shot 2017-07-07 at 9 37 17 am](https://user-images.githubusercontent.com/1599081/27960082-f526159a-62f7-11e7-8f2f-980871d22339.png)

**Comment by mtribone** [comment]
The field is in the search results view.

**Comment by mtribone** [comment]
No longer an issue.
