### ISSUE TITLE
Change BrowseEverything to allow a maximum total upload size

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#975]
Allow a configuration in browse everything to set a maximum total upload size. Aka only allow 20G in any file amount 20x1G or 10x2G or 1 5G+1 15G ect.

**Comment by awead** [comment]
I'm not sure setting the total upload limit on the BE side will be effective. You could make multiple requests to BE and assemble a large list of files. Maybe the limit needs to be set in Scholarsphere?

**Comment by awead** [comment]
@olendorf is in agreement that enforcing the limit should be placed in the Scholarsphere UI, if that's where the issue lies. Otherwise, the limit would be enforced in BrowseEverything per provider. Thoughts? @cam156
