### ISSUE TITLE
Proxy depositor is not getting set correctly

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere-3#978]
I can upload a new work on behalf of @cam156 and it looks like:
```
> work.on_behalf_of
=> "cam156"
> work.depositor
=> "cam156"
> work.proxy_depositor
=> "cam156"
```
But I would expect `proxy_depositor` to be me and not her.

**Comment by carolyncole** [comment]
@awead was this work completed?

**Comment by awead** [comment]
@cam156 no, I don't believe so, but we should verify it's still a problem.

**Comment by awead** [comment]
@cam156 Behavior is still the same. Do you think this is correct? @olendorf

**Comment by olendorf** [comment]
@awead  its not correct, it should put the "blame" on the proxy_depositor correctly. It is actually important for matters of provenance and trust too.

**Comment by awead** [comment]
I think the problem was introduced in #895, which was meant to fix another problem. Given the race condition, I'm not sure of a clear way to fix this. Perhaps using `current_user` as the value for proxy depositor.
