### ISSUE TITLE
Administrators Edit Proxy deposit information

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#979]
Allow Administrators access to proxy deposit information for editing.

Allow an administrator to change the depositor and the on behalf of fields when editing.

**Comment by carolyncole** [comment]
For admin users only: Show proxy deposit field and depositor on the work edit page and the batch edit screen.  
Put these in a warning block (with a picture of Shera!)

Needs to be copied down to containing File Sets.

**Comment by awead** [comment]
@olendorf The way this currently works is only existing users can be proxied. In other words, users who have logged into the Scholarsphere at least once and have a record of their network id, like `xyz123`, present in the application's database. Is this okay, or do you need to ability to proxy any user id, regardless of its status?
