### ISSUE TITLE
Weekly activity summary doesn't show resource type

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/scholarsphere-3#981]
The column is empty for this, but would be really helpful to me.

**Comment by carolyncole** [comment]
@olendorf I notice the report is now giving you a list of file instead of a list of works.  Did you want the information at the work level or the file level, or a bit of both

**Comment by olendorf** [comment]
Here is something that I think gives all the information we might want in a pretty decent format. 

[sample_report_YYYY-MM-DD_YYYY-MM-DD.xlsx](https://github.com/psu-stewardship/scholarsphere/files/1142288/sample_report_YYYY-MM-DD_YYYY-MM-DD.xlsx)
