### ISSUE TITLE
Migrate our current user from the database into fedora

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#989]
Textual Data from Creator that we need to convert to the Fedora User.

If the creator is the same as the  the display name for the depositor then that is a fairly clear link to that person.

Create a report with the unique names and the associated works for the other entities so that we can figure out what to do.

**Comment by carolyncole** [comment]
Here is a report on the creators in ScholarSphere production currently:
https://scholarsphere.psu.edu/solr/collection1/select?q=*%3A*&fq=has_model_ssim%3AGenericWork&rows=0&wt=json&indent=true&facet=true&facet.field=creator_sim&facet.limit=7000&facet.sort=index

We have some that are lists, some that are departments or programs and one that is completely bogus: '[Your Name Should Automatically Appear Here]'

There are 150 occurrences of semi colon in the report, which leads me to believe we have that many occurrences of multiple creators in one creator field.

**Comment by carolyncole** [comment]
We have create also have creator in multiple formats.  "last, first" "first last" "last, first Initial [middle Initial]" "first middle last [title]"

**Comment by carolyncole** [comment]
@olendorf We have some works (52) with indeterminant creators in the system right now.  Some people have just put in their initials or first names, others match multiple people (there are two Kurt B Bakers).

The ones that match multiple people will need to be dealt with after the migration, but the ones where initials or first names were used instead of people could be updated now.  Do you think there is anyone at the library that might have time to unravel this?  I would mean editing the work and updating the creator to be more descriptive, or identifying what the creator should be and giving the list to me to update the work.

Here is a current report:

Ar                                                                                                                                                 
http://scholarsphere.psu.edu/concern/generic_works/5712m916w                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m911h                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m915m                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m9132                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m9107                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m902j                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m905c                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m906n                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m903t                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m907x                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m9018                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m9086                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m9043                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m9000                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m899f                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m918f                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m912s                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m9175                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m909g                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/5712m914b                                                                                       
ME Bell                                                                                                                                            
http://scholarsphere.psu.edu/concern/generic_works/xk81jk388                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/8623j190f                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/8623j1628                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/8623j157d                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/8623j1717                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/8623j1938                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/8623j1874                                                                                       
Kurt Baker                                                                                                                                   
http://scholarsphere.psu.edu/concern/generic_works/sf268k76z                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/7d278z22f                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/sf268k688                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/sf268k69j                                                                                       
Gina                                                                                                                                               
http://scholarsphere.psu.edu/concern/generic_works/4j03cz680                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/mg74qm08d                                                                                       
Holt Ann                                                                                                                                           
http://scholarsphere.psu.edu/concern/generic_works/2z10wq262                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/n296wz13w                                                                                       
Tao Yun                                                                                                                                            
http://scholarsphere.psu.edu/concern/generic_works/w3763700m                                                                                       
http://scholarsphere.psu.edu/concern/generic_works/ms35t8816                                                                                       
Andrew                                                                                                                                             
http://scholarsphere.psu.edu/concern/generic_works/7h149p866                                                                                       
Andy                                                                                                                                               
http://scholarsphere.psu.edu/concern/generic_works/r781wk28w                                                                                       
B Murray                                                                                                                                           
http://scholarsphere.psu.edu/concern/generic_works/sf268713m                                                                                       
Chad                                                                                                                                               
http://scholarsphere.psu.edu/concern/generic_works/w0892c93k                                                                                       
Chen Min                                                                                                                                           
http://scholarsphere.psu.edu/concern/generic_works/j098zb128                                                                                       
David
http://scholarsphere.psu.edu/concern/generic_works/j38606956
F He
http://scholarsphere.psu.edu/concern/generic_works/5712mc436
Gd
http://scholarsphere.psu.edu/concern/generic_works/pg15bd93n
Ids
http://scholarsphere.psu.edu/concern/generic_works/6682x395j
John
http://scholarsphere.psu.edu/concern/generic_works/cn69m417n
Li R
http://scholarsphere.psu.edu/concern/generic_works/1r66j1131
Linda
http://scholarsphere.psu.edu/concern/generic_works/zp38wc62h
Ms
http://scholarsphere.psu.edu/concern/generic_works/9k41zd50j
Ub
http://scholarsphere.psu.edu/concern/generic_works/w9505046h
V Vand
http://scholarsphere.psu.edu/concern/generic_works/sf268k92b

**Comment by olendorf** [comment]
@cam156  UGH...why people do this? Looks like it was the same folks doing this. AR for instance all looks the same from spot checking. However, there are other authors too that can be added. 

I can do some, but I will see if we can get someone to help from PAMs too.

**Comment by carolyncole** [comment]
Current plan of attack:
1. Get a list of all creators in the system
    ```
    resp = ActiveFedora::SolrService.instance.conn.get 'select', params: { rows: 0, "facet.limit"=> 10000, "facet.field" =>"creator_sim", fq:"has_model_ssim:GenericWork"}
    creator_facet_resp = ActiveFedora::SolrService.instance.conn.get 'select', params: { rows: 0, "facet.limit"=> 10000, "facet.field" =>"creator_sim", fq:"has_model_ssim:GenericWork"}
    creators = creator_facet_resp["facet_counts"]["facet_fields"]["creator_sim"].select {|creator_or_count| creator_or_count.class == String}
    ```
1. Look up each creator in the User table
    ```
    local_users = creators.map do |creator|
      name_parts = creator.split.map(&:upcase).map{|part| part.length == 1 ? "% #{part}%" : "%#{part}%"}
      query = name_parts.map{|name_part| "UPPER(display_name) like ?"}.join(' AND ')
      User.where(query,*name_parts)
    end
    ```
1. create an Agent Alias for the creator
    1. The creator has only one User record
        1. compare the name to make sure it is valid
        1. For a valid name create a creator record with the display name, psu login, first and last name
        1. For an invalid name skip to next step
    1. The user has no User records
        1. Use Ldap Disambiguation to find the user
        ```
        disambiguated_creators = no_creators.map{|creator|LdapDisambiguate::Name.disambiguate(creator) rescue puts creator}
        ```
        1. validate the name comparison
        1. For a valid name create a creator record with the display name, psu login, first and last name
        1. For an invalid name skip to next step
    1. The user has multiple records  (or invalid match to LDAP)
        1. create an Agent that has the display name set
           1. put entire contents of name into surname
        1. output to a report for human intervention
         
1. Look up works for the creator
    ```
    resp = ActiveFedora::SolrService.instance.conn.get 'select', params: { rows: 1000, fl: 'id,depositor_tesim', fq:["has_model_ssim:GenericWork", "creator_sim:\"#{creators[0]}\""], q:''}
    resp["response"]["docs"]
    ```
1. Attach Agent Alias to works
