### ISSUE TITLE
Create a work form for inputting Orcid and display name (default to depositor Orcid & ldap name)

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#990]
This is the user interface for the work edit and new forms and collection edit and new forms

Internal author use the ldap query
External Author ORCID or free text
Text field for display on work

**Comment by olendorf** [comment]
here is the ezid form for creators that is pretty complex (maybe too much so)

![ezid_creator_form](https://user-images.githubusercontent.com/857767/28216720-a2798668-6880-11e7-9f17-c44c38bb6950.png)

**Comment by carolyncole** [comment]
For PSU people we can use the same form as proxies on the profile edit.

**Comment by val99erie** [comment]
The first name & last name fields for a creator will be on the work/collection form once this PR is merged:
https://github.com/psu-stewardship/scholarsphere/pull/1026/files

And then for this story, you can just add the new fields to the form.

**Comment by mtribone** [comment]
Can display name be multiples?

**Comment by mtribone** [comment]
This is a display name for a *work* and is a single text field

**Comment by mtribone** [comment]
related to https://github.com/psu-stewardship/scholarsphere/issues/991
