### ISSUE TITLE
Keep track of aliases

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#991]
When a user enters a different display from the default from LDAP or ORCID we should attach that as an Alias to the user Dependent on #989 & #990

**Comment by carolyncole** [comment]
The aliases would be generated by a user changing the display name on the work form or the collection form.

**Comment by carolyncole** [comment]
Add  (display name) alias to the form for the person

**Comment by carolyncole** [comment]
Is the alias a property of the work or an additional object linked to the person.

As person has many Aliases, String or Object, we are leaning towards Objects.

**Comment by awead** [comment]
After discussion today, the prevailing thought is that  Alias will be a property of Work, and Person will be a property of Alias:

``` bash
[Work](1) <--> (n)[Alias](n) <--> (1)[Person]
```

The work form can remain the same, with an added display name field that causes a new alias to be created or an existing one to be re-used. The net result of this would be:

1. A work's creators are all Alias objects
2. A person must have at least one alias in Fedora, even if it is to display only their first and last name with no changes from their person record.
3. When the same display name is used in a different work, the same alias should be used. Ideally, we should not create multiple alias resources with the same display name.

## Impacts

Work presently links to Person resources, so this would need to be redefined in the `HasCreators` module, and changed to `has_and_belongs_to_many :aliases` for example. The alias would then have a display name property and link to Person:

``` ruby
class Alias < ActiveFedora::Base
  property :person, class_name: 'Person', predicate: ::RDF::Vocab::FOAF.[TBD]
  
  property :display_name, predicate: ::RDF::Vocab::FOAF.[TBD], multiple: false do |index|
    index.as :stored_searchable, :symbol
  end
end
```
