### ISSUE TITLE
Collection Delete button has a different confirmation

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#995]
When I click delete collection from the user's dashboard collection listing I get a ScholarSphere message.

When i click the delete button from the collection I get a different message:
![screen shot 2017-07-14 at 12 17 40 pm](https://user-images.githubusercontent.com/1599081/28220772-b7d29cf8-688e-11e7-8882-8f873d1ac26a.png)

**Comment by carolyncole** [comment]
This should look like:
![screen shot 2018-04-04 at 10 37 22 am](https://user-images.githubusercontent.com/1599081/38314477-49e77278-37f4-11e8-9aa9-db65e0f65a00.png)

**Comment by cam156** [comment]
Include accessibility testing of the modal.
