### ISSUE TITLE
Large Numbers of Files in A Work

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#996]
I would like to add a large number of files in a work ~3000 files

Currently this either breaks or becomes very slow at ~300 files.

**Comment by nrm149** [comment]
Ticket may be taken cared of by other efforts. Moving from 3.5 to 3.6

**Comment by carolyncole** [comment]
@olendorf When we do this we will need to either drop ordering or do something special to handle it.

**Comment by carolyncole** [comment]
One specific use case: https://scholarsphere.psu.edu/concern/generic_works/h1831cm636

**Comment by olendorf** [comment]
@cam156 ordering of the files?

**Comment by carolyncole** [comment]
We should sort the files alphabetically by File title by default
We can drop support for the File Manager ordering, but keep support for Representative Media & Thumbnail
We can add a sort to the work show page to sort by date uploaded

1. Reverse File Membership - File point at work vs Work pointing at the File #1309 
1. Change jobs and or services to account for new relationships #1310
1. Change the work display to show search result Files in Work (like collection show) #1311
1. Add Sort order work display #1312
1. Remove File Ordering from File Manager #1313 
1. Update work edit for to make thumbnail and representative work choosing easier #1314
1. Test with a large dataset #1317
1. Update existing data to include the new relationship #1315 
1. Remove the old relationship from the model/ solr/ fedora #1316

**Comment by mtribone** [comment]
Close out the ticket and related tickets and focus the work on large amount of small files in the new SS.

**Comment by mtribone** [comment]
Focus of the project has changed and we are moving to a new ScholarSphere that may not be dependent on the current technology stack.
