### ISSUE TITLE
Keyword with special characters creates bad search

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#998]
When you include special characters in the keyword the search produced by clicking the link on the work is bad
![screen shot 2017-07-17 at 7 04 29 am](https://user-images.githubusercontent.com/1599081/28265546-629f8b60-6abe-11e7-8f23-26bfbc941257.png)

The facet with the keyword seems to work, but however we are creating the link in the work seems bad
Facet Link: `https://scholarsphere-qa.libraries.psu.edu/catalog?f%5Bkeyword_sim%5D%5B%5D=%2755+chet+atkins`
Work Link: `https://scholarsphere-qa.libraries.psu.edu/catalog?f%5Bkeyword_sim%5D%5B%5D=%26%2339%3B55+chet+atkins`

**Comment by awead** [comment]
Fixed. See https://scholarsphere-qa.libraries.psu.edu/concern/generic_works/0p2676t33d

**Comment by awead** [comment]
Doesn't work with featured works.
