### ISSUE TITLE
Work Metadata order

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/scholarsphere-3#999]
There does not seem to be any logical order to how we are displaying metadata.

We are not showing required first, we are not showing it in alpha order.

![screen shot 2017-07-17 at 7 59 28 am](https://user-images.githubusercontent.com/1599081/28267010-12119b9a-6ac6-11e7-8c5c-d5d63f4e587b.png)

**Comment by awead** [comment]
The order corresponds to the order in `app/views/curation_concerns/base/_attribute_rows.html.erb`

**Comment by awead** [comment]
@olendorf is there a specific order you'd like here, or should we go with alpha?

**Comment by carolyncole** [comment]
Follow the order as exists in the form.  Total items and size should be at the bottom

**Comment by mtribone** [comment]
Where should lease and embargo be located?

**Comment by awead** [comment]
Not slated for 3.1. Should be put out in next release.

**Comment by mtribone** [comment]
Change has been merged, but not deployed to QA yet.
